### ISSUE TITLE
Bad gateway when machine translating big repos

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1011]
## Problem

<img width="1083" alt="image" src="https://github.com/inlang/inlang/assets/58360188/bdfae056-0926-4411-ad79-7d340d26eb89">

After 100 - 300 translations this happens.

You can reproduce it with cal.com

**Comment by NilsJacobsen** [comment]
@inlang/cli

**Comment by felixhaeberle** [comment]
@NilsJacobsen I had a look at this. We should probably batch the translations together because right now, we do single fetches. This is probably not that efficient 😅 Furthermore, I could not find out why we have got this "Bad Gateway" error, but it likely has something to do with 100+ of fetches.

**Comment by felixhaeberle** [comment]
@inlang/cli Closing this because it has not happend anymore & can't reproduce it. 
If it does occur again, I will reopen.

**Comment by omarkhatibgg** [comment]
Hey @felixhaeberle, 

~~I'm getting the same error, Bad Gateway, I have a monorepo but this is a one app with around 500 keys, and I noticed that it only translate half of them~~

It's work fine again, but I'm getting 

```bash
 WARN  Some bundles could not be translated.                                                                                                                                                           8:18:26 PM


 WARN  403 Forbidden: translating from en to tr                                                                                                                                                        8:18:26 PM
403 Forbidden: translating from en to tr
403 Forbidden: translating from en to uk
403 Forbidden: translating from en to es
```

**Comment by Lexumiii** [comment]
> Hey [@felixhaeberle](https://github.com/felixhaeberle),
> 
> ~I'm getting the same error, Bad Gateway, I have a monorepo but this is a one app with around 500 keys, and I noticed that it only translate half of them~
> 
> It's work fine again, but I'm getting
> 
>  WARN  Some bundles could not be translated.                                                                                                                                                           8:18:26 PM
> 
> 
>  WARN  403 Forbidden: translating from en to tr                                                                                                                                                        8:18:26 PM
> 403 Forbidden: translating from en to tr
> 403 Forbidden: translating from en to uk
> 403 Forbidden: translating from en to es

Getting this error too. 403 Forbitten: Translaing... 

Also getting the DB not started and the BAD Gateway error sometimes. This starts to be come more and more annoying and well have to switch away from paraglide.
