### ISSUE TITLE
refactor: Add a single point of truth for commands in ide-extension

### ISSUE THREAD

**Issue by openscript** [inlang/monorepo#1044]
## Problem

Commands definition is currently distributed `main.ts`, `package.json`and individual commands. There is duplication with the title and id in several places.

## Proposal

A single point of truth for commands within the ide extension should be created.

**Comment by felixhaeberle** [comment]
@openscript I second this, but as I remember correctly - please correct me if I'm wrong" - you have to specify the command in package.json to "register" it and then also "define" it somewhere in code that it can be executed. 

Besides of that, I don't see that we need to define them multiple times.

**Comment by openscript** [comment]
> @openscript I second this, but as I remember correctly - please correct me if I'm wrong - you have to specify the command in package.json to "register" it and then also "define" it somewhere in code that it can be executed.
> 
> Besides of that, I don't see that we need to define them multiple times.

It's easy to read the title and id of a command from `package.json`.

**Comment by felixhaeberle** [comment]
@openscript Yep, but how could this be then used as single source of truth if I need to know which code belongs to which command, there has to be some kind of double assignment right? or at least a pointer in code which says command === x => code.

Besides of that, we should aim to remove all duplications.

**Comment by openscript** [comment]
It's just a set of `const`s coming from the `package.json`. I think I can do it within 2h.

**Comment by openscript** [comment]
@felixhaeberle I estimate <2h for this.

**Comment by felixhaeberle** [comment]
@openscript Perfect, lets go ahead! 🏃‍♂️

**Comment by felixhaeberle** [comment]
@openscript Can you provide an ETA for this?

**Comment by openscript** [comment]
22nd of September
