### ISSUE TITLE
refactor: reorganize event management of ide-extension

### ISSUE THREAD

**Issue by openscript** [inlang/monorepo#1047]
## Problem

Right now the event management is spread out. Decorators and commands listen and emit events. This renders in duplicate code, low test-ability and spaghetti code.

## Proposal

Have a central orchestration for event. Rethink throttling.

**Comment by felixhaeberle** [comment]
@openscript I'm currently working on the lint feature #724 , I you want to invest time and have some thoughts, you could tackle this in addition to the "single command definition" #1044 issue too.

What would you estimate for this one (and please also give an estimate in #1044)?

**Comment by openscript** [comment]
@felixhaeberle Should we include event throttling/debouncing? I would say its around 2-3h.

**Comment by felixhaeberle** [comment]
Yes, whatever makes the ide extension faster and more responsive, we should invest in.

**Comment by felixhaeberle** [comment]
@openscript Can you provide an ETA for this?

**Comment by openscript** [comment]
22nd of September

**Comment by openscript** [comment]
`throttling/debouncing` is not useful here, as the events are fired once per user interaction.
