### ISSUE TITLE
i18next plugin parser does not support plurals

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1069]
This problem was comming up in this PR: https://github.com/mifi/lossless-cut/pull/1653

## Problem

i18next has pluarls support -> https://www.i18next.com/translation-function/plurals

- You need to suffix the key with _one, _many ... (there are multiple options)
- The frontend code should look for a count option in the t function `t('key', {count: 1})`

The current implementation of the parser is just passing the key, causing the ide extension to handle the wrong key.

## Proposal

Improve the plugin parser to recognize the count option as the ns option and suffix the key. 

@inlang/plugins @inlang/ide-extension

**Comment by samuelstroschein** [comment]
Inlang core eventually needs plugralization support.

**Comment by samuelstroschein** [comment]
@NilsJacobsen I assigned you because we need to default assign issues to ensure they get handled

**Comment by felixhaeberle** [comment]
@NilsJacobsen @NiklasBuchfink @samuelstroschein Great to see that the Message format we adopted now supports plurals ootb. We can now go ahead and improve the plugin parser.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink but the i18next plugin doesn't parse plurals :)
