### ISSUE TITLE
Missing state update forces user to reload after login redirect

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/monorepo#1170]
## Problem

The Gitfloat doesn't update after login. This forces the user to reload and clone the repo again. We open up the login in a new tab to prevent exactly that.

## Proposal

- state updates
- no (possibly long) reload required

## Additional information

- same behavior in Chrome and Firefox
- only happens on first use (no GitHub login cookie)

## Steps to reproduce

1. Open the project in the editor
2. Login with GitHub
3. Try to edit after redirect

**Comment by NiklasBuchfink** [comment]
Hopefully, issues around this topic are now fixed by:
- handling windows different
- adding the localStorage.user to the Gitfloat createEffect

Please reopen this, if there are still issues.

**Comment by janfjohannes** [comment]
@NiklasBuchfink   as discussed the issue seems to be the storage event not firing reliably
