### ISSUE TITLE
[bug] Crash of  @inlang/cli machine translate with string 'ability.DEFAULT'

### ISSUE THREAD

**Issue by keldaan-ag** [inlang/monorepo#1185]
### Problem

When using: `npx @inlang/cli machine translate -f`
with string 'ability.DEFAULT'
I have the error:

```
 ERROR  Cannot read properties of undefined (reading 'value')                                                                                                           09:19:48  

  at Command2.translateCommandAction (/C:/Users/arnau/Desktop/pokemonAutoChess/node_modules/@inlang/cli/dist/main.js:70874:45)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

When debugging the inlang cli, it seems that the string "ability.DEFAULT" parsing result in an empty elements array pattern
![image](https://github.com/inlang/inlang/assets/24555243/a6ab0b8a-29e5-41bc-9620-1537d64463a3)

resulting in a crash when calling `elements[0]`
`text: message.pattern.elements[0].value`

### Expected behavior

a correct translation of the string "ability.DEFAULT" without inlang cli crash

### Reproduction

```
git clone https://github.com/keldaanCommunity/pokemonAutoChess
npm install
npm run translate
```

### `inlang.config.js` file

```JavaScript
/**
* @type { import("@inlang/core/config").DefineConfig }
*/
export async function defineConfig(env) {
	const { default: i18nextPlugin } = await env.$import('https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@3/dist/index.js');

	const { default: standardLintRules } = await env.$import('https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js');

	return {
		referenceLanguage: 'en',
		plugins: [
			i18nextPlugin({ pathPattern: 'app/public/dist/client/locales/{language}/translation.json' }),
			standardLintRules(),
		],
	};
}
```

### `npx @inlang/cli@latest config validate` file

```sh
npx @inlang/cli@latest config validate
i 🔎 Validating the config file...                                                                                                                                      09:31:56
√ 🎉 Inlang config is valid!
```

**Comment by samuelstroschein** [comment]
@keldaan-ag thanks for opening the issue!

I assigned @felixhaeberle the person of contact for the @inlang/cli.

**Comment by felixhaeberle** [comment]
This is an issue with the `plugin-i18next`, `element` does not expose a value.
Possibility of reserved word "default" (in JS) gets treated differently.

```ts
{                                                                                                                                                                                    01:07:12
  type: 'Message',
  id: {
    type: 'Identifier',
    name: 'ability.DEFAULT'
  },
  pattern: {
    type: 'Pattern',
    elements: [] // element is empty
  }
}
```
Assigning @NilsJacobsen for @inlang/plugins

**Comment by keldaan-ag** [comment]
I think that the problem is not the key "Ability.DEFAULT" but the empty string.

I just realized i wrote
```
"Ability.DEFAULT": ""
```

And its this empty string that is crashing the c:li (cause theres no token to traduce)

Expected behavior:
From my point of view, i think that an empty string translation should be "" in every language.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Can you verify that empty strings are now being handled correctly by the i18next plugin?

**Comment by NiklasBuchfink** [comment]
The issue now no longer exists.

> From my point of view, i think that an empty string translation should be "" in every language.

The expected behavior is now as described. Therefore, I am closing this issue.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Great!! 🥳
