### ISSUE TITLE
[bug] VSCode linting fails

### ISSUE THREAD

**Issue by Yelinz** [inlang/monorepo#1209]
### Problem

The VSCode extension cant lint multiple translation calls one after another.
![vscode extension linting problem](https://github.com/inlang/inlang/assets/30687616/d12d27a0-b59a-402b-be04-1b6e31f4edfc)

### Expected behavior

No error

### Reproduction

1. Have multiple translation in one line without a space between

### `inlang.config.js` file

```JavaScript
/**
* @type { import("@inlang/core/config").DefineConfig }
*/
export async function defineConfig(env) {
  const { default: sdkPlugin } = await env.$import('https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.11.0/dist/index.js');

  const { default: jsonPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js",
  )

  const { default: standardLintRules } = await env.$import('https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js');

  return {
    referenceLanguage: 'en',
    plugins: [
      jsonPlugin({
        pathPattern: "./languages/{language}.json",
      }),
      sdkPlugin({
        languageNegotiation: {
          strategies: [{ type: "url" }],
        },
      }),
      standardLintRules(),
    ],
  };
}
```

### `npx @inlang/cli@latest config validate` file

```sh
files                                                                                                                                                           21:46:52
files                                                                                                                                                           21:46:52
files                                                                                                                                                           21:46:52
ℹ 🔎 Validating the config file...                                                                                                                              21:46:52
✔ 🎉 Inlang config is valid!
```

### Other information

v0.9.3 inlang extension

**Comment by samuelstroschein** [comment]
Another one for @inlang/plugins :D

**Comment by NilsJacobsen** [comment]
It's probably due to the plugin parser.
@Yelinz we are currently refactoring the plugins. We gonna put this on the list.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink can you verify that this is fixed? 

@Yelinz We refactored the codebase and you now need a project.inlang.json file. See https://inlang.com/documentation/manually-create-project

**Comment by felixhaeberle** [comment]
@Yelinz We are releasing a new vscode version today which should fix this.

<img width="608" alt="Bildschirmfoto 2023-09-12 um 10 14 31" src="https://github.com/inlang/monorepo/assets/34959078/61c7bffe-7cec-4f2a-ada4-2fb812cf5b66">

Please remember to create a `project.inlang.json` like https://inlang.com/documentation/manually-create-project
You can then delete the old `inlang.config.js`.

**Comment by jannesblobel** [comment]
@Yelinz 
Furthermore, we would love to get feedback on our new init process and the marketplace. Feel free to share your thoughts and ups and downs. :) 🦖
