### ISSUE TITLE
[feature] support for variants in editor

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1217]
## Description

The core refactoring enabled variants. The editor needs to support variants. 

## Tasks

- [ ] ...
- [ ] ...

**Comment by samuelstroschein** [comment]
@inlang/editor the editor needs variant support. for the MVP version, it probably easiest if we have a matric view like https://github.com/unicode-org/message-format-wg/blob/main/spec/syntax.md#complex-messages. 

i give you the decision when variants should be supported in the editor. adjust the start and target date in the roadmap.

**Comment by NiklasBuchfink** [comment]
I would prioritize as follows:
1. Make the editor work again for current users (after the refactoring)
2. Improve the change management (no data loss anymore)
3. Introduce variants

If we could do 1 & 2 next week, we could start with this on August 21 (best case).

**Comment by NilsJacobsen** [comment]
Why does the editor need to support it now? I thought we can do that step by step along growth topics after the refactoring? We only have one variant with no selectors for now. 

Does something speak against it?

**Comment by samuelstroschein** [comment]
Yo sorry, this roadmap item is after the refactoring is complete. This is unrelated to the core refactoring

**Comment by NiklasBuchfink** [comment]
@samuelstroschein I close this as not planned for the same reason as https://github.com/inlang/monorepo/issues/1069#issuecomment-1713807746.

**Comment by felixhaeberle** [comment]
@inlang/editor we talked about this last week. is now the time to reopen this, or focus not on variant support but growth?

**Comment by NilsJacobsen** [comment]
Let's reopen this if we hit the 30% goals.
