### ISSUE TITLE
bundle standard lint rules plugin by default with `createApp`?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1253]
## Context

https://github.com/inlang/inlang/issues/1139#issuecomment-1642401607

**Comment by felixhaeberle** [comment]
@samuelstroschein Can this be closed?

**Comment by samuelstroschein** [comment]
@felixhaeberle yes. it's so easy now to add lint rules + we can bundle them by default in `inlang.com/new`
