### ISSUE TITLE
[bug] When i open the Page, sometimes all translations are empty

### ISSUE THREAD

**Issue by Sansumaki** [inlang/monorepo#1256]
### Did you check if the config file includes errors?

- [X] Yes, I have validated the config file

### Problem

When i open the webpage on a browser, where i never opened the page before, but also in a browser on a pc i already used the page, all the texts are empty. I have 3 languages de, en, es and all are fully translated. after a browser reload everything is fine. 

i could not extract more information by now, because i don't know what i should looking for. 

### Reproduction

Hard to reproduce, because it seems random for me right now. 

if you give me some hints, where to  look if it happens again, i can provide more infos.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 12.99 GB / 31.20 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @inlang/sdk-js: ^0.11.8 => 0.11.8
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.22.3
    svelte: ^4.0.5 => 4.1.1

But also happens on Mobile (iPhone)
```

**Comment by ivanhofer** [comment]
Ok, we will take a look at the issue probably next next week.

**Comment by jannesblobel** [comment]
Unfortunately, Ivan has passed away, and we are trying to find a solution.
I will close this issue as not planned for now when we have a solution.
