### ISSUE TITLE
add option to hide the `sourceLanguageTag` from the url

### ISSUE THREAD

**Issue by ivanhofer** [inlang/monorepo#1270]
Allow developers to choose if they want to include the `sourceLanguageTag` in the url.
Instead of `/en/settings`, `/settings` should be displayed.

**Open question:**
How to do an auto-redirect to the users preferred language?
- don't do any redirects?
- redirect a single time and store info in a cookie?

**Comment by samuelstroschein** [comment]
@ivanhofer i think you are offering too many options. choose a sensible default and push back against feature requests. the default in this case seems to be hiding the source language tag

**Comment by samuelstroschein** [comment]
@ivanhofer i just double checked google.com. no language tag in the url :D 

> So which variant should we choose? 

Assuming that most people add inlang after launch/not day 1, hiding the source language tag seems to make more sense for the sake of not breaking existing URLs that don't include any language tag.

**Comment by Sansumaki** [comment]
there are many pages where you cant select language at all. its allways choosing depending on your browser language. and a few allow you to set the language in your profile. but of course there are also many with the url selection. but i think gooogle is using the browser/profile method

**Comment by ivanhofer** [comment]
> there are many pages where you cant select language at all. its allways choosing depending on your browser language. and a few allow you to set the language in your profile. but of course there are also many with the url selection. but i think gooogle is using the browser/profile method

But then you don't should choose to have the language information in the url at all. It isn't `google.com/de` for german. It is `google.com` for every language.

> i just double checked google.com. no language tag in the url :D

You are referencing a site which never has any locale information in it...

Google isn't even following their own recommandations ^^

![image](https://github.com/inlang/inlang/assets/21335119/1bcc0be0-10c4-437e-ac1c-bd79a2267579)

and the links look like: /search/docs/specialty/international/managing-multi-regional-sites **?hl=de**

I would not restrict to that variant, but If I'm the only person that sees the issue then go for it.

So how do we redirect users to the preferred language?

**Comment by ivanhofer** [comment]
and this is exactly my point why i want tho make it optional. to not break old links!!

Users will be auto-redirected, so this should not be a big concern. Also having a big list of redirects is very common for pages that went from a single language to multilanguage

**Comment by ivanhofer** [comment]
> TBD. My intention is to steer the SDK development into a "best practice" that works for 80% of use cases instead of working for 90% of use cases but with a hefty config and documentation.

It will be probabably more like it works in 30% of cases vs. 90% if we don't allow any configuration options. At that point I don't see the benefit of offering an SDK.

**Comment by ivanhofer** [comment]
just to mention it: dominikg will need the option to have the following url structure `de.company.ch` or else he won't be able to use the SDK of find some workarounds

**Comment by jannesblobel** [comment]
Unfortunately, Ivan has passed away, and we are trying to find a solution.
I will close this issue as not planned for now when we have a solution.
