### ISSUE TITLE
what should `i` return when a message does not exist?

### ISSUE THREAD

**Issue by ivanhofer** [inlang/monorepo#1284]
Request to change the behavior comes from @dominikg. Feel free to add comments if I mave missed something.

---

Currently `i('unknown key')` returns an *empty* string.
The reason behind that is that when rendering e.g. a website before messages are loaded you wouldn't see any placeholder values in the UI. If showing the keys as placeholder the UI looks more broken in my opinion.

When using the SDK this will never happen as it awaits all messages before rendering. But there could be an old key or a typo in a key (we need typesafety in the future 😉) and therefore it still can happen that a message is not found.

I think there are two possibilities to handle this:

### advantages
- UI looks cleaner

### disadvantages
- developers will NOT see that a message is missing (we can and should log this also to the console during development)

### advantages
- developers will see that a message is missing (we can and should log this also to the console during development)
- e.g. a button (or other component) that accepts either a key or a translated message can be implemented (functionality can also be integrated into the `i` function). But this could lead to unwanted behavior if a message resolves into a key, therefore integrating it into `i` is probably preferred.

### disadvantages
- end users will see that something is broken

## what is the better option?

We should decide on a default option.

We could also make this configurable (@samuelstroschein will love this idea 😜) or leave this to userland as they can patch the functionality by themselves if they really want to.

```ts
const iWithKeyFallback = (key,args) => {
	return i(key,args) || key
}
```
> assuming that no message can be empty.

or

```ts
const iWithoutKeyFallback = (key,args) => {
	const translation = i(key,args)
	return translation === key ? '' : translation
}
```
> assuming that the message will always be different than the key.

Leaving this to userland will probably lead to unwanted behavior.

**Comment by samuelstroschein** [comment]
Options that come to my mind:

1. Default fallback to the key should be okay with the assumption that missing messages will never hit production if lints are used in CI/CD. 
2. In the future, we can detect dev mode and render a big error message in the UI to inform developers that the UI is broken, similar to Flutter's UI errors. 

 
![CleanShot 2023-08-24 at 08 07 40@2x](https://github.com/inlang/inlang/assets/35429197/823c07ea-70ee-47e7-a82c-264cc8255d22)

**Comment by dominikg** [comment]
> The reason behind that is that when rendering e.g. a website before messages are loaded you wouldn't see any placeholder values in the UI

Shouldn't the ui defer until translations are loaded? showing empty first and text popping in later would be bad ux most of the time (and that layout shift....)

I'm fine with this being configurable or a slim userland recipe for it.

**Comment by dominikg** [comment]
The "what if a translation matches a key" problem reminded me of another possible feature, referencing keys in replacement params.

2 more ideas
1) You already have "InlangString", so if key arg is an InlangString you can just return that to prevent double translating.
2) actually double translating can be a buildtime feature
```json
{
  "company": {
    "name": "Inlang"
  },
  "copyright":"Copyright {year} {company.name}"
}
```
recursively parse and replace with existing translations and it compiles to

```json
{
  "company": {
    "name": "Inlang"
  },
  "copyright":"Copyright {year} Inlang"
}
```

**Comment by dominikg** [comment]
moved here from another comment:

You already have "InlangString", so if key arg is an InlangString you can just return that to prevent double translating.
```
(key,args) => {
  if(isInlangString(key)){
    return key; // no double translate!
  }
}
```

**Comment by ivanhofer** [comment]
Response to

> Default fallback to the key should be okay with the assumption that missing messages will never hit production if lints are used in CI/CD.

and 

> Shouldn't the ui defer until translations are loaded? showing empty first and text popping in later would be bad ux most of the time (and that layout shift....)

Quote from above: "When using the SDK this will never happen as it awaits all messages before rendering. But there could be an old key or a typo in a key (we need typesafety in the future 😉) and therefore it still can happen that a message is not found."

@samuelstroschein it will hit production. Even if we traverse all source files to see which keys are used, there still can be dynamic keys like `settings.${page}` which can result into a missing translation in production systems.

@dominikg It would also shift if you have a key that later renders a longer message. But nothing will shift the layout, because 
 the SDK waits until all messages are loaded.

> recursively parse and replace with existing translations and it compiles to

If implemented with the syntax above, this is very intransparent to users what a regular variable is and what resolves to another translated message. We are aware of this use case but it will be solved in a different way and does not need to be considered in this discussion.

> You already have "InlangString", so if key arg is an InlangString you can just return that to prevent double translating.

Yes, this can be integrated into the `i` function, what I meant with this point: e.g. a button (or other component) that accepts either a key or a translated message can be implemented (functionality can also be integrated into the i function). But this could lead to unwanted behavior if a message resolves into a key, therefore integrating it into i is probably preferred.

**Comment by ivanhofer** [comment]
So you think showing the ID is better than showing nothing in production?

**Comment by samuelstroschein** [comment]
> So you think showing the ID is better than showing nothing in production?

Yep. Likely every other i18n lib. Make it clear that a bug occurred. 

On the flipside, we should make sure that missing translations don;t hit production

**Comment by ivanhofer** [comment]
> On the flipside, we should make sure that missing translations don;t hit production

We probably won't ever be 100% sure.

If everyone thinks showing a broken state instead of an empty state is the way to go, then I will change it to render the ID.

**Comment by samuelstroschein** [comment]
Moved to https://github.com/inlang/monorepo/discussions/1464#discussioncomment-7302734
