### ISSUE TITLE
[bug] editor creates too many history entries

### ISSUE THREAD

**Issue by ivanhofer** [inlang/monorepo#1285]
### On what page did you encounter the bug?

https://inlang.com/editor

### Problem

When opening a repo in the editor I see multiple history entries, so I can't simply go back to the previously opened page.

![image](https://github.com/inlang/inlang/assets/21335119/6a2fbceb-7468-427b-8259-ca87cb63c41f)

### Expected behavior

It should just create a single history entry when opening a repository

### Reproduction

1. goto https://inlang.com/editor
2. open any project e.g. https://github.com/inlang/example
3. right click on browser-back 

### Browser Info

Microsoft Edge 115

**Comment by NilsJacobsen** [comment]
This should be tackled after the refactoring. This could be due to the persistent filter that are applied when loading. Each apply causes a new historical point.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink maybe related #1380

**Comment by NiklasBuchfink** [comment]
@felixhaeberle  No, this is again unrelated, but still a bug.

**Comment by felixhaeberle** [comment]
Great!! 🎉
