### ISSUE TITLE
get rid of inlang-sdk-js-plugin for configuring the sdk-js

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1287]
## Context 

We can (and absolutely should!) get rid of the sdk-js plugin for configuring the sdk-js due to the new config schema. 

- what the sdk-js-plugin and what the sdk-js do was always confusing. Why are two sdk-js needed?
- the version mismatching between the sdk-js and sdk-js-plugin leads to unresolved problems to that date

#### Why does both the sdk-js and the sdk-js-plugin exist? 

The inlang JavaScript config was not extendable with custom config settings. But now we can use any config settings.

## Proposal 

Get rid of the sdk-js-plugin as configuration requirement for the sdk-js to: 

- simplify the setup and increase the DX of the sdk-js
- ease maintenance by not having to deal with version mismatching 

#### Why can we get rid of the sdk-js now ? 

The new `config.settings` property allows arbitrary config settings. 

Using the sdk-js-plugin to add config for the sdk-js is not required anymore. Users can directly define sdk-js settings in the config: 

```diff

{
  sourceLanguageTag: "en",
  languageTags: ["en"],
  modules: [],
  settings: {
+    "inlang.app.sdkJs": {
+      "debug": true,
+      "languageNegotation: "..."
+      ...
+    }
  }
}

``` 

## Open questions

- [x] inlang/inlang#1288

**Comment by ivanhofer** [comment]
I already was confused the first time I had to manually configure a project. We need to define `inlang.plugin.sdkJs` settings in the `inlang.config.json` and those get then passed to `appSpecificApi.['inlang.app.sdkJs']`. With the refactor we can simply use `inlang.app.sdkJs` to define the settings for the app directly.

**Comment by samuelstroschein** [comment]
@ivanhofer should we make this change as part of the refactor? 

I am wondering if we should rename `@inlang/app` to `@inlang/sdk` because the docs will refer to `@inlang/app` as the SDK as part of "how to build your own inlang app"

**Comment by felixhaeberle** [comment]
@samuelstroschein What's the status in regards to paraglide with this issue?

**Comment by samuelstroschein** [comment]
Not releveant anymore.
