### ISSUE TITLE
opening repos with symlinks errors on opening in editor and fails to commit without losing the symlink

### ISSUE THREAD

**Issue by janfjohannes** [inlang/monorepo#1296]
### Problem

opening cal.com crashes with error 

```
FilesystemError: ENOENT: No such file or directory, symlink '/packages/prisma/.env/'
    at Proxy.symlink (memoryFs.ts:149:56)
    at execute (helpers.ts:19:23)
    at Object.apply (helpers.ts:23:19)
    at FileSystem.writelink (isomorphic-git.js?v=7f3e4a36:5155:17)
    at isomorphic-git.js?v=7f3e4a36:6334:24
    at async Promise.all (index 2897)
    at async isomorphic-git.js?v=7f3e4a36:6312:7
    at async isomorphic-git.js?v=7f3e4a36:2015:16
```

the file in question: 
<img width="579" alt="Screenshot 2023-08-28 at 11 58 27" src="https://github.com/inlang/inlang/assets/110794494/9c12f7ab-1086-4386-9be0-b8ceec68018a">

### Expected behavior

symlinks should be handled without issues

### Reproduction

open   /editor/github.com/NiklasBuchfink/cal.com

### `inlang.config.js` file

```JavaScript
// see https://inlang.com/
export async function defineConfig(env) {
  const { default: i18nextPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@2/dist/index.js"
  );

  const { default: standardLintRules } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js"
  );

  return {
    referenceLanguage: "en",
    plugins: [
      i18nextPlugin({
        pathPattern: "./apps/web/public/static/locales/{language}/common.json",
      }),
      standardLintRules({
        // deactivating identical pattern because of nested
        // resources like "de-DE" and "de-AT" where "de-AT"
        // contrains overwrites but the majority are identical patterns.
        identicalPattern: "off",
      }),
    ],
  };
}
```

### Other information

TODO:

- [ ] fix symlink handling
- [ ] add symlink handling test cases

**Comment by felixhaeberle** [comment]
@inlang/lix I guess @janfjohannes is the one who should be assinged here?

**Comment by samuelstroschein** [comment]
@janfjohannes opening large repos/better auth is a higher prio

**Comment by janfjohannes** [comment]
@samuelstroschein  as cal.com is the reference repo for "large repo support" this is a blocker for that task. Better auth can of course be done independently. Will revisit this after the auth improvements.

**Comment by janfjohannes** [comment]
@samuelstroschein  @martin-lysk   this is currently breaking cal.com repo for the new commit logic, which will silently delete all simlinks on commit, so treat this as blocking bug with prio

**Comment by samuelstroschein** [comment]
@janfjohannes so this blocks #1662?

**Comment by janfjohannes** [comment]
@samuelstroschein  i think so as  #1662 will not just crash but silently remove all symlinks such as this https://github.com/calcom/cal.com/blob/main/packages/prisma/.env on a commit. in theory we should be safe as we `could` check that we only whitelist repos without any symlinks but probably better to fix this first instead of merging on a friday. what do you think?

**Comment by samuelstroschein** [comment]
> check that we only whitelist repos without any symlinks but probably better to fix this first instead of merging on a friday. what do you think?

Yep, fix this. Corrupting repos should never happen
