### ISSUE TITLE
[bug] If I use static render with url strategy together then we got some error and broken redirect

### ISSUE THREAD

**Issue by nosovk** [inlang/monorepo#1303]
### Did you check if the config file includes errors?

- [X] Yes, I have validated the config file

### Problem

When we enable static rendering for root router, then we have an error when we open root page
Also we see an error in console:
![img](https://github.com/inlang/inlang/assets/1398808/8458ab89-1bde-4219-aaf4-0396114fec8b)

### Expected behavior

I expect that minimal stub will be rendered, then lang detection script executed and then good place to make redirect to correct language version.

### Reproduction

https://github.com/nosovk/inlang-static-root

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-1370P
    Memory: 34.04 GB / 63.67 GB
  Binaries:
    Node: 20.5.1 - ~\AppData\Local\fnm_multishells\28848_1693346041188\node.EXE
    npm: 9.8.0 - ~\AppData\Local\fnm_multishells\28848_1693346041188\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\fnm_multishells\28848_1693346041188\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @inlang/sdk-js: ^0.11.8 => 0.11.8
    @sveltejs/adapter-cloudflare: ^2.3.3 => 2.3.3
    @sveltejs/kit: ^1.24.0 => 1.24.0
    svelte: ^4.2.0 => 4.2.0
```

**Comment by samuelstroschein** [comment]
Hi @nosovk, 

The bug report will stay open for a longer time. 

Our colleague and friend @ivanhofer passed away last Saturday. He was responsible for the SDK-JS. We are going starting to search for someone to take over the SDK-JS development in the upcoming weeks.

**Comment by nosovk** [comment]
Sorry to hear that. I hope you will find a new contributor, and my sincere condolences. I wasn't met him personally, but highly appreciate his efforts to make svelte type friendly.

**Comment by felixhaeberle** [comment]
@samuelstroschein What's the status in regards to paraglide with this issue?

**Comment by samuelstroschein** [comment]
Paraglide is nearing preview-release state. Hence, this issue is not applicable anymore.
