### ISSUE TITLE
Quick Links are broken

### ISSUE THREAD

**Issue by delight** [inlang/monorepo#1312]
E.g.

https://github.com/inlang/inlang/blob/2b3247f4269122adcaa3cdf500b729e071d2d416/documentation/sdk/general.md?plain=1#L19

Generated link adress is:

https://inlang.com/dehttps://github.com/inlang/inlang/tree/main/source-code/starters/inlang-svelte

instead of 

https://github.com/inlang/inlang/tree/main/source-code/starters/inlang-svelte

**Comment by felixhaeberle** [comment]
@inlang/website currently fixing broken links. closing this issue.
