### ISSUE TITLE
[bug] inlang documentation site doesn't load if wasm is disabled

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1321]
### Problem

inlang.com/documentation crashes if the user browser has wasm disabled. 

### Reproduction

/

**Comment by samuelstroschein** [comment]
Should be fixed with #1302

**Comment by felixhaeberle** [comment]
Assigning @floriandwt because he will tackle this with #1302

**Comment by floriandwt** [comment]
Update: with the new markdown logic the error doesn't get shown anymore. 🥳 Will close this issue as soon as we merge, not done with the whole refactor though

**Comment by floriandwt** [comment]
Is getting fixed when markdown refactor is merged, tested it on Chrome without wasm. Otherwise, please re-open this issue.
