### ISSUE TITLE
refactor/fix `tryAutoGenProjectConfig`

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1323]
## Problems

- the auto-gen never works (https://github.com/inlang/monorepo/commit/983e6eb7ae86e429ef91454ced43ec47279b0321, https://github.com/inlang/monorepo/commit/5a0ba7f5da018255f9b4d1e16bcb7d99710738b1, [discord user reports](https://discord.com/channels/897438559458430986/1084866774874468433/1150051889791119411)) 
- why? no validation in place at all if the project config works 

### `tryAutoGenProjectConfig`

Refactor the auto-gen to validate if a config works. 

- [x] remove `baseConfig`. A base config can't exist if the goal is to auto-gen the config. (Misleading communication by myself in https://github.com/orgs/inlang/discussions/1299#discussioncomment-6846447)
- [ ] remove `warnings`. @janfjohannes you mixed tryAutoGenConfig with CLI stuff here. The auto-gen function is designed for 0 user interaction. 
- [x] add validation 

**Pseudocode**

```ts
// the function either works @returns ProjectConfig or doesn't @returns undefined
export async function tryAutoGenProjectConfig(args: { fs: NodeishFilesystem }): Promise<ProjectConfig | undefined> { 

  // 1. derive potential plugins for stack of user via package.json etc.

  // 2. derive translation file locations for `pathPattern` of plugins

  // 3. stitch together a config based on 1, 2 (assume `en` as source language tag)

  // !!!4. validate the config schema with typebox

  // !!!5. validate the project with `openProject` and check the `inlang.errors` 
}
```

### cli project init command

We should reverse the order of action from trying to auto gen first, and then falling back to manual project init to increase DX and avoid confusion (I was confused why i had to select which language tags i use, expecting that project init will figure that out for me). 

```
1. tryAutoGenProjectConfig()
2. if fails: fallback to manual prompting
```

**Comment by janfjohannes** [comment]
@samuelstroschein  i cannot open the discord link, in case that is critical please add a screenshot or where i find it...

**Comment by samuelstroschein** [comment]
Don't forget to rename the function to `tryAutoGenProjectConfig` :)
