### ISSUE TITLE
[bug] inlang.com/marketplace crashes on safari

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1340]
### Problem

<img width="719" alt="CleanShot 2023-09-13 at 19 10 39@2x" src="https://github.com/inlang/monorepo/assets/35429197/f0107648-26e4-4c84-b1c4-820690f13d2e">

### Reproduction

1. open https://inlang.com/marketplace in safari

**Comment by floriandwt** [comment]
@samuelstroschein I can't reproduce. For me works everything as expected. Have you turned off WASM in Safari maybe? Because then the bug has another origin.

**Comment by samuelstroschein** [comment]
@floriandwt doesn't seem like wasm is the fault. 

<img width="1152" alt="CleanShot 2023-09-14 at 09 44 09@2x" src="https://github.com/inlang/monorepo/assets/35429197/0ffdd40d-17b1-43fc-b447-92f461b06516">


Can you reproduce with Safari 16.1?

**Comment by floriandwt** [comment]
<img width="684" alt="Screenshot 2023-09-14 at 9 46 35 AM" src="https://github.com/inlang/monorepo/assets/92092993/98867533-3634-43f1-8e2c-2afaaa11d394">

Nope, sadly not.

**Comment by samuelstroschein** [comment]
@floriandwt still crashing

**Comment by floriandwt** [comment]
@samuelstroschein feel free to try again and tell me if the error message has changed. An invalid regular expression is most likely because we have replaced the id string in utilities with that.

**Comment by jannesblobel** [comment]
This issue is still existing under  Safari: Version 16.4
and is also reproducible on my phone

**Comment by samuelstroschein** [comment]
sentry logs https://inlang.sentry.io/issues/4190478701/?project=4504346044006400&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

**Comment by felixhaeberle** [comment]
not crashing for me on Safari web&mobile

![image](https://github.com/inlang/monorepo/assets/34959078/f998a02b-cc0c-4ee3-991d-d9820706bf76)

**Comment by floriandwt** [comment]
It's so hard working on a bug that seems to not happen for everyone. Someone has an idea how I can reproduce without having to buy a MacBook with older Safari installed?

**Comment by samuelstroschein** [comment]
Yeah... I just updated my Mac and iPhone. Can't replicate the issue anymore.

**Comment by jannesblobel** [comment]
This problem no longer occurs after an OS update.
