### ISSUE TITLE
deprecate `detectedLanguageTags()` in `Plugin`

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1376]
### Problem

@inlang/team Let's deprecate `detectedLanguageTags()` in `Plugin`.

Pro:
- reduce bugs aka an editor removes de but the plugin always re-adds de via the API
- an inlang project should work independently from "resource files"
- the refactor makes it trivial to add or remove language tags via a UI

Con:
- Potential future usage limitations which can't be forseen now
- ??

### Expected behavior

There are basically three ways language tags can potentially be added, of which only two apply:

- user adds language tags & resource files -> langauge is enabled in editor & message are getting displayed
- user adds language tags in settings -> language is enabled in editor & messages can be added
- user adds language resource file and doesn't add the corresponding language tag in settings  -> **not handled**

**Comment by NilsJacobsen** [comment]
I agree with deprecating it. It also helps us make writing plugins easier.

**Comment by jannesblobel** [comment]
Another pro is that the `"ignore": []` is unnecessary. But please do not remove this; some Repos are already using `ignore.`

**Comment by NiklasBuchfink** [comment]
@jannesblobel We can deprecate ignore, as we define the language tags now and don't derive them from the file structure anymore.

**Comment by felixhaeberle** [comment]
Deprecate `detectedLanguageTags()` PR https://github.com/inlang/monorepo/pull/1379

**Comment by NiklasBuchfink** [comment]
@jannesblobel Did you use `ignore` in your PRs? Otherwise, we can depreciate it now as well.

**Comment by jannesblobel** [comment]
@NiklasBuchfink, I wouldn't remove it. We don't know how many repos are already using `ignore`

**Comment by samuelstroschein** [comment]
Remove it if `ignore` was only used for `detectedLanguageTags()`. There is no need to have `ignore` if detectedLanguageTags doesn't exist anymore/

**Comment by NiklasBuchfink** [comment]
@jannesblobel It is useless and doesn't do anything, as all files are explicitly defined.

@felixhaeberle I propose:
- we remove it with #1379
- it will throw an error "`ignore` is now deprecated, please remove it from your `project.inlang.json` file."

**Comment by samuelstroschein** [comment]
> @NiklasBuchfink  it will throw an error "ignore is now deprecated, please remove it from your project.inlang.json file."

No no no no no. This would be a breaking change. Just remove it without throwing or anything

**Comment by NiklasBuchfink** [comment]
Alright 👍 
- Ignore remains included in the settings (no error is thrown)
- I remove the functionality and tests (as it does nothing)
- I remove ignore from the plugin documentation

**Comment by NiklasBuchfink** [comment]
Tested, merged & released with #1379  ✅
