### ISSUE TITLE
[bug] lint reports are not updated according to the filters 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1380]
### Problem

The filters do not affect the lint reports in the Editor 

![CleanShot 2023-09-19 at 18 35 09@2x](https://github.com/inlang/monorepo/assets/72493222/6a6f77e2-07c2-4627-84da-7048ff5083d9)

### Expected behavior

When I update the filter/add a filter, the Lint reports should only contain Lint errors in the filtered messages. 
<img width="1440" alt="CleanShot 2023-09-19 at 18 34 32@2x" src="https://github.com/inlang/monorepo/assets/72493222/a13e462b-7f68-483b-bd0d-240650100e17">

### Reproduction

1. Go to `https://inlang.com/editor/github.com/jannesblobel/Open-Assistant`
2. add a filter like` only German and English `
3. lint reports doesn't update

### Other information

https://www.loom.com/share/949f3ebf8b2645069fc60d55f0b2e740

**Comment by NiklasBuchfink** [comment]
@jannesblobel We know that this is expected behavior. Our filter logic combined with reactivity caused all filters to be checked after each keystroke for all variants of all messages. We got a lot of lags as a result.

I can take another look tomorrow to see if this can be solved differently.

**Comment by jannesblobel** [comment]
This is related. Or it needs another lint rule. For that. If you want, you can ignore it. 
https://www.loom.com/share/523e9953925148bb88578ad180325900

**Comment by jannesblobel** [comment]
solved with #1399
