### ISSUE TITLE
[bug] `Project config valid` and Editor erros do not match 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1381]
### Problem

I got an `Inlang config is valid!` in the CLI but an `FilesystemError:
ENOENT: No such file or directory, readdir '/lang/main-/'` in the Editor. 
<img width="786" alt="CleanShot 2023-09-19 at 19 21 52@2x" src="https://github.com/inlang/monorepo/assets/72493222/94429b00-2ae3-4b00-8055-842df0032c3e">
<img width="796" alt="CleanShot 2023-09-19 at 19 22 01@2x" src="https://github.com/inlang/monorepo/assets/72493222/615b3611-f284-4248-a87d-c96addd26b92">

### Expected behavior

The same error across the Ecosystem 

### Reproduction

1. open `https://github.com/jannesblobel/jitsi-meet` locally 
2. execute the cli command `npx @inlang/cli@latest  project validate  `
3. IF `Inlang config is valid!`  execute ` npx @inlang/cli@latest  open editor ` 
4. wait until the repo is cloned 
5. read the error

#### Config 
` {    "$schema": "https://inlang.com/schema/project-settings",
    "sourceLanguageTag": "en",
    "languageTags": ["af","ar","be","bg","ca","cs","da","de","dsb","el","eo","es","esUs","et","eu","fa","fi","fr","frCA","gl","he","hi","hr","hsb","hu","hy","is","it","ja","kab","ko","lt","iv","ml","mn","mr","nl","oc","pl","pt","ptBR","ro","ru","sc","sk","sl","sq","sr","sv","te","tr","uk","vi","zhCN","zhTW"],
    "modules": [
        "https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@4/dist/index.js",
        "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@1/dist/index.js",
        "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@1/dist/index.js",
        "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@1/dist/index.js",
        "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@1/dist/index.js"
    ],
    "plugin.inlang.i18next": {
        "pathPattern":{"main": "./lang/main-{languageTag}.json"},
        "ignore": [
            "languages.json",
            "translation-languages.json"
        ]
    }
} `
https://www.loom.com/share/16531a5a40974143bb31a9ee361015f3

**Comment by NiklasBuchfink** [comment]
@jannesblobel There is no en in the file. They have their English copy in main.json. We need to educate them about this.

**Comment by NiklasBuchfink** [comment]
@NilsJacobsen @samuelstroschein I'm going to extend the plugins for this with an optional `sourceLanguagePath`:
```json
"sourceLanguageTag": "en",
"sourceLanguagePath": "./lang/main.json"
```

- sourceLanguageTag defines the languageTag to make machine translate work
- sourceLanguagePath defines the location

Why are we doing this? Adoption of repo with a crappy structure.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink please only add this to the `plugin.inlang.i18next` for now. There does not seem to be a reason to add this to the json plugin.

**Comment by felixhaeberle** [comment]
@inlang/team Can we mark all the crappy additions we make in order to remove them when inlang paraglide & native inlang repos take off? Feels like very dump edge case to introduce `sourceLanguagePath` – and such additions should be monitored or at least marked with a `TODO`.

**Comment by samuelstroschein** [comment]
@felixhaeberle you can't remove `sourceLanguageFilePath` after introduction if projects rely on it -> unrelated to paraglide js. This flag is also only added to the i18next plugin. Unrelated to inlang/sdk.

**Comment by NiklasBuchfink** [comment]
@felixhaeberle I think no one wants to introduce something like this to `paraglide-js`:
- with our own tooling, we define best practices
- with our "adapter plugins" we support things like this **just** for adoption

@samuelstroschein only plugin-i18next, wording `sourceLanguageFilePath` 👍

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Go go go 👍

**Comment by NiklasBuchfink** [comment]
@jannesblobel I tested it and it works with these plugin settings after https://github.com/inlang/monorepo/pull/1379 is merged and released:

```json
"plugin.inlang.i18next": {
    "pathPattern": "./lang/main-{languageTag}.json",
    "sourceLanguageFilePath": "./lang/main.json"
}
```

![image](https://github.com/inlang/monorepo/assets/59048346/8c6fb66d-262b-4d7d-ae23-b5c81a1e78f4)

**Comment by NiklasBuchfink** [comment]
@jannesblobel release is out ✅
