### ISSUE TITLE
[bug] Fork modal is displayed while the project is not inlang ready.

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1382]
### Problem

@inlang/editor The fork modal is displayed while the project is not inlang ready. 

<img width="1468" alt="Bildschirmfoto 2023-09-20 um 09 40 20" src="https://github.com/inlang/monorepo/assets/34959078/30b22a91-5c78-45be-b0bb-5f4b7de064c9">

### Expected behavior

I would only display the fork modal when the project gets successfully loaded, because otherwise forking makes no sense. Also, the overlapping between the errors & the fork window is not good & is therefore fixed.

### Reproduction

1. Go to https://inlang.com/editor/github.com/calcom/cal.com
2. Do not have the repository forked yet.
3. See the error.

**Comment by NiklasBuchfink** [comment]
@felixhaeberle Some would say your screen is just too small. That's why they overlap :D

Good catch; I put it in the hide condition. Yet, creating a fork and fixing the bugs in the project settings would also be the right thing for the user to do.

**Comment by NiklasBuchfink** [comment]
Done ✅

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Great! <3
