### ISSUE TITLE
[refactor] move github auth and git userProfile from inlang editor to lix

### ISSUE THREAD

**Issue by janfjohannes** [inlang/monorepo#1383]

**Comment by janfjohannes** [comment]
@samuelstroschein  does it make sense to move profile requests ( eg something like getUserInfo()) also into lix here? that way  the editor would not have to do any direct github requests and could just use lix.

**Comment by samuelstroschein** [comment]
@janfjohannes probably yes! move everything auth related into the lix client.

**Comment by janfjohannes** [comment]
details for new structure here: https://github.com/orgs/inlang/discussions/1386
