### ISSUE TITLE
[bug] Editor bugged by Unicode error 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1404]
### Problem

The Editor will throw an error if a languageTag.json uses an invalid Unicode. 

### Expected behavior

The Editor could check if the.json using a valid unicode 

### Reproduction

1. Try to open this project in the Editor 
https://github.com/jannesblobel/unicode-bug-issues-1404

### Other information
`main-mr.json` looks like a normal Language but uses invalid Unicode. 
_No response_

**Comment by felixhaeberle** [comment]
@jannesblobel Can you improve your bug report?

- Can you tell me which error does it throw?
- In which project can I reproduce it?
- Where in the code does it break?

**Comment by felixhaeberle** [comment]
cc @jannesblobel

**Comment by jannesblobel** [comment]
I try to reproduce the bug in a extra repo and will post the link to this repo here

**Comment by jannesblobel** [comment]
> Can you tell me which error does it throw?

<img width="320" alt="CleanShot 2023-10-04 at 09 19 19@2x" src="https://github.com/inlang/monorepo/assets/72493222/7a5717ae-7aff-4dcf-bff1-1892a56881b7">

> In which project can I reproduce it?
https://github.com/jannesblobel/unicode-bug-issues-1404


If you try to open this project in the [Editor](https://inlang.com/editor/github.com/jannesblobel/unicode-bug-issues-1404) i get this error.  The `main-mr.json` is an invalid Unicode, which is the reason why it breaks. If you remove `mr` from the `language tag` in the project settings, it works fine. 

I hope that helps, a bit more

**Comment by felixhaeberle** [comment]
Great reproduction! I'll look into it.

**Comment by openscript** [comment]
Good read about unicode: https://tonsky.me/blog/unicode/

**Comment by felixhaeberle** [comment]
cc @NilsJacobsen 

I debugged this and saw that the `text` which should be a string in https://github.com/inlang/monorepo/blob/4d2e55e52eaf3ee265224aeb9e5722dbfc8febc2/inlang/source-code/plugins/i18next/src/plugin.ts#L234 is actually an `object` and therefore `text.split()` is failing. 

I guess `flatten()` is broken because it doesn't flatten the `object` to a `string` replacement.

The root cause is probably with `getFileToParse` or `detectJsonFormatting`, I'm not quite sure. Handing this over to @NilsJacobsen because we knows best where this parsing bug could happen. 

Probably not required mocking file as `string` here https://github.com/inlang/monorepo/blob/4d2e55e52eaf3ee265224aeb9e5722dbfc8febc2/inlang/source-code/plugins/i18next/src/plugin.ts#L146 .

**Comment by felixhaeberle** [comment]
cc @NilsJacobsen 

### More observations

`flatten()` is broken. The output can return an `object` when the string can't processed correctly wtf – and see also the empty strings? *see screenshot*

We can fix it with **filtering out empty objects** from `flattenedMessages`:

```ts
for (const [key, value] of Object.entries(flattenedMessages)) {
	if (typeof value !== "string") {
		delete flattenedMessages[key]
	}
}
```

@NilsJacobsen can you verify this change and implement it?

### Screenshot

<img width="500" alt="Bildschirmfoto 2023-10-04 um 18 13 36" src="https://github.com/inlang/monorepo/assets/34959078/772ed048-5026-4edb-bdf2-1eec49a49760">

**Comment by samuelstroschein** [comment]
If this is a unicode problem, the root cause might be the memory `nodeishFilesystem` from @inlang/lix. I would try to reproduce the error by using node's fs via the CLI for example. 

If `inlang project validate` runs in the reproduction from @jannesblobel, lix nodeisfh memory fs can be ruled out.

**Comment by janfjohannes** [comment]
i could rule out the filesystem.

the issue is this empty object as value here, i think its a broken format,  if i read correctly



    "toolbar": {
        "Settings": "सेटिंग्ज",
        "accessibilityLabel": {},   <<<<<<

**Comment by felixhaeberle** [comment]
@janfjohannes 👍

**Comment by felixhaeberle** [comment]
@NilsJacobsen Great, thanks 👏

**Comment by jannesblobel** [comment]
@felixhaeberle @NilsJacobsen  did you try it in the  [Editor](https://inlang.com/editor/github.com/jannesblobel/unicode-bug-issues-1404) ? Because the error still occurs

**Comment by felixhaeberle** [comment]
@NilsJacobsen Plugin Cache? 🙄🙄🙄
 
 cc @samuelstroschein @jannesblobel

**Comment by samuelstroschein** [comment]
probably... the 7 day caching is really problematic.

**Comment by samuelstroschein** [comment]
probably... the 7 day caching is really problematic. i filed a request https://github.com/jsdelivr/jsdelivr/issues/18532#issue-1930222232
