### ISSUE TITLE
replace node-fetch with native fetch

### ISSUE THREAD

**Issue by openscript** [inlang/monorepo#1425]
# Situation

Previously Visual Studio Code was on Node 16. Node 16 doesn't have a native implementation for fetch, hence we used `node-fetch` to polyfil this gap. With the August 2023 release Visual Studio Code [was upgraded to Electron 25 and with it to Node 18](https://code.visualstudio.com/updates/v1_82#_electron-25-update). Node 18 has got native `fetch` support.

# Enhancement

We should remove `node-fetch` and use the native `fetch` implementation. It's good to remove an external dependency to reduce technical dept. The minimum required Visual Studio Code version for the IDE extension would become `1.82`.

# Estimate

2h

**Comment by felixhaeberle** [comment]
Go for it 👍 

> Although I think 2h are a bit high of an estimate because we only use fetch 1 single time in the vs code extension. 😄

**Comment by openscript** [comment]
I agree. Probably only takes 15min :)

**Comment by felixhaeberle** [comment]
Buut, issue creation. Talking. Commenting. Totally understand it.

**Comment by openscript** [comment]
ETA: 10th of October

**Comment by openscript** [comment]
The story continues:

Fetch became experimental with Nodejs 18.0. `lib.dom.d.ts` and `@types/node` don't contain declarations for `fetch`. We have the following options:

1. Stay with `node-fetch` until we can upgrade to Nodejs 20. At least we have to wait for VSCode to upgrade. It will make very much sense to upgrade the whole monorepo.
2. Use `@types/node` with version 20. A version mismatch between `node` and `@types/node` is as bad as it sounds...
3. Maintain our own `fetch` type declaration.

1. offers the best rationale. 1. it is.
