### ISSUE TITLE
[bug] <Can't log in>

### ISSUE THREAD

**Issue by CrisA-Works** [inlang/monorepo#1440]
### Problem

I gave access to Inlang to my GitHUb account, but when I reach this link (https://inlang.com/services/auth/oauth-callback) I get a red square saying "An error occured during login. Please report the bug."

### Expected behavior

To be able to log in and start contributing to a repo

### Reproduction

#1: Click on Sign in to make changes
#2: Give access to my Github account
#3: Confirm
#4: Error

### Other information

#- Browser: Firefox 118.0.1 (64-bit)
#- OS: Windows 10
![imagen](https://github.com/inlang/monorepo/assets/78399996/500e77a4-cb67-48b3-a43e-2142d43d1096)

**Comment by samuelstroschein** [comment]
@janfjohannes is fixing he problem atm!

**Comment by jannesblobel** [comment]
@CrisA-Works,  the bug has already been fixed. Thank you for raising this bug :)
