### ISSUE TITLE
[improvement] validate that `sourceLanguageTag` is contained in `languageTags`

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1453]
## Problem 

The inlang ecosystem expects the `sourceLanguageTag` to be contained in `languageTags`. The expectation is not validated, though, because JSON schema can't be used to express the expectation. 

## Proposal 

Hardcode an error in the SDK to increase the ecosystem experience (EX).

```ts
// loadProject

if (project.languageTags.includes(project.sourceLanguageTag) === false){
   project.errors.push(new ProjectLanguageTagsDoesNotContainSourceError())
}
```

## Additional information 

I was about to hardcode this validation in paraglide-js. But, having the validation in the SDK and thereby increase the ecosystem experience (EX) is better.

**Comment by samuelstroschein** [comment]
@felixhaeberle can you do this?

**Comment by felixhaeberle** [comment]
@samuelstroschein yes!
