### ISSUE TITLE
[ux issue] unclear what's clickable and what not

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1455]
## Problem 

[From a user] Unclarity on what cards are clickable and which ones are not on the website.

Not clickable

<img width="319" alt="CleanShot 2023-10-13 at 18 34 28@2x" src="https://github.com/inlang/monorepo/assets/35429197/30d4e927-3de4-4d70-89e0-9c7aac807d42">

Not clickable 

<img width="306" alt="CleanShot 2023-10-13 at 18 34 54@2x" src="https://github.com/inlang/monorepo/assets/35429197/8e630e0d-7500-482e-bb06-d662c9fc9af9">

Clickable

<img width="288" alt="CleanShot 2023-10-13 at 18 35 10@2x" src="https://github.com/inlang/monorepo/assets/35429197/75977211-8245-41f3-974a-07f72c3d79e0">

**Comment by NilsJacobsen** [comment]
This will be not relevant with the new PR -> https://github.com/inlang/monorepo/pull/1471

**Comment by samuelstroschein** [comment]
@NilsJacobsen close then?
