### ISSUE TITLE
[bug] loadProject doesn't resolve modules

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1456]
## Problem 

The implementation is buggy. 

The regex is wrong...

<img width="902" alt="CleanShot 2023-10-13 at 19 09 03@2x" src="https://github.com/inlang/monorepo/assets/35429197/110d73ae-90eb-40f5-9458-6b849c88377b">

<img width="990" alt="CleanShot 2023-10-13 at 19 07 21@2x" src="https://github.com/inlang/monorepo/assets/35429197/791d4f0e-1351-403c-b7d7-97767bde3e77">

## Proposal 

@felixhaeberle I'll change the code to 

1. don't use basepath anymore. nodeishfs should resolve from the settings path. that makes nodeish fs unit testable. 
2. remove that regex (i knew the regex will be problematic the moment i saw it)

cc @martin-lysk this might have been your problem too

**Comment by samuelstroschein** [comment]
@felixhaeberle the error should not have been thrown in `createNodesifh...`. instead `loadProject` for transparency. nothing in SDK should throw to catch errors more effectively. validating input parameters is an exception

**Comment by samuelstroschein** [comment]
actually, i decided to throw at both points although the loadProject pre-ceeds. and, i also decided that we should give a proper error

**Comment by samuelstroschein** [comment]
fixed by [936cfa4](https://github.com/inlang/monorepo/commit/936cfa40138c31ff36686e19b83a9743569d0bf4)

**Comment by felixhaeberle** [comment]
Can you add a backslash example to the tests for Windows? Or is the path already normalized at this point? Because you proceed with .split("/") then and there, it's probably not correct.

Also "bathPath" is probably not what you want 🛁😄

**Comment by samuelstroschein** [comment]
> Sorry if there was a bug, I verified that all apps were working and adjusted all tests which were passing but you are correct the tests where not optimal.

The code only worked for the limited test you wrote and failed in production. 

> Can you add a backslash example to the tests for Windows? Or is the path already normalized at this point? Because you proceed with .split("/") then and there, it's probably not correct.

Good point. @inlang/lix should force UNIX paths and automatically transform windows paths.

**Comment by felixhaeberle** [comment]
@samuelstroschein Where in production did it fail? I tested the editor, cli, ide extension, badge – all manually, but never saw it failing.

**Comment by samuelstroschein** [comment]
@felixhaeberle paraglide-js

**Comment by samuelstroschein** [comment]
@felixhaeberle can you test the windows stuff? i am working on paraglide

**Comment by felixhaeberle** [comment]
yes 👍
