### ISSUE TITLE
improve app category conversion by prompting for tech stack

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1461]
## Problem 

The hero section for the app category is not hooking. Showing an announcement for paraglide is nice but I want to translate my app and don't know if paraglide can help me. 

<img width="1304" alt="CleanShot 2023-10-14 at 11 19 48@2x" src="https://github.com/inlang/monorepo/assets/35429197/b4e99c1c-3157-4b58-bc10-8c537fcd6235">

## Proposal

Use the hero section to prompt for the tech stack. 

Prompting can be as simple as `onClick () => fillOutSearch("react")` 

<img width="562" alt="CleanShot 2023-10-14 at 11 21 00@2x" src="https://github.com/inlang/monorepo/assets/35429197/274edbf0-0860-4ad9-b7c0-231a8a7f07e2">

**Comment by samuelstroschein** [comment]
@floriandwt thoughts?

**Comment by floriandwt** [comment]
@samuelstroschein I like it and I think it is more engaging to users than just a simple announcement. The announcements where a fast idea, so I think this is a big improvement. 👍

**Comment by NilsJacobsen** [comment]
The tech stack can be chosen on the "/" and "/application" so this went in https://github.com/inlang/monorepo/pull/1471

**Comment by floriandwt** [comment]
Closing this issue as it was implemented for the new layout in https://github.com/inlang/monorepo/pull/1471
