### ISSUE TITLE
(?) Ease the implementation of inlang.com by simply filling out the search query via UI elements.

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1470]
## Problem 

Building a great search/UI experience is hard. 

## Idea

Maybe we can leverage the search backend to simplify the implementation of a great search/UI experience.

- the UI only has to fill in the search query 
- the search engine reports back what has been matched to display a corresponding UI

### Example

1. A user clicks on the category "Application"
2. The user is forwarded to `inlang.com/m?search=application` which triggers the search backend
3. The search backend reports that the category `application` has been matched
4. The UI uses the search backend report to display "Application" as selected

Excalidraw with further information: https://app.excalidraw.com/s/1RmnkzJA3Ph/62OGfYM84w1

<img width="1282" alt="CleanShot 2023-10-16 at 11 51 50@2x" src="https://github.com/inlang/monorepo/assets/35429197/4c1060ed-c35d-4365-8ff1-385ec5b45fab">

The flow seems simple because the search backend does the heavy lifting of finding relevant results. The only requirement is, can the search backend report back what category, sub-category, etc. has been matched?

**Comment by samuelstroschein** [comment]
@floriandwt if this works, building the marketplace could become much simpler because the approach scales any category, sub-category and more properties.

**Comment by samuelstroschein** [comment]
@floriandwt because we don't know what future requirements are. having a small letter seems to ease future upgradability. 

`inlang.com/c/how-to-get-started-with-react`
`inlang.com/p/app.inlang.editor`

**Comment by floriandwt** [comment]
@samuelstroschein okay seems reasonable
