### ISSUE TITLE
add HTML header function export to paraglide-js

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1474]
## Problem 

Manual typing of HTML lang headers for SEO. 

<img width="788" alt="CleanShot 2023-10-11 at 15 23 39@2x" src="https://github.com/inlang/monorepo/assets/35429197/c7ad95d0-3edd-4d46-8fa1-8cf403e3bf2e">

## Proposal 

Paraglide should export a function `headers` for SSR, SEO

```tsx

<head>
  {htmlHeaders(languageTag)}
</head>
```

**Comment by felixhaeberle** [comment]
@samuelstroschein how does this work with the URL used in the link tags? 

I guess we need to provide a `baseUrl` option for SSR? Except of that, could a potential function look like this?

```ts
export const htmlHeaders = (args: {
	availableLanguageTags: LanguageTag[]
	languageTag: LanguageTag
	baseUrl?: string
}) => {
	const baseUrl = window.location.origin || args.baseUrl

	// create available lang headers
	const htmlHeaders = args.availableLanguageTags
		.filter((tag) => tag !== args.languageTag)
		.map((tag) => {
			return `<link rel="alternate" hreflang="${tag}" href="${baseUrl}/${tag}/" />`
		})
	// default lang header
	htmlHeaders.unshift(`<link rel="alternate" hreflang="x-default" href="${baseUrl}/" />`)

	// add comment to htmlHeaders
	htmlHeaders.unshift("<!-- START i18n -->")
	htmlHeaders.push("<!-- END i18n -->")

	return htmlHeaders.join("\n")
}
```

**Comment by felixhaeberle** [comment]
@samuelstroschein @LorisSigrist who should be responsible for this? @LorisSigrist ?

**Comment by LorisSigrist** [comment]
This really should be handled in the adapters, or it's not going to work in SSR. 

Doing it in paraglide-js directly also limits us in what we can do in the adapters. What if there is a framework for which the `/{lang}/some-page` pattern doesn't make sense? If the function is in paraglide-js we can't provide different behaviour there.

**Comment by samuelstroschein** [comment]
@LorisSigrist agree, let's put it in the adapters
