### ISSUE TITLE
[bug] TypeError: Cannot read properties of undefined (reading 'variableReferencePattern')

### ISSUE THREAD

**Issue by mattupham** [inlang/monorepo#1476]
### Problem

we've upgraded to `"@inlang/cli": "^1.8.0"` - when running `yarn machine-translate` we get this error `Cannot read properties of undefined (reading 'variableReferencePattern')` cc: @jonator

### Expected behavior

`yarn machine-translate` should run succesfully

### Reproduction

1. clone https://github.com/osmosis-labs/osmosis-frontend/tree/stage (stage branch)
2. run `yarn` in the root directory
3. run `yarn machine-translate`

### Other information

<img width="1049" alt="Screenshot 2023-10-16 at 1 43 38 PM" src="https://github.com/inlang/monorepo/assets/30577966/179140d1-0e24-4e8f-b927-e4bcf22abcdd">

`node -v v18.16.1`
`yarn -v 1.22.19`

**Comment by MaxMillington** [comment]
@mattupham I believe this is fixed if you upgrade the cli to v 1.10

**Comment by samuelstroschein** [comment]
@inlang/cli @felixhaeberle can you look into this ASAP?

**Comment by felixhaeberle** [comment]
@mattupham 

1. Can you ensure you are running on the latest version of the inlang CLI? run `npx @inlang/cli@latest machine translate`
2. Can you share your `project.inlang.json`
3. Can you share how your language files (json?) are set up or/and provide an example?

**Comment by felixhaeberle** [comment]
@mattupham Can't reproducde it. Could it be that your CI/CD does run on a cached version of the inlang CLI?

<img width="686" alt="Bildschirmfoto 2023-10-17 um 09 50 29" src="https://github.com/inlang/monorepo/assets/34959078/bc1d4b21-fc0d-496c-a2df-29ad1e1ecf7d">

**Comment by felixhaeberle** [comment]
cc @inlang/plugins Do you know where the error `PluginLoadMessageError: Cannot read properties of undefined (reading 'variableReferencePattern')` is thrown? Seems that this is not an issue with the CLI?

**Comment by samuelstroschein** [comment]
@mattupham I can't reproduce your issue either. 

<img width="779" alt="CleanShot 2023-10-17 at 18 21 30@2x" src="https://github.com/inlang/monorepo/assets/35429197/4991c5cb-7adf-48ed-86df-7e69eafa7257">

**Comment by felixhaeberle** [comment]
closing because stale
