### ISSUE TITLE
compiled output gets distributed

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1481]
## Problem 

<img width="818" alt="CleanShot 2023-10-17 at 16 06 31@2x" src="https://github.com/inlang/monorepo/assets/35429197/9899af0c-9ac5-4fd6-be53-9be59453c94f">

## Proposal 

- [ ] move compiled-output outside of dist to avoid this problem. 
- [ ] update the package.exports

**Comment by felixhaeberle** [comment]
@samuelstroschein already done? you once told me this is now the case.

**Comment by samuelstroschein** [comment]
@felixhaeberle no, not yet

**Comment by samuelstroschein** [comment]
redundant due to #1607
