### ISSUE TITLE
Improve Marketplace Header

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1488]
![image](https://github.com/inlang/monorepo/assets/58360188/b93cd606-0a2a-40c1-a55e-fe19ee93820d)

The Marketplaceheader is the first iterable shot. There are things to improve.

- [x] Add social links again
- [x] Fix: Subcategories are breaking layout on mobile
- [x] Add blog again
- [x] See if we add LanguagePicker again (after dogfooding)

@inlang/website

**Comment by NilsJacobsen** [comment]
I would keep them. If we need to discuss a topic with the team, we are not spamming on one issue. Also I think we need to prioritize them or even decide against them separately. But jap let's make round packages. Think of them as small initiatives.

**Comment by NiklasBuchfink** [comment]
I almost submitted the same issue. If we want to make this async, why don't we make a short tasklist somewhere before, prioritize it and break it down in GH issues afterward? The list could have been collected in our Discord channel /website

**Comment by floriandwt** [comment]
No, I meant it like here (stated as sub-tasks):
<img width="949" alt="Screenshot 2023-10-19 at 2 07 57 PM" src="https://github.com/inlang/monorepo/assets/92092993/38da7a77-c7ac-4dad-ae4b-fa69f0b93f74">

Every issue has its own page where we can discuss. But we also have an overview over whats missing and whats done

**Comment by NilsJacobsen** [comment]
Ahh as long the grouping makes sence. Chances are high that we are not closing it for a long time :D

**Comment by floriandwt** [comment]
@NilsJacobsen better than having no overview at all and separated sub-tasks all over the place in my opinion

**Comment by NiklasBuchfink** [comment]
"Someone" will comment: "Is this done?" or "This issue is stale." Or we just close it as soon as we take over other tasks.

**Comment by NilsJacobsen** [comment]
Quick fix added social links to help people navigate -> https://github.com/inlang/monorepo/commit/ffac0e57ff61734eccd07df8774035dd69e4cabb

The rest of the issue will probably be done after dogfooding

**Comment by felixhaeberle** [comment]
@NilsJacobsen dogfooding over? what's the status?

**Comment by NilsJacobsen** [comment]
Nope this is not finsihed

**Comment by NiklasBuchfink** [comment]
Doing Felix's job. @NilsJacobsen What's the status?

**Comment by NilsJacobsen** [comment]
Let's close this as we are iteratively changing it
