### ISSUE TITLE
Dogfood inlang

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1489]
## Proposal

Use paraglide.js to add i18n to the page.

- [x] Remove old i18n lib from inlang.com
- [x] See how many translations still apply (none)
- [x] Change remaining storage layer to message format @felixhaeberle can we use your script (nothing to change)
- [x] Add paraglide
- [x] Add old language picker
- [x] Work on languageTag injection
- [x] Test

Through the sync approach that paraglide is based on, we should fix the SEO topic with it. (Important for growth)

@inlang/paraglide-js @inlang/website

**Comment by felixhaeberle** [comment]
@NilsJacobsen script: https://gist.github.com/felixhaeberle/40e0fe6ea73154f7210ef4280f33b07a

**Comment by samuelstroschein** [comment]
@NilsJacobsen here is the working version 

i18n routing -> https://github.com/inlang/monorepo/blob/add-paraglide-to-website/inlang/source-code/website/src/renderer/_default.page.route.ts

paraglide adapter -> https://github.com/inlang/monorepo/blob/6eeccaf5c1e8d55576bd75e70aed841170beb347/inlang/source-code/website/src/renderer/_default.root.tsx#L32-L66

You might need to intercept routing like clicking on <a> and calling `navigate` to inject the current language tag. @brillout is <a> and `navigate` interception possible with Vike?

**Comment by NilsJacobsen** [comment]
This is blocked by https://github.com/inlang/monorepo/issues/1513

**Comment by NilsJacobsen** [comment]
1. How do we want to deal with broken translations for other languages than de and en?
<img width="1512" alt="image" src="https://github.com/inlang/monorepo/assets/58360188/20246633-5d61-455d-8c78-5f0937ebdf1e">

Proposal: Initially, do a machine translate?

2. Does someone wants to review the wording on the page?

3. Most of the content comes from registry. So not translated with paraglide. Are we waiting for the markdown editor?

@inlang/team

**Comment by NiklasBuchfink** [comment]
> Proposal: Initially, do a machine translate?

@samuelstroschein suggested not committing machine translations and instead using the CLI command in a deployment step.

We still can reach out to our language contributors.

**Comment by samuelstroschein** [comment]
@NilsJacobsen hi from the airport 👋

I recommend to add the inlang machine translate command to the render deploy command. 

- Ensures that no missing translations exist in production 
- ensures that contributors see "missing translations" that should be machine translated.

**Comment by NilsJacobsen** [comment]
Have a nice flight ✈️

Okey so at first I'm gonna add the lints so any dev will get an error with `npm run ci`.
-> As soon as the #1482 is fixed we can add that too.

**Comment by samuelstroschein** [comment]
Ha ... we only want the lints for DE as other translations are community translated. 

Another feature that we want/need?

**Comment by NilsJacobsen** [comment]
cli lint doesn't have monorepo support -> https://github.com/inlang/monorepo/issues/1527

**Comment by NilsJacobsen** [comment]
We could add a lint option for only checking specific languages.

**Comment by felixhaeberle** [comment]
@NilsJacobsen can be closed? follow-up issues are existing.

**Comment by NilsJacobsen** [comment]
I don't want to forget about integrating lint for our monorepo so I would wait for the lint options. @felixhaeberle

**Comment by floiem** [comment]
@NilsJacobsen I hope this is the right discussion for this small question/proposal: Should we make the community translations not clickable as long as the translations can't be shown yet?

**Comment by NilsJacobsen** [comment]
But then nobody will translate those. We initially add the machine translations and if there are missing ones people will contribute.

**Comment by felixhaeberle** [comment]
> cli lint doesn't have monorepo support -> #1527 
> We could add a lint option for only checking specific languages. -> #1528

@NilsJacobsen Both done ✅ Can you continue?

**Comment by NilsJacobsen** [comment]
Great I'll take over after lunch :)

**Comment by samuelstroschein** [comment]
Prompt users to contribute

![CleanShot 2023-10-31 at 10 58 33@2x](https://github.com/inlang/monorepo/assets/35429197/ebbab6aa-68f2-49b8-bf20-05a9928d6a64)

**Comment by NilsJacobsen** [comment]
@floiem can you add something like that?

**Comment by floiem** [comment]
@NilsJacobsen sure

**Comment by NilsJacobsen** [comment]
Going to close this as this is an ongoing process now. We get lint errors if german is not submitted in a PR.
