### ISSUE TITLE
Extend registry with guides/articles

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1490]
## Problem 

We already talked about adding guides and articles in the market place so there are some questions in my head?

### 1. Do we want to keep the blog page?
- If the blogs are part of the marketplace and the ecosystem we should just through them into the registry. 

**Pro:** People are searching for stuff or using filters and also get guides and articles 👍
**Cons:** No way of quickly seeing all blogs

### 2. How do we store them?

Proposal: Add a folder in the monorepo with itemfolders existing of markdown, assets and manifest file.

```js
guide.inlang.paraglideXSvelte
- content.md
- marketplace-manifest.json
- assets
- - icon.svg
```

### 3. How do we name them?
- Do we only want guides? Because that could clash with articleish contents.

**Proposal1:**
For now add article for old blogs and guides for tutorialish contents

**Proposal2:**
Don't add old blogs and add guides for tutorialish contents

@inlang/website

**Comment by floriandwt** [comment]
@felixhaeberle guides are now possible, write me a DM if you want to see how. Docs have to get extended for guides, if we want others to also write guides.

**Comment by jannesblobel** [comment]
@floriandwt  Before you do the work twice. Just quickly write the docs and link them here.

**Comment by floriandwt** [comment]
@jannesblobel work for what twice?
