### ISSUE TITLE
[quality improvement] Unbundle the editor

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1494]
## Problem 

As we grow, we want to unbundle the editor from the website. 
- Editor client-side
- Website SSR -> SEO, etc. ...

With the new marketplace, we already unbundled shared components like header... so 50% done.

Question: 
- Are we just going to make a new module for the editor? 
- Can it stay on the /editor route? Or do we need to use something like subdomains?

In the end, it helps with SEO. So growth topic.

@inlang/editor @inlang/website

**Comment by NiklasBuchfink** [comment]
This closed with: https://github.com/inlang/monorepo/pull/1551
