### ISSUE TITLE
title text overflow in card on marketplace

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1505]
### Problem

<img width="324" alt="Bildschirmfoto 2023-10-20 um 17 03 30" src="https://github.com/inlang/monorepo/assets/34959078/bbb3fc92-76ed-41da-a835-79ee2dba07be">

### Solution

No overflow under the button or something similar.

**Comment by NilsJacobsen** [comment]
Thank felix 👍

**Comment by NiklasBuchfink** [comment]
I fixed it ✅
