### ISSUE TITLE
`paraglide-js compile` remove default path

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1508]
## Problem 

@NilsJacobsen was unaware that the project location can be specified with --project. 

<img width="678" alt="CleanShot 2023-10-23 at 12 05 47@2x" src="https://github.com/inlang/monorepo/assets/35429197/5c41cef4-195e-4767-aba7-96100a8ae243">

**Comment by samuelstroschein** [comment]
@NilsJacobsen good idea, can you do this? If yes and yes, please implement this

**Comment by NilsJacobsen** [comment]
Sound good, would have saved me a lot of time checking the docs back and forth :D
I can do that.

**Comment by samuelstroschein** [comment]
I propose to remove the default path altogether. With the upcoming [inlang directory](https://www.loom.com/share/a77df1ce6f4a4fd3a4b97ecacef9bce8?sid=5ac4ada2-cf23-4652-a397-0f5f9361d2d2), choosing a default project won't be possible anymore. 

@LorisSigrist please remove the default path from the compile command
