### ISSUE TITLE
Add parrot to marketplace

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1509]
## Is it time to add parrot to the marketplace?

Discussed that with @martin-lysk.

### Proposal: Add parrot to the marketplace now.

Pro: 
- Parrot helps to go global, so why not putting it in the marketplace
- It's not hurting

Cons: 
- People are not confused about what parrot has to do with inlang. 
- They would probably expect dev tooling from parrot.

Please vote 👍👎
@inlang/team

**Comment by felixhaeberle** [comment]
add parrot NOW. 

> also think about the submission of marketplace items because if we want people submit items there, we have to lower the barrier like extremely.

**Comment by samuelstroschein** [comment]
But, can @martin-lysk "maintain" the manifest? 

It's a good test for everyone how easy martin finds creating and maintaining the manifest file.

**Comment by floriandwt** [comment]
@samuelstroschein agree, after merging the new PR some things inside the registry.json itself are changed but that has nothing to do with the manifest itself.

**Comment by martin-lysk** [comment]
@samuelstroschein sure will take care of this asap. I will take notes on problems i may face.

**Comment by martin-lysk** [comment]
@NilsJacobsen I recorded a loom on my steps to create an app entry and noted the things that where not ideal on the path.
I prepared a manifest here https://github.com/parrot-global/parrot/blob/main/marketplace-manifest.json not sure who would be good to check it out and help me getting it published

**Comment by felixhaeberle** [comment]
cc @flornkm @samuelstroschein would a short loom on how to release to the marketplace help – also with a graphic which field is rendered where on the page? This should potentially solve all the issues. 

This is a good example but a bit long & not well formatted. But in general, this is a good start: https://developers.raycast.com/basics/prepare-an-extension-for-store

**Comment by flornkm** [comment]
@felixhaeberle I think it would be much better & simpler to just let users create their `manifest` visually on the page. It's very easy to then let them download / copy the json string from a basic form + we then have the ability to prefetch the contents and tell if the links they are putting there are valid or not.

**Comment by samuelstroschein** [comment]
@felixhaeberle I like flos' proposal of a UI form to create the manifest better. Seems easier to maintain than a loom video and is lower friction to try out. 

I have a big idea though for the manifest. Let's pause manifest discussions for a week please.

**Comment by felixhaeberle** [comment]
@samuelstroschein Dev's want to have things in a file tho. Using a form on a website is uff. I don't like filling forms.

**Comment by samuelstroschein** [comment]
@felixhaeberle devs also hate watching your loom ;)

**Comment by felixhaeberle** [comment]
@flornkm @martin-lysk @samuelstroschein whats the status? would really like to see 🦜 on inlang.com

**Comment by martin-lysk** [comment]
The marketplace-manifest is ready (see: https://github.com/parrot-global/parrot/blob/main/marketplace-manifest.json) - if someone can support me adding parrot to the registry we are good to go!

**Comment by flornkm** [comment]
@martin-lysk This is the `jsdelivr` url for it: https://cdn.jsdelivr.net/gh/parrot-global/parrot@latest/marketplace-manifest.json 
You can add just add it here with a random key as a `"m"` app: https://github.com/inlang/monorepo/blob/main/inlang/source-code/marketplace-registry/registry.json

If something's unclear just ping me

**Comment by felixhaeberle** [comment]
I will take over.

**Comment by flornkm** [comment]
@felixhaeberle what is the current state? Do you need help? Otherwise, I can put it into the registry. I thought this would be some kind of user testing to let Martin do it on his own.

**Comment by flornkm** [comment]
Getting errors implementing Parrot, likely because of the License and other stuff. I have to change the versioned interface first cc @felixhaeberle

**Comment by samuelstroschein** [comment]
@flornkm maybe make licesne just a string field. everyone can enter the license that they want.

**Comment by flornkm** [comment]
Closing this as 🦜 is now officially added to inlang.com! 🎉

We have to look in the next few days if people are confused about why a "plugin" is listed in "apps" category.
