### ISSUE TITLE
add `--project` flag to options for paraglide cli

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1510]
### Problem

we currently miss the `--project` flag in the paraglide js cli help section.
it's not kinda obvious to run `paraglide-js compile --help`

therefore, this error happened https://discord.com/channels/897438559458430986/1096046572913041429/1165935337017720922

![image-apfcwpendv](https://github.com/inlang/monorepo/assets/34959078/20837ce6-27a3-4b26-9a9c-132aac6848d2)

### Solution

add the flag to the options / higher the flag to be global and not command specific.

**Comment by felixhaeberle** [comment]
duplicate of #1508

**Comment by samuelstroschein** [comment]
You have to run `paraglide-js compile --help`
