### ISSUE TITLE
ide extension doesn't provide inline hints if a function is called after referencing the message

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1517]
### Problem

From https://discord.com/channels/897438559458430986/1163504297577812179/1166807579435999252

<img width="705" alt="CleanShot 2023-10-25 at 23 59 55@2x" src="https://github.com/inlang/monorepo/assets/35429197/4807d6c7-64d6-43e2-a533-aa5da04ad3e6">

### Expected behavior

The message hint should be shown inline. I am unsure how to render it though without .method() to be annoying.

### Reproduction

/

**Comment by felixhaeberle** [comment]
fixed with #1523

rendering`m.message() [inline message] .method()` because we can't know what `.method()` is doing and therefore displaying it at the end of the line would probably be misleading.
