### ISSUE TITLE
paraglide vite plugin 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1518]
- [ ] sets ssr no external for paraglide-js https://github.com/inlang/monorepo/issues/1485#issuecomment-1779918933
- [ ] includes the compile step (removes the need to include the compile step in package.json)
- [ ] if messages change, the compile step is re-executed [blocked by #1519]
- [ ] exclude paraglide in `optimizeDeps`, see https://github.com/inlang/monorepo/pull/1533, to get HMR working

**Pseudocode**

```ts
import { paraglideJsVitePlugin } from "@inlang/paraglide-js"

export default defineConfig({
	plugins: [
            paraglideJsVitePlugin({
              name: "frontend",
              project: "./project.inlang.json"
            })
	]
})


```

**Comment by samuelstroschein** [comment]
@felixhaeberle can you take over this issue?

**Comment by felixhaeberle** [comment]
@samuelstroschein sure, how urgent is it?

**Comment by samuelstroschein** [comment]
@felixhaeberle fixing the ide extension plugin and #1535 should preceed this task

**Comment by felixhaeberle** [comment]
this is currently blocked by https://github.com/inlang/monorepo/issues/1519

**Comment by felixhaeberle** [comment]
cc @samuelstroschein I got the paraglide vite plugin running 🎉

but have 1 issue left with the ts server not recognizing the change.

https://www.loom.com/share/b78134a3356740aebd3596759299def0

**Comment by felixhaeberle** [comment]
progress in here https://github.com/inlang/monorepo/pull/1571

**Comment by janfjohannes** [comment]
@felixhaeberle  https://github.com/inlang/monorepo/pull/1572

**Comment by felixhaeberle** [comment]
@NilsJacobsen see #1571, unfortunately the watcher which should trigger subscribe is not executing

**Comment by KraXen72** [comment]
nice! please make sure that the HMR properly recompiles whenever a new message string is added :)

**Comment by felixhaeberle** [comment]
@KraXen72 this is exactly the purpose of the bundler plugin 👍
