### ISSUE TITLE
inlang.com does not re-direct to product page

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1520]
## Problem 
Opening a product page with the id only like `inlang.com/m/zu942ln6` does not open the product/redirect to `inlang.com/m/zu942ln6/app-inlang-badge`

Watch the screen recording here: https://jam.dev/c/99da00f0-d350-4e63-b3bd-77f19312fc52

\-------------------------------------

**Website URL:**
[https://inlang.com/m/zu942ln6](https://inlang.com/m/zu942ln6)

**Device and browser info:**
Chrome 118.0.5993.70 (1440x758) | Mac OS (arm) 10.15.7

**Date and time:**
October 26th 2023 | 8:09am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/99da00f0-d350-4e63-b3bd-77f19312fc52](https://jam.dev/c/99da00f0-d350-4e63-b3bd-77f19312fc52)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by floiem** [comment]
Should be fixed with https://github.com/inlang/monorepo/commit/ca5bb28046c76617c44b9232b8134a4130d030d4
