### ISSUE TITLE
No monorepo support for cli lint

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1527]
## Problem 

I can not use the --config anymore. The `package.json` and the `project.inlang.config` need to be on the same dir right now.

## Proposal
Add a --project option as we have it in the compile command of paraglide-js.

@inlang/cli

**Comment by felixhaeberle** [comment]
oof we had this built before. we should be generally more patient removing things "just because".

I can do this 👍 should be a general flag tho. All commands should be runnable with a different project root.
