### ISSUE TITLE
cli: lint command should allow to lint only specific languages

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1528]
## Problem 
When users only want to garantee for example en and de languages. They do not want to get lint errors for other languages.

## Proposal
Add an `--option`
Example: `npx @inlang/cli --scope en de`

@inlang/cli

**Comment by samuelstroschein** [comment]
I vote for --languageTags as option, not scope. Make it explicit. We might introduce more filters in the future. 

PS this dogfooding is great. It gives us a good set of requirements.

**Comment by NilsJacobsen** [comment]
BTW new requirement -> We hardcode strings and forget about it. How can we fix that?:D

**Comment by NilsJacobsen** [comment]
In the dev process, we use hard-coded strings sometimes to iterate faster. It would be great if a cli command browses through all .tsx files and searches for hard-coded strings and lints them. 👍

**Comment by samuelstroschein** [comment]
I see. We need an ESLint rule for that, or the ide extension is extended to detect hardcoded messages. I'd say future optimization

**Comment by NilsJacobsen** [comment]
Fine I just faced the problem that's why I was bringing it up.

**Comment by felixhaeberle** [comment]
@inlang/team should this be a general flag of the CLI, e.g. machine translate / other commands also running only with specified language tags?

**Comment by samuelstroschein** [comment]
@felixhaeberle I bet you're asking because you wonder if this should be a global flag. I vote for "do it on a per-command basis". The need to machine translate only certain languages hasn't arisen yet, and I doubt that it will ever do.
