### ISSUE TITLE
filesystem watch feature

### ISSUE THREAD

**Issue by janfjohannes** [inlang/monorepo#1534]

**Comment by janfjohannes** [comment]
@samuelstroschein

**Comment by samuelstroschein** [comment]
Thanks @janfjohannes. 

We need the `fs.watch` API in lix nodeish fs. 

- ASAP priority to unblock paraglide-js and #1519 
- only the API and in-memory implementation is needed, no cross env watching like web editor watches for changes on local filesystem

Let me know if I need to elaborate further. Once nodeish fs supports `fs.watch`, @NilsJacobsen can go ahead and implement #1519
