### ISSUE TITLE
Improve plugin functionality communication: One plugin, one job

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1535]
## Problem 
It is not easy to understand what plugins do. Because they have multiple purposes, it is hard to read it from the name. 

## Proposal
**One plugin, one job.**

- [ ] Extract the matcher from the i18next and json plugin. 
- [ ] Add a `t-function-matcher-plugin`, that helps reading the `t-functions` for the ide-extension
- [ ] Rename the paraglide plugin to `m-function-matcher-plugin`

The names are now more descriptive and help reading the project.inlang.json files.

Did I miss something?
@inlang/paraglide-js @inlang/plugins @inlang/ide-extension

**Comment by samuelstroschein** [comment]
Nothing is missing. @NilsJacobsen will you implement this soon? If so, please assign yourself

**Comment by felixhaeberle** [comment]
@NilsJacobsen @samuelstroschein This eases the pain of not understanding what a plugin does & eliminates monster plugins. Big like 🤩

**Comment by NilsJacobsen** [comment]
I just started looking into `json` and `i18next` plugin and saw that we are passing the plugin settings into the matcher to react differently to namespace paths or single paths.

```ts
export const plugin: Plugin<{
	[id]: PluginSettings
}> = {
	id,
	displayName,
	description,
	settingsSchema: PluginSettings,

	loadMessages: async ({ settings, nodeishFs }) => {
		settings["plugin.inlang.i18next"].variableReferencePattern = settings["plugin.inlang.i18next"]
			.variableReferencePattern || ["{{", "}}"]
		return loadMessages({
			settings,
			pluginSettings: settings["plugin.inlang.i18next"],
			nodeishFs,
		})
	},
	saveMessages: async ({ messages, settings, nodeishFs }) => {
		settings["plugin.inlang.i18next"].variableReferencePattern = settings["plugin.inlang.i18next"]
			.variableReferencePattern || ["{{", "}}"]
		return saveMessages({
			pluginSettings: settings["plugin.inlang.i18next"],
			nodeishFs,
			messages,
		})
	},
	addCustomApi: ({ settings }) => ideExtensionConfig(settings["plugin.inlang.i18next"]),
}
```
We cant do that anymore after unbundling matcher plugins right?

**Comment by samuelstroschein** [comment]
No, we can't. In that case, unbundle the message reference matcher for the plugin json only? 

Kinda also makes sense that the i18next plugin handles everything for me because I use a very specific stack. For the JSON plugin, it's too generic though. 

Agree on unbundling from JSON plugin but leave in i18next plugin?

**Comment by NilsJacobsen** [comment]
`json` and `i18next` are almost the same. Both use namespaces. So if we keep it for i18next we should keep it for json too. @samuelstroschein

**Comment by samuelstroschein** [comment]
> that we are passing the plugin settings into the matcher to react differently to namespace paths or single paths.

Wait, why is this an issue? You can write settings for the t-function-matcher too `hasNamespace`: true

**Comment by NilsJacobsen** [comment]
Wait, the json matcher plugin is not using the settings. So that should be easy.

**Comment by felixhaeberle** [comment]
can you also inform our user in Discord about this change 
+ check the setting files in the monorepo to link to the new packages?

**Comment by NilsJacobsen** [comment]
Done ✅
