### ISSUE TITLE
solution for missing sitemap

### ISSUE THREAD

**Issue by kiemflo** [inlang/monorepo#1550]
## Problem 
A lot of our pages are not listed on google and the search console bot can't detect them without a sitemap see here:
<img width="952" alt="Screenshot 2023-10-31 at 3 36 33 PM" src="https://github.com/inlang/monorepo/assets/92092993/38d0eaa9-7c1f-421b-8943-35d2ecdb7f32">

## Proposal
- search for a solution to dynamically generate a sitemap with every build step so we get more visitors via SEO

cc @inlang/website

**Comment by floiem** [comment]
Possible solution: https://github.com/jbaubree/vite-plugin-pages-sitemap

**Comment by NiklasBuchfink** [comment]
@floiem this will be a problem:

> You must use [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages/) routes generation to use this plugin. If you are not working with vite-plugin-pages, i recommend to use [vite-plugin-sitemap](https://github.com/jbaubree/vite-plugin-sitemap).

But to leverage the vite ecosystem for that seems to be the right choice. What about this library:
https://github.com/jbaubree/vite-plugin-sitemap

**Comment by floiem** [comment]
@NiklasBuchfink I've looked at all, but it seems to make more sense to just write an own script we can adjust freely without any additional dependencies: https://github.com/inlang/monorepo/pull/1563

I got this idea from looking into the solidjs website repo. They also have their own script for making the sitemap.

**Comment by NiklasBuchfink** [comment]
Top job 👍  Maybe you can adjust it to keep track of "inlang/editor" after the merge as well.
