### ISSUE TITLE
implement SEO for different languages

### ISSUE THREAD

**Issue by flornkm** [inlang/monorepo#1553]
## Problem 
We're getting started again with SEO, however, just in English. As we have dogfooded inlang now with german too, it makes sense to dynamically adjust the meta tags for the german language to get shown in german search results.

## Proposal
Change the meta tags on all pages (including the dynamic ones!) to be shown in german too.

### Pros
- We can see what impact it has (telemetry: german audience)
- More likely that german devs are finding us via google
- Maybe we can even use our "case study" later on for advertising paraglide

### Cons
- we can't directly check if we got listed in german google results
- none of our marketplace items in the registry is translated -> has to be done first

### Subtasks
- [ ] translate the most important items from the marketplace registry
- [ ]

**Comment by floiem** [comment]
@samuelstroschein so I just go for the marketplace / landingpage itself and we'll see the impact there?

**Comment by samuelstroschein** [comment]
@floiem yes. we need markdown tooling before we translate documents. otherwise, we will be screwed :)

**Comment by flornkm** [comment]
Closing as SEO is now dogfooded with https://github.com/inlang/monorepo/commit/1d442f25d04da949d580dfcf04e823c62bbd9d7c 

See:

<img width="1679" alt="Screenshot 2023-11-21 at 1 34 14 PM" src="https://github.com/inlang/monorepo/assets/92092993/9c633025-9732-43e5-94bb-fb00c765ef0e">
<img width="1703" alt="Screenshot 2023-11-21 at 1 33 55 PM" src="https://github.com/inlang/monorepo/assets/92092993/1876321a-1727-4d64-8c3d-44ae8891f63c">


This is likely an ongoing task (as new pages appear, sometime we will have inlang Markdown, and sometime we translate the images too).
