### ISSUE TITLE
[bug] The VS Code extension is not working on Windows

### ISSUE THREAD

**Issue by JLAcostaEC** [inlang/monorepo#1554]
### Problem

Following the instructions at [Inlang Docs](https://inlang.com/g/2fg8ng94/guide-nilsjacobsen-buildAGlobalSvelteApp) i'm getting the following error:  `There is no `plugin` configuration for the inlang extension. One of the `modules` should expose a `plugin` which has `customApi` containing `app.inlang.ideExtension``

After changing the paraglide-js module to `"https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js"` the error keeps showing.

I'm working on Windows 11, with VS Code and SvelteKit (All on the latest version)

### Reproduction

1. Just initialize a SvelteKit Project (With the Skeleton App or an empty app).
2. Follow the instructions at [Inlang Docs](https://inlang.com/g/2fg8ng94/guide-nilsjacobsen-buildAGlobalSvelteApp)
3. With that, the error appears.

[Reproduction Repo](https://github.com/JLAcostaEC/inlang-test)

### Other information

Browser: Edge 118
OS: Windows 11 Home 22H2 Build 22621.2506
Processor	AMD Ryzen 5 5600G with Radeon Graphics 3.90 GHz
Installed RAM	32.0 GB (31.4 GB usable)
System type	64-bit operating system, x64-based processor

Screenshots:

![image](https://github.com/inlang/monorepo/assets/61467132/d5c25a69-bb69-4409-addb-afa841211802)

![image](https://github.com/inlang/monorepo/assets/61467132/91fd2c6a-5356-4fe3-8c86-11c968df9af7)

**Comment by felixhaeberle** [comment]
I unfortunately don't work on Windows, that's why I can't reproduce it myself. But it's working great for the online ide:

<img width="1275" alt="Bildschirmfoto 2023-11-02 um 18 38 52" src="https://github.com/inlang/monorepo/assets/34959078/a8e8b03c-323e-41b6-8eb0-08708eb61be7">

Is this an option for you? Otherwise, we have to investigate further on Windows.

**Comment by JLAcostaEC** [comment]
For now, I'll be working on Linux, but I think the VS Code plugin should work on Windows to support more developers. This is because some employers may force some developers (like me) to work on some operating systems. So with that said, I have tried to understand a little how the code works to obtain the `ideExtension` parameter. I have placed a random UUIDV4 in the plugin configuration in VS Code, and it no longer shows me that error, but now show me:

![image](https://github.com/inlang/monorepo/assets/61467132/c9e4281c-333e-4c85-9533-3fa05cf1014d)
![image](https://github.com/inlang/monorepo/assets/61467132/2fbfb999-3d8a-4c46-a5b7-76a9e7ef69f5)

I think the problem is in how the Token is obtained or how it is saved. Since I see that you use `Validbot` to validate the token, I have to read more code to try to understand what is happening and try to find a solution from my side. I will be happy to help solve the problem.

**Comment by felixhaeberle** [comment]
Really cool, so I will guide you through it if you want to do a PR. 

The "magic" happens in the initProject function in the main.ts file in inlang/source-code/ide-extension.

From there, a function called loadProject of the inlang/sdk loads your modules defined in the project.inlang.json, which imports the modules like the inlang message format plugin & the m function matcher. These plugins set properties within the inlang object, which gets returned by loadProject.

One of these properties is the customApi for "app.inlang.ideExtension", which holds the information how the ide extension should parse the files. If you installed the m function matcher (located in inlang/source-code/plugins/m-function-matcher) it will obtain the config from there.

Up until this point, you should be all set up, inlang message format plugin should expose loadMessage / saveMessage for the ide extension to use to load/save messages & the m-function-matcher should provide you with the ability to display inline decorations (translation next to your code).

**Comment by felixhaeberle** [comment]
@JLAcostaEC Do you need any additional help to get started debugging this?

**Comment by JLAcostaEC** [comment]
@felixhaeberle Due to several other emergencies I have not been able to contribute to this, it is possible that it will start between today and tomorrow, although I have already cloned the repo.
