### ISSUE TITLE
make first image in the gallery the cover image

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1556]
## Problem 
The cover images are not rendered on the product page which likely leads to drop off. 

## Proposal 
Use the first image in the gallery as the cover image. 

**Pros**
- we can get rid of the "cover image" prop in the manifest
- the cover image is automatically included on the product page

Watch the screen recording here: https://jam.dev/c/97a70d44-657d-44d4-bae3-ed8f473b7498

\-------------------------------------

**Website URL:**
[https://inlang.com/c/lint-rules](https://inlang.com/c/lint-rules)

**Device and browser info:**
Chrome 118.0.5993.117 (1440x758) | Mac OS (arm) 10.15.7

**Date and time:**
October 31st 2023 | 7:25pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/97a70d44-657d-44d4-bae3-ed8f473b7498](https://jam.dev/c/97a70d44-657d-44d4-bae3-ed8f473b7498)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by samuelstroschein** [comment]
@floiem are those jam.dev issues useful to you or should i write an issue/make a loom? here would be the loom https://www.loom.com/share/2920965c933a4e6a8115e295a4fe406d?sid=151a4da5-46ab-4573-8f5f-a9aa012d26bb

**Comment by floiem** [comment]
@samuelstroschein the jam.devs are useful.
The gallery is just shown when images.length > 1, otherwise the gallery is implemented see e.g. on the editors item page.
Will change that the gallery is always shown.

**Comment by floiem** [comment]
Should be resolved with https://github.com/inlang/monorepo/commit/052c9b26446d6fef72f6742135e0703b1cbcecc3
