### ISSUE TITLE
[improvement] change position and design of the lix badge

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1559]
### Problem

it's  confusing when the Lix badge is right after the original name 
And it is not intuitive that lix is a button. I accidentally hovered over it
![CleanShot 2023-10-31 at 23 45 16@2x](https://github.com/inlang/monorepo/assets/72493222/cbb87157-36cd-4faf-b00d-56e9397db9f0)

### Expected behavior

have the Lix badge as an item spec on the right side 
with the name powerd by lix 
![CleanShot 2023-10-31 at 23 46 05@2x](https://github.com/inlang/monorepo/assets/72493222/d26e285e-2d3d-4ed0-b804-d1a5c1ef9c6b)

### Reproduction

https://inlang.com/m/tdozzpar/app-inlang-editor

**Comment by floiem** [comment]
@jannesblobel thanks for the feedback! I wouldn't label it as a bug though, we decided to implement lix badge on the item page on purpose. :D

**Comment by floiem** [comment]
lix spec is implemented with https://github.com/inlang/monorepo/commit/902b48799007fd1acc5ca10579d999df5b25ad4d
