### ISSUE TITLE
[bug] the selection of multiple branches is possible in the branch selection editor dropdown

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1560]
### Problem

I can select multiple branches, and  before the editor changes the branch, it takes several seconds 
![CleanShot 2023-10-31 at 23 58 22@2x](https://github.com/inlang/monorepo/assets/72493222/29873071-95f2-4a17-bb6c-e05182d8d385)

### Expected behavior

Click on a branch, and the Editor changes the branch immediately or gives me a hint, which could take a few seconds. 
It shouldn't be allowed to select/pick branches ( checkbox vs radio button) 

### Reproduction

1. go to https://inlang.com/editor/github.com/inlang/monorepo
2. log in 
3. select a branch

**Comment by NiklasBuchfink** [comment]
This shouldn't be a multi-select and it might take a few seconds, but there should be sufficient user feedback that reflects the state. Good catch 👍

**Comment by NiklasBuchfink** [comment]
@jannesblobel I did a quick fix for this (https://github.com/inlang/monorepo/commit/144604389afd1033557a42a54df0257714a82737). 
During the loading time of the other branch the button is set to loading.

This time will shrink with https://github.com/inlang/monorepo/issues/1459
