### ISSUE TITLE
fix broken links 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1565]
## Problem 

<img width="1099" alt="CleanShot 2023-11-01 at 13 39 43@2x" src="https://github.com/inlang/monorepo/assets/35429197/f20332ce-776f-4894-b8a5-8f95683604d1">

https://www.brokenlinkcheck.com/broken-links.php#status

## Proposal 

Fix links. 

## Additional information 

We should prob have a github action that checks for broken links in a given interval like https://github.com/marketplace/actions/broken-link-checker-action (but that one is unmaintained)

**Comment by floiem** [comment]
@samuelstroschein don't you think this gets fixed with the sitemap anyway? I couldn't find anything about how the link checker works, but it seems like it is simply looking up the links from google with`"… site:inlang.com"` as input?

**Comment by samuelstroschein** [comment]
@floiem it scrapes inlang.com. those are not broken links on google but broken link on our website

**Comment by flornkm** [comment]
broken links are fixed, almost all broken links came from README's of the marketplace items. Will research if I can find a github action for it, maybe not all links are fixed yet because of CDN cache.

**Comment by samuelstroschein** [comment]
@flornkm you could have a script in the registry that crawls the links in the documents

**Comment by flornkm** [comment]
@samuelstroschein would these be the possible steps to achieve this:

1. reading / fetching the manifest file
2. extracting the link to readme
3. reading / fetching the link to readme
4. converting the raw markdown to include only the links 
5. opening a virtual browser with chromium / puppeteer to look if the page responds with `404`

**Comment by samuelstroschein** [comment]
@flornkm too complicated. 

1. fetch the markdown file
2. convert the markdown file to HTML (which we do anyways)
3. get the <a> links
4. make a regular fetch(link) request (no need to have a virtual browser) 

BUT too much effort for now i think. i would skip this automation and occasionally check for broken links and update them
