### ISSUE TITLE
[bug] seo titles affect routing

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1566]
## Problem 

SEO titles like https://inlang.com/m/gerre34r/library-inlang-paraglideJs affect the routing which should not be the case. 
- renaming the SEO title will lead to 404s

## Reproduction 

1. Open https://inlang.com/m/gerre34r/library-inlang-paraglideJs
2. Remoshouldve text from the SEO title like https://inlang.com/m/gerre34r/library-inlang
## Expected behaviour

Opening any link with an id should never return a 404 if the SEO text is invalid (instead re-direct) 
https://inlang.com/m/gerre34r/library should redirect to https://inlang.com/m/gerre34r/library-inlang-paraglideJs

## Additional information 

@flo this seems to be a classical "if no unit test exists, this will be broken in the future". Can we write unit tests for routing?

Watch the screen recording here: https://jam.dev/c/d42c82c1-a600-4c95-af42-3a0766bb2620

\-------------------------------------

**Website URL:**
[https://inlang.com/m/404](https://inlang.com/m/404)

**Device and browser info:**
Chrome 118.0.5993.117 (1440x758) | Mac OS (arm) 10.15.7

**Date and time:**
November 1st 2023 | 5:45pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/d42c82c1-a600-4c95-af42-3a0766bb2620](https://jam.dev/c/d42c82c1-a600-4c95-af42-3a0766bb2620)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by kiemflo** [comment]
@samuelstroschein the bug itself is fixed. Where does it make sense to write the unit tests and do we already have some of these?

**Comment by samuelstroschein** [comment]
@kiemflo we don't have unit tests. don't know how to write one for this behavior. if you can figure something out in 10 mins, go for it. else, move on

**Comment by flornkm** [comment]
Closing this for now as I haven't found a solution that quickly could be implemented (and the bug itself is already fixed).
If that bug happens in the future again, we can think of using `e2e` test for it like brillout does here in his i18n example: https://github.com/vikejs/vike/tree/main/examples/i18n-v1
