### ISSUE TITLE
[improvend] add Recommendations/ other people also use stack  

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1568]
### Problem

It needs to be clarified which items match and are recommended/suggested. 

We can't use Algolia's 'Complementary recommendations'  because we haven't any conversion rate yet. Thought: "We could use the 'install plugin' button as one of x conversion trackers." 

### Proposal

Add another property in the marketplace manifest like: `recommendations`: []. We can use the ID (3i8bor92) of the articles to list and also weight the recommendations. 

### Other information

![CleanShot 2023-11-01 at 18 42 20@2x](https://github.com/inlang/monorepo/assets/72493222/ef1ab2bc-986c-46c6-8f4c-8dd210f3f7e1)

**Comment by samuelstroschein** [comment]
Not "we" recommend but "this product recommends" 

```json
{
   // array of registry ids that the product recommends
   recommends: ["m/uhasoufb", "m/pijnsu2"]
}

```

**Comment by jannesblobel** [comment]
Yes, that was just in case there is more than one. It doesn't matter at the beginning. The same goes for the wording; it was just so you understand what was meant.
