### ISSUE TITLE
[bug] Login redirect of `/install` is not working

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/monorepo#1580]
### Problem

If you're not logged in already and try to install a lint rule:

![image](https://github.com/inlang/monorepo/assets/59048346/9d847eec-16c3-4fc2-a224-293eb863cb55)

The click on the "Sign in with GitHub" button only closes the modal:

![image](https://github.com/inlang/monorepo/assets/59048346/0ba8ecae-5541-409a-8ca8-234598dec56c)

### Expected behavior

Redirect to GitHub login and have a working login flow that lint rules can be installed again.

### Reproduction

1. Make sure you are not logged in already
2. Try to install any lint rule
3. Try to login

### Other information

We can probably just look at the editor login and see what is different.

**Comment by flornkm** [comment]
is closed as of https://github.com/inlang/monorepo/commit/67ca8d42c9c47afab31b85e64a58578076430c71
