### ISSUE TITLE
inlang.com/new

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1583]
## Problem 

Getting started with inlang is a big "how question mark" 

## Proposal 

Introduce a guided getting started a la 

- What do you want to achieve?
- Are you a developer/designer?
- etc.

### Discussed in https://github.com/inlang/monorepo/discussions/1299

<div type='discussions-op-text'>

<sup>Originally posted by **samuelstroschein** August 28, 2023</sup>

# 📺 [loom](https://www.loom.com/share/e0510d1bef1046fb8ed97b45a1feaf67?sid=2fba9d5e-a13c-455c-856e-928b4cb9c0d9)

## Problem 

- The CLI init only works for a subset of users (web devs with node.js installed)
- Thus, we have multiple ways to create a new project that all need to be explained and maintained 

## Proposal 

Have one way to create a new project that works for every user persona via a guided setup on `inlang.com/new`. 

**Pros**

- no "getting started" explanation (!!!) -> just "create a new project"
- we can hyper optimize that one way an inlang project is created
- less effort because only one way to create an inlang project needs maintenance

**Cons**

- as long as local repositories are not supported by @inlang/lix, creating a project requires signing-in [BUT strong argument now to push @inlang/project-lisa top open local repos]

**Additional information**

- @inlang/lix needs less auth requirements ASAP :D Otherwise, users are steered away by the auth scopes
</div>

**Comment by janfjohannes** [comment]
@samuelstroschein could you explain " less auth requirements "

**Comment by samuelstroschein** [comment]
@janfjohannes the issue description is from auguast. the auth permissions have been implemented 

<img width="352" alt="CleanShot 2023-11-06 at 10 27 06@2x" src="https://github.com/inlang/monorepo/assets/35429197/0b18a111-2683-41ee-a77e-749cf038aa5c">

**Comment by samuelstroschein** [comment]
Not relevant anymore with the new ecosystem/marketplace strategy. 

Building and maintaining a "unified" getting started does not and will not work. How to get started with inlang ecosystem products vastly differs. Each product is responsible for providing a specific, and thereby better, getting started experience.
