### ISSUE TITLE
[Docs] TS Module Resolution (Node16 | Bundler | NodeNext)

### ISSUE THREAD

**Issue by JLAcostaEC** [inlang/monorepo#1584]
## Problem 

Now if you have a project without configuring `tsconfig.json` with `compilerOptions.moduleResolution` to `Node16`, `Bundler` or `NodeNext` you will get an error when try to import `messages` or `runtime` files.

![image](https://github.com/inlang/monorepo/assets/61467132/6b345b72-bd31-4325-9fac-d4e7fa6903f0)

Normally it works by default but when using inlang in some older project, we will get this error

## Proposal

Add documentation to notify this requirement.

**Comment by samuelstroschein** [comment]
Thanks for the proposal!

I recently introduced the paraglide-init command in prerelease.5 which prompts setting the compiler options to Bundler. Do you think that suffices? 

PS the importing of messages will change with https://github.com/inlang/monorepo/discussions/1579

**Comment by JLAcostaEC** [comment]
Excellent, makes me sense to avoid compiling into node_modules. So I think that we can close this issue.

**Comment by samuelstroschein** [comment]
implemented
