### ISSUE TITLE
Replace CMD+K with /

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1586]
## Problem 

- CMD+K is Mac specific
- Google and GitHub don't use `CMD+K` but `/` (i suppose for good reasons)

<img width="443" alt="CleanShot 2023-11-03 at 17 03 02@2x" src="https://github.com/inlang/monorepo/assets/35429197/a7393e94-6980-4d70-9ab7-d3c670d33996">

## Proposal

Use `/` for search like Google and GitHub?

**Comment by flornkm** [comment]
@samuelstroschein I have now implemented the shortcut for all users who aren't using macos, I have talked to some mac dudes and everyone is enjoying using cmd + k / has gotten used to it. The Windows people can use `/` and we can change that in the future if there are strong arguments to make the "commands" the same.
https://github.com/inlang/monorepo/commit/c86bdfce092eebf51e84a676d0421452579b8ab0

**Comment by samuelstroschein** [comment]
@flornkm please use `/`. have two different flows for mac os and other platforms is bad UX (why is the command I know from platform a not working on platform b) and higher maintenance effort for us

**Comment by flornkm** [comment]
@samuelstroschein let's not discuss too long, the maintainability part is understandable and I will unify it therefore – but I consider it to be bad UX to have commands no one knows just to align both platforms. It is good UX to align the commands to the OS of the user so he doesn't have to learn something new, at least I never used `/` ever before (doesn't even work for me on german keyboard haha)

**Comment by flornkm** [comment]
https://github.com/inlang/monorepo/commit/bdad093e038a73c8cc93af1b9f8baab4eb8f90ef

**Comment by jannesblobel** [comment]
`/` for jumping into the search is a bit annoying if you try to write something where a / is included. 

**Proposal** 
1. go back go cmd+k 
Pro: it is a keyboard shortcut and prevents someone who needs/wants to type the `/` somewhere from jumping into the search. 
(You also can use cmd+k on Github) 
Con: CMD+K is Mac specific


2. `/` works only if nothing else is in focus ( input not focused)
Pro: Users can use a / in an input field
Con: Does it take more time to implement? 




![CleanShot 2023-11-21 at 11 45 11@2x](https://github.com/inlang/monorepo/assets/72493222/095f7ec8-4014-4975-b41d-4a3da92de568)

https://www.loom.com/share/d2f9b23b49cf4a9e9f28cd73597a1832

**Comment by flornkm** [comment]
@jannesblobel thanks. I have decided to leave `/`. If we target devs, they often don't have MacOS machines.
Instead, I fixed it by looking if the user has already focused a generic input element or the `INLANG-BADGE-GENERATOR` (yes, this is the official element name haha).

This way, the UX flaw got fixed without going back to cmd + k.
