### ISSUE TITLE
[bug] installing modules via inlang.com is broken

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1587]
### Problem

The installed links are wrong

<img width="837" alt="CleanShot 2023-11-04 at 17 04 56@2x" src="https://github.com/inlang/monorepo/assets/35429197/c29cd17c-22e4-40ac-905c-7b582747d289">

### Expected behavior

```diff
-"https://cdn.jsdelivr.net/npm/@latest/plugin-message-format/dist/index.js"
+"https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js"
```

### Reproduction

1. install https://inlang.com/m/632iow21/plugin-inlang-mFunctionMatcher

### Other information

- [x] #1588

**Comment by flornkm** [comment]
@samuelstroschein fyi this isn't a bug of installation, it is the link that was entered wrongly:
```
        ...
	"module": "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format/dist/index.js"
}
```
Will implement more strict checks in the marketplace registry to prevent this from happening in the future.

**Comment by flornkm** [comment]
Closing the issue as the wrong module link in the manifest is now changed (https://github.com/inlang/monorepo/commit/67ddc6fc51a44ce07be5520e86f375d410315e86) and the registry is looking deeper into the manifests, checking if the link is really valid. If using the type schema for `json` it should be inline linted anyway as we already have introduced that.
