### ISSUE TITLE
notify to update CLI to latest major version / auto-update to latest minor 

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1591]
## Current Behavior

At present, users may not be aware of the availability of new releases, and manual updates are required. This can lead to users running outdated versions with known bugs.

## Opportunity

To enhance user experience and mitigate potential issues, it would be beneficial to implement a notification mechanism urging users to update to the latest version. Additionally, providing an option for auto-updating to the latest minor version can streamline the process and ensure users are on the most stable release.

## Proposal

- Users should receive notifications within the CLI interface when a new version is available. 
- Additionally, users should have the option to auto-update to the latest minor version directly from the CLI prompt.

### Implementation

only a rough sketch, misses a few parts:
- run on "preHook"
- have minimal surface API `latestVersion, currentVersion, update()`
- have minor update happen in background, notify on major

```ts
  .hook("preAction", (command) => {
   //...

    // Check for the latest version and notify if there's a major version update
    const latestVersion = getLatestVersion();
    const currentVersion = getCurrentVersion();

    if (isMajorVersionUpdate(currentVersion, latestVersion)) {
      notify(`A major update (${latestVersion}) is available. Please consider updating.`);
      // Optionally, prompt the user to update
      prompt("Do you want to update to the latest version?");
    } else {
      // Check for the latest minor version and update automatically in the background
      updateToLatestMinor();
    }
  });
  
// --------------- //  
// UPDATE UTILS
// --------------- //

// Dummy function to check if there's a major version update
export function isMajorVersionUpdate(currentVersion: string, latestVersion: string): boolean {
  return semver.major(currentVersion) !== semver.major(latestVersion);
}

// Function to get the current version by executing "npx @inlang/cli -v"
export function getCurrentVersion(): string | null {
  try {
    const output = execSync('npx @inlang/cli -v', { encoding: 'utf-8' });
    // Extract the version from the output (assuming it's in the format "vX.Y.Z")
    const match = output.match(/v(\d+\.\d+\.\d+)/);
    return match ? match[1] : null;
  } catch (error) {
    console.error('Error getting current version:', error.message);
    return null;
  }
}

// Function to update to the latest minor version in the background
export function updateToLatestMinor(): void {
  try {
    // Execute the update command in the background
    execSync('npx @inlang/cli@latest', { stdio: 'ignore' });
  } catch (error) {
    console.error('Error updating to the latest minor version:', error.message);
  }
}
```

**Comment by felixhaeberle** [comment]
@rishi-raj-jain If you have any question feel free to ask, but we normally had something like npm update notification in mind which you get after running a command. 

if it's possible, we would like to auto-update minor versions in the background. 
I'm curious what you come up with.

**Comment by rishi-raj-jain** [comment]
Thanks for the context. Right now, it fetches the latest version and checks it for a major update.

I can update the code to automatically install the minor update if it's not a major one. @felixhaeberle let me know if I shall do it.

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

How is this looking? Anywhere I can make improvements? Happy to contribute the best thing that makes sense for you.
