### ISSUE TITLE
[improvement] introduce copyable commands like e.g. npm does

### ISSUE THREAD

**Issue by flornkm** [inlang/monorepo#1600]
## Problem 
- e.g. libraries just have a github link as "primary" interaction
- users have to scroll down instead of just being able to copy the command they search for
- no one wants to read the whole readme just for getting the init command

## Proposal
- introduce a new component that lets you copy the command needed for the library
- add a new property to the libraries to contain a command that can be copied

**Comment by samuelstroschein** [comment]
did we agree on "no props to the manifest will be introduced, use the readme to convey your commands?"?

**Comment by flornkm** [comment]
@samuelstroschein oh yes, totally forgot to close the issue.

**Comment by flornkm** [comment]
closing as not planned because you can advertise the command directly in the readme.
