### ISSUE TITLE
token exdiry logout force broken after editor factor out

### ISSUE THREAD

**Issue by janfjohannes** [inlang/monorepo#1604]

**Comment by samuelstroschein** [comment]
context 
<img width="801" alt="CleanShot 2023-11-07 at 11 51 22@2x" src="https://github.com/inlang/monorepo/assets/35429197/1469f4c3-5f19-4465-a3c1-312ebc057b57">

**Comment by janfjohannes** [comment]
@samuelstroschein  @NiklasBuchfink   fix should be live now
