### ISSUE TITLE
compile into source code instead of node modules

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1607]
- [x] compile only JSDoc. get rid of typescript declaration stuff
- [x] remove namespacing stuff
- [x] init command must set "checkJs" "allowJs" to true
- [ ] split messages to signal messages/de imports to everyone

---

### Discussed in https://github.com/inlang/monorepo/discussions/1579

<div type='discussions-op-text'>

<sup>Originally posted by **samuelstroschein** November  2, 2023</sup>
Vote with 👍 or 👎 

## Problem 

The majority/all JS tooling default assumes that code in `node_modules` is static. Paraglide's compilation into node_modules breaks that assumption, leading to bugs that are fixed with workarounds. 

## Proposal 

Don't compile into node_modules. Instead, compile into the source code itself with a git ignore. 

```diff
-import { setLanguageTag, languageTag } from '@inlang/paraglide-js/sveltekit-example';
+import { setLanguageTag, languageTag } from '../../paraglide-js/runtime';
-import * as m from "@inlang/paraglide-js/sveltekit-example/messages"
+import * as m from "../../paraglide-js/messages"
```

![CleanShot 2023-11-02 at 16 34 46@2x](https://github.com/inlang/monorepo/assets/35429197/52901018-a361-45db-9518-a76ebad345b9)

**Pros**

- no need for "namespacing" as two codebases won't compile into the same directory, see https://github.com/inlang/monorepo/discussions/1464#discussioncomment-7280355
- less bugs because the majority of tooling (typescript, bundlers, etc.) expects node_modules to be static, see https://github.com/inlang/monorepo/pull/1533, https://github.com/inlang/monorepo/issues/1485#issuecomment-1779918933, https://github.com/inlang/monorepo/issues/1518#issuecomment-1790682159
- no need for declaration files as typescript can resolve JSDoc itself (simpler compiler!)

**Neutral**

- users are responsible for importing messages themselves (no more explaining of 'namespaces' `@inlang/paraglide-js/{name}/messages`; imports will differ per user (but it's just normal JS after all!))

**Cons**

- "pollution" of source code (gitignore to the rescue)

https://github.com/inlang/monorepo/assets/35429197/046a3a0b-fb77-489a-bfd1-aa00b0e178c7

</div>

**Comment by DanikVitek** [comment]
This way the dependency itself can be moved to the `devDependencies` section

**Comment by samuelstroschein** [comment]
> This way the dependency itself can be moved to the devDependencies section

correct!
