### ISSUE TITLE
m function does not match after prerelease.6

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1608]
## Problem 

The prelease.6 got rid of node module imports see #1607 . The m function checks for a node module import to prevent false positives, resulting in no matches. 

## Proposal 

Remove the heuristic of imports on top of the file. With prerelease.6, users can import any directory. Hence, matching the m function alone seems to be the only reliable way, at the risk of a few false positives.

**Comment by felixhaeberle** [comment]
@samuelstroschein can we still match "import * as m" ?

**Comment by samuelstroschein** [comment]
Yes we can! Good idea!
