### ISSUE TITLE
vscode extension shows source code errors which are no source code errors

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1613]
## Problem 

missing translations are not a source code error. yet, the vscode extension shows them as source code error

**effect**

- users will uninstall the ide extension because it's so annoying. 
- users think paraglide js is buggy

<img width="757" alt="CleanShot 2023-11-08 at 11 25 07@2x" src="https://github.com/inlang/monorepo/assets/35429197/b9b51873-8f9e-4d2f-a7d7-044f88fba51d">

## Proposal

show inline error messages but not as source code error. really unexpected and annoying

**Comment by felixhaeberle** [comment]
@samuelstroschein how to solve this? I didn't understand the problem from your explanation. 
If the message is not existing, the message can't be omitted that there is no according function on the m. object.

**Comment by samuelstroschein** [comment]
Does the video explain my cause?

https://github.com/inlang/monorepo/assets/35429197/b3b4d7a6-c83f-42dc-8743-fe5708da7676

**Comment by felixhaeberle** [comment]
where can I test this?

**Comment by samuelstroschein** [comment]
@felixhaeberle aha good point. 

in that case, it's super annoying that we have missing translations :D

**Comment by samuelstroschein** [comment]
@felixhaeberle no worries! missing translations will be a thing of the past with the directory proposal next week
