### ISSUE TITLE
product/module pages should show how to install a module manually 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1626]
## Problem 

- Installing a module requires full repository access, a no-go for large enterprise customers
- the product page does not explain that and how a module can be added manually
- expecting every module to explain how the module can be added manually is a recipe for disaster

<img width="631" alt="CleanShot 2023-11-12 at 10 52 04@2x" src="https://github.com/inlang/monorepo/assets/35429197/a0535e85-5c26-47cc-b33e-adf840db9ec4">

<img width="922" alt="CleanShot 2023-11-12 at 10 53 02@2x" src="https://github.com/inlang/monorepo/assets/35429197/3e2e19fb-3c1f-4b91-afaf-505bdc9fa8cb">

## Proposal

Add a second button/something that allows me to copy and paste the module link to my project file. 

![CleanShot 2023-11-12 at 10 52 04@2x](https://github.com/inlang/monorepo/assets/35429197/4d5e5a69-8294-461b-83de-4b996a487c1b)

![CleanShot 2023-11-12 at 10 57 19@2x](https://github.com/inlang/monorepo/assets/35429197/c0537817-a3d1-44e0-b6d2-b4f46738e038)

**Comment by samuelstroschein** [comment]
The discussion can be found here https://discord.com/channels/897438559458430986/1070750156644962434/1173264650138296401

**Comment by samuelstroschein** [comment]
Actually, I think a much better flow is: 

1. Button "install"
2. Forwards to the install page
3. The install page describes how to install a module manually, or prompt to login/go the guided flow

**Pros**

- no need for multiple buttons (which is confusing)
- No need for dropdowns in "install" because the installation page can show recent projects (confused users, lead to bug reports)

![IMG_7445](https://github.com/inlang/monorepo/assets/35429197/a681a614-44b0-4d32-9518-5f276708a493)

**Comment by flornkm** [comment]
This was implemented in https://github.com/inlang/monorepo/commit/818850dbe0fba22378b4674d13458559ffffe8cc 

See screenshot:
<img width="1710" alt="Screenshot 2023-11-13 at 12 47 57 PM" src="https://github.com/inlang/monorepo/assets/92092993/8f921358-819d-4676-bdff-24980da9a68f">

**Comment by samuelstroschein** [comment]
@flornkm so good <3
