### ISSUE TITLE
[Improvement] Improve npm missing meta data 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1629]
### Problem
Some metadata are missing: 
- [x] Keywords 
- [x] Author fields are incorrect
- [ ] Readme.md are not updated 

### Keywords
Paraglide-js hasn't any keywords on npm. This makes it hard to find paraglide in a search and probably also on Google ( SEO) 
Proposal :
add keyword to the package.json
```
 "keywords": [
    "i18n,",
    "...",
    "....",
    "...."
  ],
```
![CleanShot 2023-11-13 at 12 17 16@2x](https://github.com/inlang/monorepo/assets/72493222/87a6a70c-1db0-4fd5-92c3-74d850f98fd6)

### outdated Readme
Still, todos left on npm and the readme is not the same as in the repo 

![CleanShot 2023-11-13 at 12 25 07@2x](https://github.com/inlang/monorepo/assets/72493222/4aa1dd75-e7fe-4afc-9fd1-cac63d41caed)

### Reproduction

Go on https://www.npmjs.com/package/@inlang/paraglide-js?activeTab=readme
scroll down

**Comment by flornkm** [comment]
@jannesblobel I've created #1644 for it. The readme seems to not update because no new version is released, I asked samuel if we should do that as the new version would only introduce a update readme.
