### ISSUE TITLE
unify concept / styling / content for all inlang README's (header, table of content, getting started ...)

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1630]
## Problem 

- Inconsistency in concept, styling, and content across inlang READMEs.
Affects: 
1. GitHub browsing
2. npm page rendering
3. marketplace page rendering.

## Proposal

- Develop a style guide for READMEs
- Create a template adhering to the style guide
- Update**all** package README's with those changes

❌ Bad example:

https://github.com/inlang/monorepo/blob/main/inlang/source-code/sdk/README.md

✅ Good example:

https://github.com/inlang/monorepo/blob/main/README.md
https://github.com/inlang/monorepo/blob/main/inlang/source-code/paraglide/paraglide-js/README.md

**Comment by samuelstroschein** [comment]
@felixhaeberle do you think that is necessary? Who will enforce and maintain the styleguide? 

Yes, bad that we have really ugly readme's but fix them as a one time task?

**Comment by flornkm** [comment]
@samuelstroschein what you mean with maintaining exactly, what has to be maintained? styleguide is not a design system, it is just recommendation for users in which direction they can go -> guide for how to style.

**Comment by samuelstroschein** [comment]
@flornkm every guide needs to stay up to date. otherwise, the guide will become useless. The more guides we have, the more needs to be maintained

**Comment by flornkm** [comment]
@samuelstroschein @felixhaeberle  I've already started with it cause I thought it would be good to share how we can make product pages engaging (also for the future when creating a new one) – just as a small illustration. Share it yes 👍 or no 👎?

![image](https://github.com/inlang/monorepo/assets/92092993/e54c7ada-a302-41a8-a881-1dee084d4143)

**Comment by samuelstroschein** [comment]
@flornkm seems good. generally, don't be fixated on one specific layout. we can allow users (in the future) to swap out the layout to whatever works best for them

**Comment by felixhaeberle** [comment]
I also talked about the README's in GitHub & not the MARKETPLACE.md's. From a developer perspective, I will likely browse GitHub, and there, I will not see the MARKETPLACE file.

**Comment by flornkm** [comment]
Closing because of https://github.com/inlang/monorepo/commit/cd19f09298294dbcb625763fc906bb07e18993c3 
(reopen again if guide is outdated)

Styling the READMEs on our site is an internal + ongoing task that I'm working on consistently. Now visitors / people like martin have a guide for the best practices.
