### ISSUE TITLE
update VSCode extension README with better Getting Started

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1635]
## Problem 
As seen & experienced in https://discord.com/channels/897438559458430986/1173918606975840286/1173919106513244270 – the onboarding and overall usage of the VSCode extension is not clear. 

## Proposal
We have to communicate more clearly & with a Step-by-step guide on how to set it up correctly. Mentioning the requirement of an load/save message module, the t / m function matcher & potential lint rules.

> Furthermore, a "inlang" tab would help for users to understand what is going on, display lints, display setup errors, do settings & more. The implicit behavior of just add a file (project.inlang.json) & the extension, results in users do not understand which functionality is offered & makes it very hard to communicate errors & impossible to do settings in a convenient way (like enable/disable inline decoration, set lang of inlang decoration etc.).

cc @openscript

**Comment by samuelstroschein** [comment]
@felixhaeberle i default assigned you to ensure that this issue gets handled

**Comment by felixhaeberle** [comment]
fixed 👍
