### ISSUE TITLE
customizable call to action buttons for products pages / remove "button" from manifest

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1646]
https://github.com/inlang/monorepo/assets/35429197/eb9bb25a-d3d2-460c-b262-59ace04ad047

## Problem 

1. The conversion for CTA buttons can be improved via customization
2. Customizing buttons via the manifest will lead to a massive manifest which is confusing

## Proposal

Remove customizable buttons from the manifest.json and force product pages to render buttons as images in the Readme.

**Pros**

- products can render whatever boosts conversions
- no bloated manifest that we need to explain and maintain

<img width="873" alt="CleanShot 2023-11-16 at 15 28 43@2x" src="https://github.com/inlang/monorepo/assets/35429197/6f1f03b5-c1ca-4539-973f-68034b7a7a8d">
<img width="871" alt="CleanShot 2023-11-16 at 15 28 38@2x" src="https://github.com/inlang/monorepo/assets/35429197/6dc5c7f7-4a4d-42b4-b196-78021101eba3">

**Comment by samuelstroschein** [comment]
@flornkm  good idea to drive conversions and remove the complexity of the manifest?

**Comment by felixhaeberle** [comment]
this is the wrong direction from a user perspective. I want a unique an "learnable" behavior to install an app. Every marketplace & app store work like this. Amazon "In den Einkaufwagen". Apple "Installieren". Of course, they only have one action, but I fear people not inserting a button / placing it in the wrong place leading to an EVEN WORSE conversion.

Also in the future, when you can directly purchase/subscribe to an app via the marketplace, giving this flexibility possibly introduces more complexity & a bad UX.

**Comment by flornkm** [comment]
There are many things I'm open to do which speak against common design guidelines, but buttons as images? No, I won't do it. This is wrong on many levels and I don't see the benefit in it as we already are using lit for custom web components such as banners.

**Counter proposal for the button-images:**
I can create a lit component for that – but we can also enable people to use a "big" banner-link like we already have introduced here: https://inlang.com/documentation 

@samuelstroschein generally, I agree and get your point. Let's use unavatar for getting the logos of the platforms inside of the buttons instead using images.

**Comment by flornkm** [comment]
Closing this. Have added the badges to the items where necessary:

Parrot: https://github.com/parrot-global/parrot/pull/5 (has to be approved my @martin-lysk)
IDE Extension: https://github.com/inlang/monorepo/commit/a439e814c4f069b2a1a0017ef4708d5d7f3aeb3d 

Feel free to re-open when we need more badges for other purposes or the platforms are introducing it (Figma / Vs Code)

**Comment by felixhaeberle** [comment]
@flornkm Thank youuu !
