### ISSUE TITLE
[improvement] wrong wording on inlang.com

### ISSUE THREAD

**Issue by flornkm** [inlang/monorepo#1649]
## Problem 
The wording on inlang.com sometimes doesn't make sense. In this case, guides AND products are shown, however the site states "all products" on top which gives the user wrong hopes: 

<img width="1710" alt="Screenshot 2023-11-17 at 12 59 54 PM" src="https://github.com/inlang/monorepo/assets/92092993/95914b91-54f5-4244-93c1-b60e85647982">

## Proposal

- Change the wording to "All results"

EDIT: The wording could also be wrong on other places in the website.

**Comment by NilsJacobsen** [comment]
I think I already removed it from the ecosystem subpages so that shouldn't be a issue there.

**Comment by NilsJacobsen** [comment]
FIxed it.
