### ISSUE TITLE
mobile browsing issues on marketplace

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1651]
spacing ![image](https://github.com/inlang/monorepo/assets/34959078/5ba3b8dc-82de-4d5a-9877-40b3e3055ea2)

alignment ![image](https://github.com/inlang/monorepo/assets/34959078/476b36b0-c46b-4930-838c-cf673297ef4d)

overflow (probably do overflow x hidden on body & make table scrollable?) ![image](https://github.com/inlang/monorepo/assets/34959078/c6403c5e-b23a-46c7-b783-11ea8d3ccf55)

text alignment
![image](https://github.com/inlang/monorepo/assets/34959078/e9aa1aa9-3b54-4140-9fbf-39695dbf2718)

**Comment by samuelstroschein** [comment]
Is this happening on Chrome/Safari too? If not, I vote for ignore brave browser

**Comment by flornkm** [comment]
Fixed with https://github.com/inlang/monorepo/commit/4c70e030ea5246bae6c5419ca1e86e1c0fea45ad

**Comment by felixhaeberle** [comment]
great!

**Comment by flornkm** [comment]
@felixhaeberle only thing left is making tables accessible on mobile, but that's not the most important atm. You cannot add horizontal scroll to a table, sadly. Let's look again in the future if someone complains why tables are not so readable on mobile.

**Comment by jannesblobel** [comment]
I opened inlang on my cell phone (Safari browser) and the readability is not so good. Do you also have this problem and should we just ignore it for now? 
![IMG_1045](https://github.com/inlang/monorepo/assets/72493222/7938bf0e-591e-4d4f-8737-2c20d3872b24)

**Comment by flornkm** [comment]
@jannesblobel wtf is this font??? pls tell me you are using an "Android Emulator"

![IMG_C0740373736D-1](https://github.com/inlang/monorepo/assets/92092993/c01a0278-edaf-419a-8485-1f07c167e3f4)

**Comment by felixhaeberle** [comment]
Can't reproduce.

**Comment by jannesblobel** [comment]
@flornkm nope default Safari on a Iphone
