### ISSUE TITLE
category page for lix apps

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1653]
https://github.com/inlang/monorepo/assets/35429197/50b147a4-41a4-46ec-8187-5c338a52aac0

## Problem 

1. 10% of every product page viewer clicks on "powered by lix" but receives a site with no explanation of what lix is
2. lix apps are not discoverable 

## Proposal

Introduce a "build with lix" category to: 

1. to provide an explanation of what lix is
2. make lix apps discoverable 

![CleanShot 2023-11-18 at 19 19 59@2x](https://github.com/inlang/monorepo/assets/35429197/749a7928-9c31-4100-9c3a-134b29fc2ba8)

**Comment by samuelstroschein** [comment]
@NilsJacobsen @flornkm do you prefer "just a loom" video or creating an issue (like i did here) with an embedded video?

**Comment by felixhaeberle** [comment]
my feedback https://www.loom.com/share/277554aede524a73bf4a20f4a715f31a

**Comment by NilsJacobsen** [comment]
@flornkm and I discussed it and gonna add the lix category (in the future we should not pollute the categories too much).

**Comment by flornkm** [comment]
> do you prefer "just a loom" video or creating an issue (like i did here) with an embedded video?

both is totally fine for me. I think a quick loom to send out quickly for smaller tasks is better. An embedded video at the right position would make more sense for bigger issues. But it also depends on if something has to be discussed or not

potentially leads to discussions -> definitely use loom, much easier to comment on timestamps

**Comment by flornkm** [comment]
Should be implemented with https://github.com/inlang/monorepo/commit/d8ea1997bcb92d3afec915ffe382b028c2ac0dc4

**Comment by samuelstroschein** [comment]
I love that we are iterating so quickly again <3 

Small feedback: Shouldn't the category name align with the badge name? Powered by lix makes it clearer IMO that "lix" is not a category like plugins or apps

![CleanShot 2023-11-20 at 08 11 26@2x](https://github.com/inlang/monorepo/assets/35429197/fa9b3025-4c2c-4306-b3ec-c74a6659b7e9)

**Comment by flornkm** [comment]
@NilsJacobsen what do you think? Would "Powered by lix" be too long in your opinion?

**Comment by NilsJacobsen** [comment]
Pro: Mental helper to understand lix and inlang
Cons: It's pretty long. (Amazon also puts prime there and not an explanation sentence)

I bet that people will learn fast what they get on the lix category. We gonna test that.

**Comment by samuelstroschein** [comment]
One last remark: Change the "powered by lix" icon with the actual lix icon for better recognition?

![CleanShot 2023-11-20 at 09 20 58@2x](https://github.com/inlang/monorepo/assets/35429197/819d0d27-c6c5-4c2e-9c41-8c367b62525d)
