### ISSUE TITLE
highlight powered by lix an app cards

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1654]
## Proposal

A 4 (?) week test to increase the discoverability of lix by adding the "lix" badge to app cards. 

**Pros**

- lix becomes more visible/discoverable 
- users can click on lix and get to #1653 

**Cons**

- might not be that useful (can be evaluated after X weeks. do users click on it?)

![CleanShot 2023-11-18 at 19 25 51@2x](https://github.com/inlang/monorepo/assets/35429197/9dd4c470-1d0c-4970-92ea-18bb72d88fa8)

**Comment by NilsJacobsen** [comment]
I think the bigger problem is, that we have problems communicating lix in generell. We can but it there, but then we should have a good way of explaining it when they click on it. 

Can we not just put the old lix landing page section on a subpage. That should be ready. Or we link to the design principles but it's probably not the best way to communicate benefits.

**Comment by flornkm** [comment]
@NilsJacobsen can this be closed?

**Comment by NilsJacobsen** [comment]
Yes
