### ISSUE TITLE
[bug] inlang.com/install layout is borken  

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1657]
### Problem

I tried to install the plugin via the install button on the marketplace page. 
Unfortunately, the layout is totally broken and the content is unreadable 

### Reproduction

Go to https://inlang.com/install?module=plugin.inlang.i18next

**Comment by jannesblobel** [comment]
screen size  macbook air 13" 13.3-inch (diagonal) 

![CleanShot 2023-11-20 at 15 13 32@2x](https://github.com/inlang/monorepo/assets/72493222/42297cbb-0956-41aa-88d6-1dd5ebe57ffc)
![CleanShot 2023-11-20 at 15 13 24@2x](https://github.com/inlang/monorepo/assets/72493222/73dc2d0d-c157-40b6-9eff-e8f7e8f48882)

**Comment by flornkm** [comment]
@jannesblobel thanks! should be fixed with https://github.com/inlang/monorepo/commit/45044e5cb39fb66a4078b3fcab636581925cc75f.
