### ISSUE TITLE
create crazy delicious icon for vs code extension

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1663]
## Problem 

We currently suck a bit on marketing on the ide extension listing. This might be due to an not so appealing appearance which seems rather "corporate".

<img width="1230" alt="Bildschirmfoto 2023-11-20 um 10 35 21" src="https://github.com/inlang/monorepo/assets/34959078/429d6299-6d82-4348-8692-36f4a209f7d5">

## Proposal

Create delicious i18n related logo people immediately click on because OMG it look so gooood.
Thank you! 🔥

Good example:

<img width="1676" alt="Bildschirmfoto 2023-11-20 um 17 15 36" src="https://github.com/inlang/monorepo/assets/34959078/709f4ef3-bffb-4aae-836f-88211682d49d">

cc @NilsJacobsen

**Comment by NilsJacobsen** [comment]
@felixhaeberle can this be closed?

**Comment by felixhaeberle** [comment]
thank you! 🔥
