### ISSUE TITLE
[bug] UX flaw for the lint rule filter

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1664]
### Problem

The lint rule filter shows too many warnings/and warnings where the filter is not applied. 

Fink also shows me the same pattern when I search for missing translations. Although I only searched for missing translations. 

### Expected behavior

It works like the language filter. 
Users filter for language de and en, and only these are showing. 

Users filter for lint rules "missing translations"; only this rule is showing, and the warning for all other Lint rules disappears. 

### Reproduction

Go to:
https://inlang.com/editor/github.com/jannesblobel/homepage?lint=messageLintRule.inlang.missingTranslation

### Other information

![CleanShot 2023-11-20 at 17 08 29@2x](https://github.com/inlang/monorepo/assets/72493222/58244c39-1f17-4d5d-8e68-61474e28bf44)

**Comment by NiklasBuchfink** [comment]
As we discussed, there are other options, but they come with their own UX problems.

The case of the language filter cannot be fully transferred to linting. The patterns are still visible and should be displayed according to the project configuration. If we hide other lint rules, we show an incorrect state for visible patterns.

The identical pattern lint rules pollute some messages with lints and an option to mute it would be great. (possible with directory proposal).

This is not a big deal if you select the languages you speak. We may come back to this later. Until then, I'm going to close this issue as not planned.
