### ISSUE TITLE
[bug] dogfooding destroyed routes to /documentation

### ISSUE THREAD

**Issue by flornkm** [inlang/monorepo#1671]
### Problem

The problem is, that the page doesn't load (just showing a white screen) when going to a `documentation` subpage with an alternate language tag.

### Expected behavior

The documentation loads and the navigation + footer should be dogfooded.

**Comment by NilsJacobsen** [comment]
@flornkm Are you already working on that?

**Comment by flornkm** [comment]
@NilsJacobsen no, I wanted to wait if you have an idea why this is the case just for some pages.

**Comment by NilsJacobsen** [comment]
Alright, should I investigate then? If yes, unassign only me:)
