### ISSUE TITLE
fix unordered list / bullet points in guides

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1673]
## Problem 

the bullet point list in the guides is broken 😄

## Proposal

have it displaying correctly.

<img width="1326" alt="Bildschirmfoto 2023-11-21 um 14 10 48" src="https://github.com/inlang/monorepo/assets/34959078/8fbc3e59-9824-4cbc-af8f-9c8a401abdb2">

**Comment by flornkm** [comment]
Should be fixed with https://github.com/inlang/monorepo/commit/9456586488a51b9ee0f556e3393460608dfc0973
