### ISSUE TITLE
Have `paraglide init` detect it's environment & suggest adapters 

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1676]
## Problem 
Currently paraglide users need to somehow _know_ that adapters are a thing. Even if they do know they exists, in order to get started they still need to do the full vanilla-js setup before adding the adapter. 

With the bundler adapters in #1669 this is pretty awkward since the vanilla setup requires the user to add `paraglide compile` to their build steps, and the adapters immediately make it obsolete. 

## Proposal
Have `paraglide init` scan it's environment for bundler / framework specific files, and the suggest installing the adapter during the initialisation flow.
If the user chooses to go with the adapter, then the install flow becomes tailored to that adapter.

(Eg. a project with a `vite.config{.js,.ts}` at it's root would have `@inlang/paraglide-js-adapter-vite` suggested)

**Comment by NilsJacobsen** [comment]
I feel like it is the right step to guide users with the paraglide-init flow.
When I was using paraglide-init I really liked that you get the small section with the next steps directly in the terminal. There is no need to go back to the docs. Let's keep that vibe 👍

**Comment by LorisSigrist** [comment]
Closing this as a duplicate of #1570. Didn't see that one
