### ISSUE TITLE
[bug] installing @inlang/mesasge-lint-rule-* with pnpm package manager fails postinstall script

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1684]
### Problem

installing any @inlang/mesasge-lint-rule-* package with pnpm package manager fails postinstall script & fails to install.

### Expected behavior

it would install correctly and can be relatively referenced from node_modules in `project.inlang.json`

### Reproduction

install the pnpm package manager `npm i -g pnpm`
run 
```bash
pnpm add -D @inlang/message-lint-rule-empty-pattern@latest
```
see error:
```bash
Packages: +1
+
Progress: resolved 437, reused 383, downloaded 0, added 0, done
node_modules/.pnpm/@inlang+message-lint-rule-empty-pattern@1.4.0_@sinclair+typebox@0.31.28/node_modules/@inlang/message-lint-rule-empty-pattern: Running postinstall script, failed in 34ms
.../message-lint-rule-empty-pattern postinstall$ patch-package --error-on-fail
│ 'patch-package' is not recognized as an internal or external command,
│ operable program or batch file.
└─ Failed in 35ms at D:\coding\svelte\pursiny-sveltekit\node_modules\.pnpm\@inlang+message-lint-rule-empty-pattern@1.4.0_@sinclair+typebox@0.31.28\node_modules\@inlang\message-lint-rule-empty-pattern
 ELIFECYCLE  Command failed with exit code 1.
 ```

### Other information

Vivaldi Latest stable
OS: Windows 10

**Comment by samuelstroschein** [comment]
Plugins and lint rules are not installed via NPM. Please refer to https://inlang.com/install?module=messageLintRule.inlang.emptyPattern for instructions. 

I added your confusion as an argument for #1688

**Comment by KraXen72** [comment]
this is how i wanted to install them:
https://github.com/albbus-stack/kit-stack/blob/main/project.inlang.json

**Comment by samuelstroschein** [comment]
@KraXen72 ha actually this should work locally. but ... it wouldn't work in the browser. hence, we discourage this pattern

**Comment by KraXen72** [comment]
jsdelivr is not that great tbh. i prefer to have stuff locally if possible, but i understand it makes sense for the web editor.

**Comment by samuelstroschein** [comment]
Upvote #1021 :)
