### ISSUE TITLE
Improve Paraglide docs

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1689]
from https://github.com/inlang/monorepo/issues/1667

## Problem 
Feedback from @KraXen72:
"i am not sure if this is the relevant issue for it, but it took me an hour or two to figure the following things out:

- npx @inlang/paraglide-js@latest init is apparently either supposed to install @inlang/paraglide-js to your project (even though npx does not imply installation usually, or you are supposed to instlal it manually (not mentioned anywhere). i ran the command with the pnpm package manager, pnpm dlx @inlang/paraglide-js@latest init and while it did set up the inlang project sucessfully, it did not add the dependency.
also, is @inlang/paraglide-js supposed to be instlled as a devDependency or normal one?
- it took me very long to figure out the import from ./paraglide-js/messages is intentional (it is also wrong)
what worked for me was importing form (whatever relative path to src is)/paraglide/messages (not paraglide-js)
no where it is mentioned that inlang compilation creates a folder called paraglide in the source folder upon build
i think the init script should automatically add an alias (vite or sveltekit alias, idk about other frameworks tho) to src/paraglide as something like $paraglide or @paraglide, and you should mention that this is an implicity created, invisible folder
- in the svelte summit talk, you guys mentioned that there are several translation formats supported, but only json works so far - but i see yaml is being tracked too, so that's good. would be nice to see more formats down the road"

@inlang/martketplace-infrastructure @inlang/paraglide-js

**Comment by NilsJacobsen** [comment]
I feel like we do need information when things happen under the hood. Maybe we can add collapsable element where we can go into detail without polluting the pages. What do you think?

**Comment by LorisSigrist** [comment]
A collapsible Element for an FAQ style section would be very convenient.

I'll rewrite the Docs to address the points listed above. 
(also the `init` command is supposed to add it as a devDependency, we might have a bug)

**Comment by NilsJacobsen** [comment]
If you need custom elements ping me or @flornkm we handle that so you should only work on the md file

**Comment by flornkm** [comment]
> A collapsible Element for an FAQ style section would be very convenient.

This was proposed very often. @LorisSigrist how urgent is it to have this element / when do you plan to use it?
@NilsJacobsen I can implement the element, that's fine

**Comment by LorisSigrist** [comment]
I don't need it urgently, I can do an FAQ by just listing out everything. 
It's more of a nice to have

**Comment by KraXen72** [comment]
thank you guys <33

**Comment by samuelstroschein** [comment]
> npx @inlang/paraglide-js@latest init 

Prompts to run pnpm,npm, yarn install after completion. Seems like @KraXen72 overread this. Question: How can we make this more prominent? 

> i think the init script should automatically add an alias (vite or sveltekit alias, idk about other frameworks tho) to src/paraglide as something like $paraglide or @paraglide, and you should mention that this is an implicity created, invisible folder

Disagree. It opens a the box of pandora: 

- doesn't work in plain JS
- might work for framework A but not framework B
- requires changes to both tsconfig and vite, rollup, turbopack, webpack config

**Comment by KraXen72** [comment]
understandable. however, atleast a few of the most popular bundlers could offer adding an alias. there are a lot of people using vite nowadays, and it supports asiases. or atleast mention how it all works, with the compiled paraglide directory

now that i re-rad the init command in a test repo, it does indeed show that you should run install.
but the paraglide-js dependency still gets added to dependencies (when using pnpm), instead of devDependencies - unless thats to be expected

**Comment by KraXen72** [comment]
left some feedback. it is a big improvement!

**Comment by KraXen72** [comment]
very nice. however, i still thing there should be a link to auto-generated, latest API docs in https://inlang.com/m/gerre34r/library-inlang-paraglideJs#runtime

this looks pretty good:

i found out you can literallly use jsdoc (the api documentation generator) by jsdoc (the github organization), who created jsdoc (the doc comments in js), to generate an api documentation site

https://github.com/jsdoc/jsdoc

**Comment by LorisSigrist** [comment]
Agreed, auto-generating the docs would be nicer & more robust. 
We would need to do the work to integrate the auto-generated docs into the website, and in the meantime doing it manually is better than not having it :) 

Definitely a nice-to have for the future!
