### ISSUE TITLE
Create Collapsable element for docs.

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1692]
## Feature
If we need to explain the details but want clean docs get a faq, we could use collapsables.

@inlang/martketplace-infrastructure

**Comment by NilsJacobsen** [comment]
-> https://github.com/inlang/monorepo/issues/1689

**Comment by flornkm** [comment]
The collapsable was introduced with this commit https://github.com/inlang/monorepo/commit/efa7482ba3a4d2b1e9a53f47281a8417de09a0ad
