### ISSUE TITLE
[refactor] Improve Github Actions efficiency

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1693]
## Problem 
Currently we do a lot of work multiple times for each action. 
For example: `ci` get's called in three separate actions. All of them have a reason to do so.
- `continuous integration` Calls CI (obviously)
- `versioning` Calls CI to not create changesets for broken
- `npm publish` Calls CI to not publish broken packages. 

## Proposal
Reorganize the Actions so that `versioning` and `npm publish` are dependent on the `continuous integration` action succeeding, so that they can trust that they are working with a working version without having to recheck.

This would roughly cut the CI work in half.

**Comment by samuelstroschein** [comment]
We just need to enable NX cloud again, and the issue is resolved. I will put this one my todo list.

**Comment by samuelstroschein** [comment]
Good proposal. 

In addition, we should re-enable NX cloud https://github.com/inlang/monorepo/issues/1705
