### ISSUE TITLE
How to sytle product pages not found 404 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1694]
go to https://inlang.com/c/guides
click on `How to sytle product pages`
encounter `item not found`

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/b99095b1c42d7ae35b973c1b6da3301c/screenshot/965d118f-3a99-4fa4-8c91-2d3769cc4663.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/b99095b1c42d7ae35b973c1b6da3301c/screenshot/d12a4684-e5a2-45d6-bc23-4dff0654e3ac.png)

\-------------------------------------

**Website URL:**
[https://inlang.com/c/guides](https://inlang.com/c/guides)

**Device and browser info:**
Chrome 119.0.6045.159 (1440x754) | Mac OS (arm) 10.15.7

**Date and time:**
November 22nd 2023 | 10:34am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/13d3c263-9038-434b-9f62-50d90b14d9da](https://jam.dev/c/13d3c263-9038-434b-9f62-50d90b14d9da)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by flornkm** [comment]
Algolia index wasn't updated.
