### ISSUE TITLE
[bug] vs code extension no longer supports extract or shows inline keys

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1700]
### Problem

see screenshots.
extract command doesen't work
![image](https://github.com/inlang/monorepo/assets/21956756/97c0c75c-87a0-4ab7-bdc4-f508dc02bf9b)
no key previews
![image](https://github.com/inlang/monorepo/assets/21956756/b130c27e-1fa6-47ed-86a8-580682d7100a)
i have the latest version installed
![image](https://github.com/inlang/monorepo/assets/21956756/63a8a728-fb61-4666-829c-499b1b77cb24)
does not show key previews with edit icons
![image](https://github.com/inlang/monorepo/assets/21956756/406534c0-047a-4795-8b92-20934a1a165b)

### Expected behavior

the command would exist and the keys would get a dynamic preview

### Reproduction

install extension version 1.18.0

### Other information

Vivaldi latest stable
windows 10

@inlang/ide-extension

**Comment by felixhaeberle** [comment]
@KraXen72 Has it worked before? With the old version? Or has it never worked?

**Comment by felixhaeberle** [comment]
@KraXen72 It's working on MacOS. Can you debug the problem?

https://www.loom.com/share/a6f00582247b4ff99bd6ff1cc7ba6f92

**Comment by KraXen72** [comment]
for me, latest version is 1.18. how recent is 1.19?

**Comment by KraXen72** [comment]
at the time of making this issue, i was coding for an hour long session. 15min in, you guys released v1.19, but it didn't get picked up by vscode yet. i'll see if the issue is still present v1.19 but thanks for the lightning fast response!

**Comment by felixhaeberle** [comment]
@KraXen72 Have you tried reloading your workspace? We will soon ship better error handling.

**Comment by KraXen72** [comment]
fixed in 1.20.1

**Comment by felixhaeberle** [comment]
@samuelstroschein 😎
