### ISSUE TITLE
re-enable nx cloud

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1705]
## Problem 

We disabled nx cloud because nx cloud cached env variables from dev to production. 

## Proposal

Let nx cloud invalidate the cache when env variables change 

## Additional information

- https://github.com/inlang/monorepo/pull/1325
- https://github.com/inlang/monorepo/issues/1693

**Comment by felixhaeberle** [comment]
@LorisSigrist Do you want to take over in conjunction with fixing the GitHub Actions?

**Comment by LorisSigrist** [comment]
I can do that.
That means enable nx cloud & make sure that it get's invalidated when environment variables change
