### ISSUE TITLE
[bug] nodeish memory fs allows writing undefined files

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1709]
### Problem

Nodeish fs does not check if the content of a file is not undefined or null when writing a file, leading to a misleading FILE NOT FOUND error even though the file exists/the dev thinks the file exists. 

![CleanShot 2023-11-22 at 16 08 30@2x](https://github.com/inlang/monorepo/assets/35429197/91ce3d5f-8ace-4d10-b938-d035b8c6da3e)

### Expected behavior

What does node do? I suppose throw when writeFile data is undefined

### Reproduction

(unverified)

```ts
const fs = createNodeishMemoryFs()
await fs.writeFile("/hello.json", undefined as any)
await fs.readFile("/hello.json)
```

**Comment by janfjohannes** [comment]
(will be in next merge)
