### ISSUE TITLE
[discussion + proposal] Why building a new website for install instead of publish it as a service

### ISSUE THREAD

**Issue by flornkm** [inlang/monorepo#1714]
## Problem 
@NiklasBuchfink and I have discussed how to move forward with #1703.
Initially, our plan was to go with `lit` SSR and put the install logic to a subdomain. When further thinking about doing this, we saw the following Pros and Cons:

**Pros**
- no problem with node polyfills anymore
- (maybe) easier sharable

**Cons**
- `inlang/install` is a core part of inlang.com, it is not an own product like `Fink`
- lit SSR is experimental and most likely changes in the future, will bring a lot of maintainability efforts while it is initially not hard to set up
- expensive to host such a small application for 20$ per month
- all services are spread out on render.com, not intuitive anymore and hard to comprehend what's going on when you deploy
- design has always to be aligned with `inlang.com`, but it is completely separated and uses other technology
- and last but not least: we want lix to work in the browser! – Why do we then have to remove it from our own real use "example"? It's like we have to remove paraglide JS from our website because it doesn't work. 

## Proposal
Treat `inlang/install` like `inlang/badge`. Introduce it as a service that can be fetched from any of our apps e.g. `inlang.com/api/install`. This would be completely unopinionated and allows `Fink` to install apps directly inside of the editor.

The install process subpages then can stay inside of the website too.

Example:
<img width="912" alt="Screenshot 2023-11-23 at 12 15 02 PM" src="https://github.com/inlang/monorepo/assets/92092993/df0de69f-0834-42dc-b1ea-976fdf326bb2">

**Comment by flornkm** [comment]
EDIT: For Fink, it absolutely made sense to unbundle, as the editor is its own product.

But for install: `inlang.com` is the product -> install is a core part of it. 

inlang/install is one feature the PRODUCT `inlang.com` offers. I hope this is clear to everyone!

@inlang/website @samuelstroschein please clarify this, I'm sure we don't want to move forward with a decision that doesn't make sense long term.

**Comment by janfjohannes** [comment]
why should install not be part of the editor? also i am not sure i understand what you mean with "service", could you explain?

**Comment by flornkm** [comment]
@janfjohannes my proposal is about install being so flexible to be integrated into the editor via API request (which isn't the case yet). service = being requestable from any app like the badge

**Comment by janfjohannes** [comment]
@flornkm  ok then the title is confusing "Why adding a new server and unbundling install .." becuase to run it like the badge this would still require unbundling the install command and also running it on its own server.

**Comment by flornkm** [comment]
@janfjohannes ah thanks, better now?

**Comment by janfjohannes** [comment]
@flornkm   no website is really ambigous too :D after reading throught the ticket again i think what you talk about is putting the install command on a path routing instead of giving it its own subdomain?

i am all for that!

**Comment by flornkm** [comment]
@janfjohannes that's not what was discussed yesterday. I don't know if you were there, it is about a "new website" built with lit components just for installation (so installation is completely stand-alone), so I think the term "website" describes quite well what everyone thought about.

**Comment by janfjohannes** [comment]
@flornkm  no was not there, got it. my only strong oppinion is to not put install on a subdomain, but on a path.

**Comment by samuelstroschein** [comment]
Summary of the call: 

- decided to unbundle because we expect more logic like uninstall, update versions, etc. in the future
- decided for `manage.inlang.com` to allow apps to add a "manage modules" button that forwards to this site and avoid every app to build their own ui
- the app can be a pure SPA (no vike required) and should be built with lit

**Comment by flornkm** [comment]
We decided to go with `manage.inlang.com` as a SPA. The issue for the implementation is #1703
