### ISSUE TITLE
[bug] vs code extract message handle quotes in plain strings better

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1726]
### Problem

**extracting a message like so:**
```js
const message = 'some message'
//               ^^^^^^^^^^^^ selected (without quotes)
```
puts the resulting m. function into the original quotes:
```js
const message = 'm.some_message()'
```
i have to remove the quotes from js

**option 2:**
```js
const message = 'some message'
//              ^^^^^^^^^^^^^^ selected (with the quotes)
```
puts the quotes in the resulting translation:
```json
{
  "some_message": "'some message'"
}
```
i have to remove the quotes from json

### Expected behavior

i would not have to do manual fixup when running the `Extract Message` command

### Reproduction

see section Problem.

### Other information

Vivaldi latest stable
Windows 10
VS Code Ext version 1.20.0

**Comment by felixhaeberle** [comment]
Indeed. We need to change that and check for quotes. I'll add a check that

- `'some message'`
- `"another message"`
- ``backtick message``

gets properly handled.

**Comment by KraXen72** [comment]
rad! 👍
