### ISSUE TITLE
[bug] typescript: availableLanguageTags.includes cannot cope with 'string'

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1729]
### Problem

when i want to runtime test whether a potential language tag is valid (for example, after getting it from localStorage or url, etc)
i would want to check it with `availableLanguageTags.includes`

however, typescript knows the explicit type of availableLanguageTags, so it throws:
```ts
const paramLang = params.get('lang');
if (!paramLang || !availableLanguageTags.includes(paramLang)) return;
//                                                ^^^^^^^^^
// error: Argument of type 'string' is not assignable to parameter of type '"en" | "sk"'.
```
there is quite an easy workaround: lie to typescript:
```ts
const paramLang = params.get('lang') as AvailableLanguageTag;
if (!paramLang || !availableLanguageTags.includes(paramLang)) return;
// no error
```

as long as you first check that the variable is defined and can be passed into the `.includes()` method, this is fine. but it leaves a bad taste in my mouth, and i think there should be a better solution

### Expected behavior

there are several ways to go about this, but the one i can think of right now (not saying it's the best idea by any means) is defining the parameter of `Array.prototype.includes` on `availableLanguageTags` to explicitly be 'string'

### Reproduction

see section Problem

### Other information

Vivaldi Latest stable
windows 10
inlang vscode ext v1.20.0

**Comment by LorisSigrist** [comment]
I'm not sure i like overriding the `Array.prototype.includes` method. This kinda just is how typescript works. 

I would recommend instead defining an `isLanguageTag` function like so:

```ts
function isLanguageTag(thing: any) : thing is AvailableLanguageTag {
    return availableLanguageTags.includes(thing)
}
```

Because of the `thing is AvailableLanguageTag`, type-narrowing will work.

We might include such a function in paraglide in future, since we also need that quite often in the adapters

**Comment by samuelstroschein** [comment]
Interesting suggestion @LorisSigrist. 

Small suggestion: changing the function name to `isAvailableLanguageTag` reads natural.

**Comment by KraXen72** [comment]
> ```ts
> function isLanguageTag(thing: any) : thing is AvailableLanguageTag {
>     return availableLanguageTags.includes(thing)
> }
> ```

not sure about the any, better to use unknown, no? also, never seen that 'is' thingy but if it works, sure.

**Comment by LorisSigrist** [comment]
If you don't have the `any` you end up with the same issue as before, where the compiler complains that `unknown is not assignable to "en" | "sk"`.

The `is` thingy is called a type-guard. They're pretty cool.
https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types

They allow you to write code like
```ts
const potentialLanguageTag : string = "fr"
if(isAvailableLanguageTag(potentialLanguageTag)) {
   //in here potentialLanguageTag has type AvailableLanguageTag
} else {
   //in here potentialLanguageTag has type string
}

```

**Comment by KraXen72** [comment]
okay. is there possibly a better name than isAvailableLanguageTag?
