### ISSUE TITLE
i18n checker as growth instrument for recurring users on inlang.com

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1730]
> This was brought up by @openscript https://discord.com/channels/897438559458430986/1072193070797430955/1177272009680502814

## Problem 
Our goal is to have more returning users on inlang.com. We should improve the value first-timers will get when not directly adopting apps.

## Proposal: Add a i18n checker that gives insight about i18n status of an URL

This proposal could be the first step to get the way to go for i18n insights.

## MVP - as simple as possible
- We should keep it simple
- An initial value could be enough to proof if this helps to get returning users
- Robin proposed someone who can do it (I would try to accomplish a MVP on a checker route in ~10 hours, @openscript comment if you disagree)
- Just input and results in a list

## Strategy
1. Build MVP in hours
2. Let it live for some days
3. Analyse with posthog
4. See if we get returning users on the checker

@inlang/website @openscript @samuelstroschein @felixhaeberle @NiklasBuchfink 
What do you think folks, should we continue this opportunity?
👍👎

**Comment by felixhaeberle** [comment]
My answer. https://www.loom.com/share/267820b6d10649af91c46fe20bbd9891

I like it. Especially if we do it very minimal, in an MVP way.

**Comment by jannesblobel** [comment]
even if i am not tagged, it is similar to the google ranking checker. 

The problem I see is not the development effort but the whole thing around it. 
If there are bugs, who does it? Who promotes it? Who takes care of seo? ..... 

I see a lot of potential in the future if you can promote such tools. It is another App and we see it on the badge, it's also just a good MVP but needs time and attention

**Comment by NilsJacobsen** [comment]
> Who promotes it? Who takes care of SEO?

Nobody. I would for now only use it as free value for users to make them returning. 

> If there are bugs, who does it?

If this thing has no dependencies on inlang, it can be built and live. @openscript do you think that will consume a lot of maintenance efforts?

**Comment by NilsJacobsen** [comment]
Change to i18n-checker, that leaves a WOW in the face of the user.
Feedback welcome:
https://www.loom.com/share/606609e0cc32474e942e9c2d3f571d5d?sid=8b78fe2b-ba67-4b20-9e49-838fa6964438

**Comment by jannesblobel** [comment]
@samuelstroschein 
> Instead, build a product page on inlang.com that describes the SEO/link checker tool

What do you mean by this? Why do I need a product page without a product?

**Comment by NilsJacobsen** [comment]
Gonna close it tomorrow when the page is ready.

**Comment by NilsJacobsen** [comment]
I added this page. 
https://inlang.com/m/92fst3wd/app-inlang-globelens
We will work on SEO and see how it performs. Update will come.
