### ISSUE TITLE
[bug] Inlang editor keeps marking my translations as missing

### ISSUE THREAD

**Issue by stmr** [inlang/monorepo#1736]
### Problem

![Screenshot 2023-11-24 at 16-39-48 stmr_AppFlowy](https://github.com/inlang/monorepo/assets/1045974/aff77047-18c0-4641-b6b0-dea171de9672)
System: Linux
Browser: Firefox 119.0.1

As seen in the screenshot Inlang editor keeps marking my translations as missing even though I have put the translation in there. This is causing around 60% of my translations to get lost.

There was nothing interesting in the browser console, just constant warnings about cookies being set over and over again

I've already translated all strings twice in Inlang pushing after every 50-150 strings translated but overall it shows just around 100 strings translated and pushed to git.

### Expected behavior

I did expect my translation to either be marked as fine or as 

### Reproduction

Exact steps to reproduce:

1. Fork https://inlang.com/editor/github.com/AppFlowy-IO/AppFlowy
2. Create cs language tag
3. Start translating to Czech language
4. Pay attention to the check mark at the end of the input line

After reloading Inlang editor I am able to translate the same strings easily and even push them but it breaks quickly

### Other information

System: Linux
Browser: Firefox 119.0.1

**Comment by stmr** [comment]
I think it might be related to https://github.com/inlang/monorepo/issues/1710

**Comment by stmr** [comment]
Breaks more often on phrases with special characters from my locale "ěščřžýáíéťúůďňó"

**Comment by NiklasBuchfink** [comment]
@stmr This should be fixed now ✅  Do not mind the short delay in updating the warning. This is due to the debouncing of the input. :)

**Comment by stmr** [comment]
@NiklasBuchfink great thanks!
