### ISSUE TITLE
[bug] Inlang editor - Missing translation phrases are counted to "Push" counter but are not pushed

### ISSUE THREAD

**Issue by stmr** [inlang/monorepo#1737]
### Problem

Phrases that are marked as "Missing translation" but also with green check mark get counted to the "Push to GitHub" counter. After pressing the "Push" button they are not propagated to git. After reloading the Inlang editor the phrases are still in the "Lint is Missing translation" filter without any translation present (makes sense as they were not pushed).

This is misleading and causes one to believe that the work is done when in fact it doesn't push all of it to Git.
![Screenshot 2023-11-24 at 17-08-06 stmr_AppFlowy](https://github.com/inlang/monorepo/assets/1045974/b8295604-2bd1-4856-a3c6-95914c318740)

### Expected behavior

Phrases that won't be pushed to Git are not counted into the "Push to GitHub" counter OR they are pushed to Git once they have been counted in.

### Reproduction

1. Get phrases into this condition https://github.com/inlang/monorepo/issues/1736
2. Check the counter inside "Push to GitHub" button
3. Push the "Push to GitHub" button
4. Check Git
5. Reload Inlang editor repo and set filter to "Missing translation" phrases
6. Locate the phrases that you believed were pushed

### Other information

System: Linux
Browser: Firefox 119.0.1

**Comment by samuelstroschein** [comment]
@stmr thanks for the bug report. I assigned @NiklasBuchfink who is in charge of the editor and already stated that he will dedicate the entire next week to fix bugs. 

Have a great weekend! :)

**Comment by stmr** [comment]
Alternative name for this bug could be: "Filled in translation is marked as both valid and missing translation"

**Comment by NiklasBuchfink** [comment]
#1736 and this issue are almost the same. The message doesn't update correctly and therefore, it isn't marked and pushed as expected.

**Comment by NiklasBuchfink** [comment]
@stmr As it was related, this is fixed as well ✅
I rechecked it with the AppFlowy repo and everything is now updating and pushing as expected.

---
**Side note:** I noticed that some languages are missing in the `project.inlang.json`. These won't show up. You can add them to the file or if they are valid BCP-47 language tags, you can add them via the fink editor :)

**Comment by stmr** [comment]
@NiklasBuchfink Thanks a lot for the update and fix!
