### ISSUE TITLE
make --project an argument instead of a requiredoption 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1738]
## Context 

Minor "nice to have" now that `--project` is required https://github.com/inlang/monorepo/pull/1716. We could get rid of the `--project` flag in the CLI altogether. 

```diff
-"build": "paraglide-js compile --project ./frontend.inlang && tsc",
+"build": "paraglide-js compile ./frontend.inlang && tsc",
```

## Proposal

Let's ask paraglide pre-release users what they think. This is a really minor improvement and not worth a long debate/breaking change after 1.0

**Comment by AdamTmHun** [comment]
Maybe we could make it look for a default `project.inlang.json` or a `projectName.inlang.json` (projectName is grabbed from the package.json) in the directory of where the command was ran from (usually the project root). Thus simplifying it even further.
```diff
-"build": "paraglide-js compile --project ./frontend.inlang && tsc",
-"build": "paraglide-js compile ./frontend.inlang && tsc",
+"build": "paraglide-js compile && tsc",
```
And simply this in terminal:
```terminal
npx paraglide-js compile
```

**Comment by samuelstroschein** [comment]
We just removed a default path yesterday :D See https://github.com/inlang/monorepo/pull/1716

**Comment by AdamTmHun** [comment]
Ah, I see. Kinda annoying to type every time without adding a script, but I guess to avoid confusion it is better. That's what Adding a script is what I should do anyway.

**Comment by samuelstroschein** [comment]
ACtually, never mind. This issue is so minor. The inlang CLI also uses `--project` so let's keep it that way.

**Comment by felixhaeberle** [comment]
really minor.
