### ISSUE TITLE
[bug] paraglide vite adapter missing 'repository' field in package.json

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1739]
### Problem

the paraglide vite adapter is missing 'repository' field in package.json.
this means, on npm.com you can't go to the repository of the adapter, and have to search for it manually

### Expected behavior

there would a repo field

### Reproduction

see `package.json` of `@inlang/paraglide-js-adapter-vite`

### Other information

win 10
vivaldi latest stable

**Comment by samuelstroschein** [comment]
@KraXen72 why are you opening all the issues as bug? there are improvements/no bugs. are the templates not intuitive?

**Comment by KraXen72** [comment]
sorry, afaik the improvement template only got added very recently and i missed it. i'll use it in the future for improvement-related issues
