### ISSUE TITLE
[bug] paraglide unplugin adapter compiles 3 times per change

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1740]
### Problem

per each change in the json files, paraglide unplugin run the compile command 3 times
![image](https://github.com/inlang/monorepo/assets/21956756/a33ab713-ca0c-409b-8b49-69a8a2687006)

### Expected behavior

it would only run once

### Reproduction

install an unplugin-based paraglide-js adapter
see console output

**Comment by LorisSigrist** [comment]
Did this only happen on startup or on every message change?

**Comment by KraXen72** [comment]
now it's 5 times lol
![image](https://github.com/inlang/monorepo/assets/21956756/8e85370c-167c-4ca7-a2fa-1925eb9863ed)

(i changed 1 key, it was used in more components, so maybe that's what triggered the re-comp)

probably just throttle (1 every second) or debounce (200ms) the compilation.
another potential solution is to diffing the jsons?

**Comment by LorisSigrist** [comment]
@inlang/sdk 
This seems to be an issue with `project.query.messages.getAll.subscribe((messages)=>{ ... })` firing multiple times for each message change.

**Comment by samuelstroschein** [comment]
We need a better state/reactivity management in the SDK. I opened an issue https://github.com/inlang/monorepo/issues/1772#issue-2014953299

**Comment by LorisSigrist** [comment]
The root cause of this seems to be that `fs.watch()` is bad at it's job. If we replace that with something less terrible this should get fixed.
