### ISSUE TITLE
[bug] paraglide unplugin silent option not mentioned in type UserConfig

### ISSUE THREAD

**Issue by KraXen72** [inlang/monorepo#1741]
### Problem

paraglide unplugin: silent option is not mentioned in type UserConfig, so there's no intellisense for it => users don't know it exists

### Expected behavior

the UserConfig type would include `silent?: boolean`

### Reproduction

```ts
// vite.config.ts
import { paraglide } from '@inlang/paraglide-js-adapter-vite';

export default defineConfig({
	plugins: [
		UnoCSS(),
		sveltekit(),
		paraglide({ // no intellisense for silent here
			project: './project.inlang.json',
			outdir: './src/paraglide'
		}),
	],
	 optimizeDeps: {
		exclude: ['@inlang/paraglide-js']
	},
	ssr: {
		noExternal: ['@inlang/paraglide-js']
	}
	// possibly more stuff
}

```

**Comment by samuelstroschein** [comment]
Silent for not loggin stuff? 

Related to #1742. @LorisSigrist I would remove the usage of the CLI in the bundler plugin und directly use the `compile` function to avoid CLI logs.
