### ISSUE TITLE
[bug] pnpm clean fails

### ISSUE THREAD

**Issue by ezhil56x** [inlang/monorepo#1744]
### Problem

After installing all the required packages unable. `pnpm clean` can be used to remove all the node_modules and few other folder. But `pnpm clean` throws errors and fails to remove the folders

### Expected behavior

It should remove node_modules, dist folders, env

### Reproduction

1. pnpm install
2. pnpm clean

### Other information

$ pnpm clean

> monorepo@ clean /Developer/monorepo
> pnpm recursive run clean --if-present && rm -rf ./.env ./node_modules

Scope: 54 of 55 workspace projects
inlang/source-code/design-system clean$ rm -rf ./dist ./node_modules "--if-present"
│ rm: unrecognized option '--if-present'
│ Try 'rm --help' for more information.
└─ Failed in 78ms at /Developer/monorepo/inlang/source-code/design-system
inlang/source-code/json-types clean$ rm -rf ./dist ./node_modules "--if-present"
│ rm: unrecognized option '--if-present'
│ Try 'rm --help' for more information.
└─ Failed in 102ms at /Developer/monorepo/inlang/source-code/json-types
.../source-code/detect-json-formatting clean$ rm -rf ./dist ./coverage ./node_modules "--if-present"
│ rm: unrecognized option '--if-present'
│ Try 'rm --help' for more information.
└─ Failed in 99ms at /Developer/monorepo/inlang/source-code/detect-json-formatting
inlang/source-code/markdown clean$ rm -rf ./dist ./node_modules "--if-present"
│ rm: unrecognized option '--if-present'
│ Try 'rm --help' for more information.
└─ Failed in 117ms at /Developer/monorepo/inlang/source-code/markdown
/Developer/monorepo/inlang/source-code/design-system:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @inlang/design-system@ clean: `rm -rf ./dist ./node_modules "--if-present"`
Exit status 1
inlang/source-code/result clean$ rm -rf ./dist ./node_modules "--if-present"
│ rm: unrecognized option '--if-present'
│ Try 'rm --help' for more information.
└─ Failed in 59ms at /Developer/monorepo/inlang/source-code/result
lix/source-code/fs clean$ rm -rf ./dist ./node_modules "--if-present"
└─ Running...
.../versioned-interfaces/language-tag clean$ rm -rf ./dist ./node_modules "--if-present"
└─ Running...
 ELIFECYCLE  Command failed with exit code 1.

**Comment by LorisSigrist** [comment]
Which OS are you running on?

**Comment by ezhil56x** [comment]
> Which OS are you running on?

Ubuntu 22.04.3 lts

**Comment by LorisSigrist** [comment]
Ok, seems to have been an easy fix.

We still had an `--if-present` around from before we switched to `pnpm`. This was needed to only run `clean` in packages that had a `clean` command. This isn't needed anymore, since `pnpm recursive` behaves correctly by default. 
For some reason this extra flag was passed to the `rm` command on your machine. Probably a linux thing.

Should be good now
