### ISSUE TITLE
Clarify messaging around Paraglide's Treeshaking

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1747]
## Problem 
I've talked to several people who've used paraglide, and many seemed to misunderstand the point of tree-shaking messages. 
People believe that the treeshaking is there to remove unused messages from an _app_. That's true, but not the primary advantage. The primary advantage is that the messages bundle can get split, so that each _page_ only loads the messages that it needs. 
This currently isn't communicated properly.

## Proposal
Update the documentation to clarify why tree-shaking is beneficial.

**Comment by samuelstroschein** [comment]
@LorisSigrist good point. the question about namespaces and why they are not required for paraglide comes up constantly. 

@flornkm can you work with @LorisSigrist to improve the product page and illustrate/communicate the benefits of tree-shaking better?

@LorisSigrist make use of @flornkm design skills to illustrate tree-shaking with a visualization :)

**Comment by flornkm** [comment]
@LorisSigrist happy to help, just ping me if you want to jump on a quick call to communicate the tree-shaking better.
