### ISSUE TITLE
[bug] bold text in headlines on marketplace a little too bold

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1751]
### Problem

<img width="1033" alt="Bildschirmfoto 2023-11-27 um 10 45 46" src="https://github.com/inlang/monorepo/assets/34959078/1a5164ae-03a4-49f6-8da0-876a18984539">

### Expected behavior

Maybe we can "flatten" the bold style in order that if we are already displaying the headline in bold, the bold tag gets ignored / is not displayed bold.

### Reproduction

https://inlang.com/m/r7kp499g/app-inlang-ideExtension

### Other information

-

**Comment by flornkm** [comment]
@felixhaeberle Should be fixed with https://github.com/inlang/monorepo/commit/ab7ed40fafc439cfebe59e9833245d541e97426f
I flattened it.
