### ISSUE TITLE
[bug] Watcher in inlang SDK breaks fink for large language configurations 

### ISSUE THREAD

**Issue by NiklasBuchfink** [inlang/monorepo#1769]
### Problem

Messages no longer update reliably within Fink for projects with large language configurations.

Every language file path creates its own watcher. When a message pattern gets updated by the `saveMessage` function, the following happens:
1. all watchers get triggered by `saveMessage`
2. all watchers execute `loadMessage` again
3. the reactive map for linting needs to be created again (the same thing that is blocking the loading time)

This results in:
- performance issues
- wrong linting state
- UI and data are not in sync
- PRs with cut-off or broken translations

Many users are complaining about this and filing issues:
- #1710 
- #1736 
- #1737 

---
cc @inlang/sdk
@felixhaeberle Please check if there is an issue with the VS code extension for projects with large language configuration

### Expected behavior

We had granular message updating and linting before. A change of one message pattern should only trigger the linting of this single message.

A temporary fix for this would be an SDK option to disable the watcher within the editor:

```js
loadProject({
  ...
  watcher: false
})
```

It only needs to appear in the SDK doc if other apps experience something similar.

### Reproduction

1. Add a log to the linting effect within `Message.tsx`
2. Open a project with a large language configuration like Appflowy
3. Update two messages
4. Look at the counter in the dev console

### Other information

We risk losing projects that highly benefit from the editor and have it in their readme/docs.

**Comment by NilsJacobsen** [comment]
https://github.com/inlang/monorepo/issues/1590#issuecomment-1798837192

**Comment by NiklasBuchfink** [comment]
> [#1590 (comment)](https://github.com/inlang/monorepo/issues/1590#issuecomment-1798837192)

@samuelstroschein The comment indicated that these issues can't get fixed until the dir proposal and the importer & exporter are implemented. Is this correct?

**Comment by janfjohannes** [comment]
@NilsJacobsen @NiklasBuchfink the #1590 is not related to this one or am i missing something?

**Comment by NilsJacobsen** [comment]
Maybe related

**Comment by samuelstroschein** [comment]
I add this issue as a requirement to #1585. Importer and exporter should not trigger watch if changes happened from an inlang project.  

---

@NiklasBuchfink you can likely temporarily fix this without API changes by overwriting `nodeishFs.watch`:

```ts
// pseudocode
const nodeishFs = createMemoryFs()
// @ts-expect-error
nodeishFs.watch = () => undefined

const project = await loadProject({ nodeishFs })
``` 

> @janfjohannes  wait didnt we say to avoid one watcher per file? any setup wehere there could be hundreds of watchers will break. ideally we can watch a folder that contains the message files and the inlang config file.

Out of our control. We have to watch individual files that plugins load. Those might be in a directory, or might not. We don't know. #1585 will ease the situation. The majority of inlang projects that use paraglide won't need plugins anymore. How we save messages is in our full control.

**Comment by NiklasBuchfink** [comment]
The overwrite of the watcher worked, and we have added an exception that sets the message as before the change. This was necessary in order to trigger the linting.
