### ISSUE TITLE
Add built in `--watch` option to `paraglide-js compile`

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1770]
## Problem 
While we do have the bundler plugins, automatically recompiling messages on change is still a pain for anyone not using one of the plugins. You either have to add a second build command just for messages, or bring your own watcher.

Since NextJS & React Native projects can't make use of our bundler plugins, this leaves quite a large part of our potential Userbase affected. 

Given that we already have a message-watcher in the inlang SDK, it shouldn't be that hard to add a `--watch` flag to the compile command, so that messages would be continually recompiled during development. 

## Proposal
Add a `--watch` flag to the `paraglide-js compile` command

**Comment by KraXen72** [comment]
if you need a fast message watcher, therer is https://github.com/parcel-bundler/watcher, which is used internally by vscode
