### ISSUE TITLE
fix cause for nx crashes

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1773]
## Problem 

<img width="995" alt="CleanShot 2023-11-28 at 21 23 18@2x" src="https://github.com/inlang/monorepo/assets/35429197/d2920fc6-31f7-4207-8f40-1186e46d5a08">

## Reproduction

the code beneath copies template directories into dist which makes the deployment easier but screws up nx. copy out the code and `pnpm run build` runs through reliably. 

```
// TODO: this line crashes NX because it changes the output folder irrespective of nx caching
```

https://github.com/inlang/monorepo/blob/8f84d98ff2dd3fed93ccbafa0a287c24355692a5/inlang/source-code/cli/build.js#L47-L53

**Comment by LorisSigrist** [comment]
I've disabled the NX Daemon outright now. 

It seems to have been causing a lot of problems, and it's not required for NX to work.
All it is is a watcher process that precomputes which part's of the cache should be invalidated. Disabling it will cause _slightly_ slower command start times on development machines and have no impact on CI. 

Should be good now

**Comment by samuelstroschein** [comment]
Seems to run reliably now.
