### ISSUE TITLE
updated docs needed for 2.0.0

### ISSUE THREAD

**Issue by MaxMillington** [inlang/monorepo#1790]
## Problem 

I upgraded my inlang to 2.0.0. Now, my scripts no longer work:

```
"machine-translate": "inlang machine translate && yarn fix-machine-translate",
 "fix-machine-translate": "node fix-machine-translate.js"
 ```
 
 ```
 yarn machine-translate
yarn run v1.22.19
$ inlang machine translate && yarn fix-machine-translate
error: required option '--project <path>' not specified
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It looks like in the new version of inlang, the `project` option is now required and it is expecting a format of `{name}.inlang` , but in the [docs](https://github.com/inlang/monorepo/tree/main/inlang/source-code/cli), it still says that the root is the default and that inlang will look for a `project.inlang.json` file. 
## Proposal

Can we get updated docs in the read.me and ideally a quick migration guide?

**Comment by samuelstroschein** [comment]
@MaxMillington I opened https://github.com/osmosis-labs/osmosis-frontend/pull/2490 to fix the issue on your side. 

The auto migration for https://github.com/inlang/monorepo/issues/1678, in combination with updating to v2 of the CLI simultaneously, did not work. I updated the docs and removed the reference of the root file. 

PS with the project directory you can soon move the project into your frontend folder. There won't be a need for projects at the root of a repo anymore :)
