### ISSUE TITLE
[bug] Fink editor only updates a select language and not others

### ISSUE THREAD

**Issue by xKesvaL** [inlang/monorepo#1794]
### Problem

When using the Inlang fink editor and updating something, only 1 language changed gets pushed. In my case I have the `en`, `de` and `fr` language and regardless of what I change in `en` or `de` it's not pushed at all. For `fr`, it works fine.

### Reproduction

Go to [https://github.com/xKesvaL/leetstrength](https://github.com/xKesvaL/leetstrength)
Go to the `feature/issue-13` branch 
Try to change anything in the `en` or `de` languages
See that nothing is being pushed

**Comment by NiklasBuchfink** [comment]
I can reproduce it 👍 I will take care of it and let you know what went wrong and when it is fixed.

Lovely starter btw 😉

**Comment by xKesvaL** [comment]
Thanks a lot really, I love how you guys really account for the community's feedback.

;)

**Comment by xKesvaL** [comment]
Nice! Since you just made me discover it, I'm going to switch to `plugin-json` anyways to use namespaces
At least people won't have my issue if they use `plugin-message-format` :)

**Comment by NiklasBuchfink** [comment]
`plugin-message-format` can now be used safely again with the Fink editor ✅
