### ISSUE TITLE
[bug] setLanguageTag not working when used in onMount ?

### ISSUE THREAD

**Issue by MarArMar** [inlang/monorepo#1804]
### Problem

In SvelteKit, if I do

```svelte
<script lang="ts">
import { onMount } from 'svelte'
import * as m from '$lang/messages'
import { setLanguageTag } from '$lang/runtime'

setLanguageTag('sk')
</script>
m.hello_world() : '{m.hello_world()}'
```
It changes the language

But if I do

```svelte
<script lang="ts">
import { onMount } from 'svelte'
import * as m from '$lang/messages'
import { setLanguageTag } from '$lang/runtime'

onMount(() => {
  setLanguageTag('sk')
})

</script>
m.hello_world() : '{m.hello_world()}'
```

It does not

Is this normal ? Certainly feels abnormal to me, how would I be able to change the displayed language ?

### Expected behavior

Change the display language

### Reproduction

Test showcased code

**Comment by MarArMar** [comment]
Will read the guide to make sure I understand

https://inlang.com/g/2fg8ng94/guide-nilsjacobsen-buildAGlobalSvelteApp

**Comment by samuelstroschein** [comment]
You likely implemented the adapter a wrong. The app does not seem to re-render. Here is a short explainer video https://www.loom.com/share/3f3361df14c64c04898aba0d518beb6d. 

In the meantime, @LorisSigrist will release an official plug & play SvelteKit adapter soon.
