### ISSUE TITLE
[bug] routing doesn't work when clicking on already picked language

### ISSUE THREAD

**Issue by flornkm** [inlang/monorepo#1806]
## Problem 
I've surfed inlang.com on mobile and clicked on the english language. The behavior I would expect is nothing to change as it was already selected.

https://github.com/inlang/monorepo/assets/92092993/4944c1b6-dc01-48bf-8e06-8d407166d497

## Proposal
Solution A: Make the checked option not clickable via pointer-events: none;

Solution B: Redirect to the correct URL (but that would trigger an unnecessary reload)

## Additional Information

- Maybe this bug is only appearing on mobile devices, will test again on a computer

**Comment by NilsJacobsen** [comment]
It should be fixed. Reopen if you can still experience it.
