### ISSUE TITLE
isomorphic git middleware does not call next() and blocks our cors headers middleware function

### ISSUE THREAD

**Issue by janfjohannes** [inlang/monorepo#1812]

**Comment by janfjohannes** [comment]
cc @flornkm   we have to fix this bug before merging the change again.

**Comment by janfjohannes** [comment]
worst case i have to fork the isogit middleware and fix the bug there.

**Comment by flornkm** [comment]
> update: had to fork iso git middleware and micro-cors to fix issue there

Thanks, let me know if you need anything from me for fixing that issue

**Comment by janfjohannes** [comment]
@flornkm  its all done, just review the pr and test that with your branch before merging  ;)
