### ISSUE TITLE
[bug] ide extension doesn't find new project directory

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1818]
### Problem

The ide extension doesn't find `project.inlang` directories. see https://github.com/inlang/monorepo/discussions/1808#discussion-5920766 and other user reports.

### Reproduction

/

**Comment by AdamTmHun** [comment]
# Temporary Fix
just simply copy your `project.inlang/settings.json` into a new file in the root dir, and name it `project.inlang.json`. You should have both files until the extension gets migrated.

**Comment by samuelstroschein** [comment]
@AdamTmHun thanks for the quickfix!

**Comment by samuelstroschein** [comment]
closes by [e237b49](https://github.com/inlang/monorepo/commit/e237b49425f417034930d61ba7ea309410fb5b40) update to version 1.22 of the ide extension. should be available in approx 20-30 minutes. 

the bug was caused by changeset not updating the ide extension version number :)
