### ISSUE TITLE
[Documentation] Add Guide for using Paraglide with Expo (React Native)

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1827]
## Opportunity

[Expo](https://docs.expo.dev/) is one of the most popular ways of writing & distributing a React Native Application. Because Paraglide is just JS, it's already super easy to integrate into an Expo project. All you need to do is get the device language using [`expo-localization`](https://docs.expo.dev/guides/localization/), resolving it to one of the available language tags and setting the language tag. That's it. 

If we (I) write a guide on how to do this & educate developers on it, then we greatly expand the potential userbase of paraglide. 
This seems like a relatively low effort opportunity.

**Comment by samuelstroschein** [comment]
I doubt that the effort of creating and maintaining a guide is worth it. I will send you a link with access to keywords everywhere.  

1. expo has an own guide for i18n/locaization. ranking higher than that one is unlikely. 
2. search interest is very low for "expo i18n" is only 200 per month. search for "expo localization" is only 1000 per month. For comparison "React i18n" is 9900 per month.  

![CleanShot 2023-12-05 at 09 43 26@2x](https://github.com/inlang/monorepo/assets/35429197/158e63b9-efa2-43ea-9547-789249aa2b1a)

**Comment by ashuvssut** [comment]
You can use [lingui](https://lingui.dev/tutorials/react-native) with expo-localization. lingui is nice. i am using it in my project. 

setting up lingui might not be that straight forward. but you can see their example react native app and blusky social app repository to copy paste code. its easy enough

But in case if you want to still findout how to use paraglide in React native, then you would have to do [these things](https://github.com/opral/paraglide-js/issues/551#issuecomment-3649161853). I created my own metro plugin and learnt the hard way that it is possible but its really not worth it. Using lingui is far better option for react native. It comes with reactive hooks like useLingui and non reactive macros and much more like Trans component for complex use cases.
