### ISSUE TITLE
[bug] IDE Extension doesn't resolve the closest inlang project

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1831]
### Problem

When working in a monorepo there might be a situation where there are multiple inlang projects with the same name in the tree. The IDE extension always picks the one that's the lowest in the tree.

Eg:
```
|- project.inlang             <-- This one always get's picked
|- some-project
    |- package.json
    |- project.inlang         <-- This one never get's picked
    |- src
         |- index.js              <- - doesn't see the correct messages
```

### Expected behavior

The Extension should use the inlang-project with the least "distance" to the file being viewed currently.

### Reproduction

In the monorepo, open any of the paraglide examples.

**Comment by samuelstroschein** [comment]
Put it on the list for #1832

**Comment by felixhaeberle** [comment]
closed as it's established with https://github.com/inlang/monorepo/commit/7d98c9c4253117498bc11ce5936be62ca6930d34
