### ISSUE TITLE
project selection in ide extension

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1832]
## Problem 

The ide extension does not allow the selection of projects leading to "bugs" like #1831 

## Proposal

Implement project selection logic. 

- [x] #1833
- [ ] UI to overwrite the default/automatically selected closest project with another one 

## Additional information 

The selection should be stored in the vscode workspace if possible. otherwise, we are forced to introduce a `.application-data` directory [for data shared across projects] now. We can do that if required but I would prefer little changes at a time.

**Comment by felixhaeberle** [comment]
this will also be solved through the inlang tab proposal — among a lot of other things which will be added step by step as needed.

**Comment by felixhaeberle** [comment]
related #1833

**Comment by felixhaeberle** [comment]
established with the lastest commit in https://github.com/inlang/monorepo/pull/1890/commits/6b425228b216e3edfccedbefb451dea60e97ce74 where you can now select your project from a list (you additionally get one auto selected if there are any).
