### ISSUE TITLE
auto detect a project closest to the user as a default

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1833]
To ease the getting started, do not require a project selection if ONE inlang project exists in the current workspace. 

### Sub-tasks

- [ ] https://github.com/inlang/monorepo/issues/1831
- [ ] implement logic if two or more projects exists in the same path

**Comment by felixhaeberle** [comment]
closed as it's established with https://github.com/inlang/monorepo/commit/7d98c9c4253117498bc11ce5936be62ca6930d34
