### ISSUE TITLE
cli: logs machine translate for each message, even if not writing anything to fs

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1834]
## Problem 
This is spamming the terminal. 
![image](https://github.com/inlang/monorepo/assets/58360188/eb47b3d0-d7fc-44fa-9e35-a875e201a8c5)

## Proposal: Only log if you translated something for the message
@inlang/ide-extension

**Comment by samuelstroschein** [comment]
Yep, is fixed!
