### ISSUE TITLE
[bug] Inlang not generate paraglide folder when project using monorepo

### ISSUE THREAD

**Issue by harrytran998** [inlang/monorepo#1835]
### Problem

Like the title, I don't know why this does not work but seems this is a bug on Inlang internal.  Hope your team can check this 😆.

Here is the overview.
<img width="177" alt="image" src="https://github.com/inlang/monorepo/assets/24296018/136918c4-02b4-4d64-8446-72eb2c11caa1">

### Expected behavior

Everything works like what you do 😌.

### Reproduction

Clone this repo --> Do like the readme
https://github.com/harrytran998/repro-inlang-paraglide-monorepo

### Other information

MacOs 13 - Any browser

**Comment by LorisSigrist** [comment]
Will take a look!

**Comment by LorisSigrist** [comment]
@samuelstroschein 
Should we log a warning if no messages are found?

**Comment by samuelstroschein** [comment]
@LorisSigrist sounds good!
