### ISSUE TITLE
[bug] Website nav doesn't work when on Changelogs

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1842]
### Problem

The Navigation on the website doesn't work when on any Changelog page. Vike throws errors when trying to navigate. Going away from the changelog to the documentation tab fixes it.

### Expected behavior

The Nav works even when viewing a changelog

### Reproduction

Go to any of the Changelog pages:
Eg: https://inlang.com/m/gerre34r/library-inlang-paraglideJs?view=changelog

Try to use the Nav

### Other information

Arc Browser with Chromium 119

**Comment by samuelstroschein** [comment]
I can't reproduce the issue. Can you record a loom?

**Comment by LorisSigrist** [comment]
I can no longer reproduce it either. Maybe it was a cached dependency misbehaving? Anyway it fixed itself
