### ISSUE TITLE
[bug] Machine translate not including string parameters

### ISSUE THREAD

**Issue by jonator** [inlang/monorepo#1843]
### Problem

I don't know how I didn't notice this yet, but it appears machine translate doesn't handle the inclusion of string parameters (injecting values into the string) at all. This is a critical issue as we have many strings with parameters and this means that a lot of key information is missing for users of non-english languages.

One example of _many_:
[en.json](https://github.com/osmosis-labs/osmosis-frontend/blob/f4e0c72d367fa6664c595fd23d175aab7bb4c25b/packages/web/localizations/en.json#L30)
[es.json](https://github.com/osmosis-labs/osmosis-frontend/blob/f4e0c72d367fa6664c595fd23d175aab7bb4c25b/packages/web/localizations/es.json#L30)

I believe the ones we do have were manually translated a while back, before we had inlang.

### Expected behavior

Perhaps it needs to be configured in our [settings file](https://github.com/osmosis-labs/osmosis-frontend/blob/f4e0c72d367fa6664c595fd23d175aab7bb4c25b/project.inlang/settings.json). Inlang should be able to know that a parameter is in a reference language string and handle that accordingly.

### Reproduction

See links above to see strings with missing params.

### Other information

Ideally once a fix is in for this, we can do a force re-run on the entire reference language and generate all new translations that include the params.

**Comment by jonator** [comment]
Thanks!

**Comment by samuelstroschein** [comment]
Closing this issue due to https://github.com/inlang/monorepo/issues/1843#issuecomment-1846195519
