### ISSUE TITLE
increase visibility of tabs on docs

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1852]
## Problem 

The tabs on the docs are not raising attention. 

I was looking for the plugins docs and couldn't find them until I recalled that @NilsJacobsen might have implemented the tabs already. Users will have the same problem and not click on plugins. 

![CleanShot 2023-12-08 at 16 17 04@2x](https://github.com/inlang/monorepo/assets/35429197/6fc9fcc4-e3b3-4977-a376-a42981795c6c)

## Proposal

- [ ] add icons like posthog to increase visibility

<img width="1197" alt="CleanShot 2023-12-08 at 16 19 02@2x" src="https://github.com/inlang/monorepo/assets/35429197/8cef8a54-3801-4d89-a29b-3d83d0b3d6ee">

- [ ] maybe center the tabs like posthog to further increase visibility?

**Comment by NilsJacobsen** [comment]
There are 37% clicking on plugins, but I can improve it. Icons might be an easy win.

**Comment by NilsJacobsen** [comment]
<img width="1512" alt="image" src="https://github.com/inlang/monorepo/assets/58360188/c29e7b2a-e9dd-47e3-ad50-9922f61f1bdd">
Added icons. Let's see if it improves the click-through rate.
