### ISSUE TITLE
[bug] reserved keywords

### ISSUE THREAD

**Issue by torrfura** [inlang/monorepo#1855]
### Problem

There's is nothing stopping me from adding keys with reserved keywords:

```
{
   "delete": "Delete me"
}
```

compiles into:
```
export const delete = (params = {}, options = {}) => {
	const tag = options.languageTag ?? languageTag();
	if (tag === "en") return en.delete()
	return undefined
}
```

Which is not allowed.

`> npx inlang lint` no errors / warning is thrown, nor when running `> npx inlang machine translate ...`

Will only fail when client tries to compile.

### Expected behavior

Warnings / errors should be thrown if you supply reserved keys in .json files.

### Reproduction

Just add any of https://www.w3schools.com/js/js_reserved.asp in a `en.json` file.

**Comment by samuelstroschein** [comment]
That's a nice find! @LorisSigrist @torrfura should we write a new no javascript keyword as id lint rule?

I understand that you would expect lint warnings if reserved keywords are used. The fix would be straightforward: Have a new "no javascript keyword as id" message lint rule.

**Comment by LorisSigrist** [comment]
That should certainly be a lint rule. On top of that, the paraglide compiler itself should probably throw an error, since using JS keywords instead of identifiers is likely to break the entire modules file.
