### ISSUE TITLE
[bug] indentation ordered / unordered lists are not aligning with rest of content in docs 

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1859]
### Problem

<img width="399" alt="Bildschirmfoto 2023-12-11 um 09 43 13" src="https://github.com/inlang/monorepo/assets/34959078/808d5ae5-15f1-4946-9aa9-37a25b97e7c2">

### Expected behavior

Have them aligned with the rest of content in docs 
(also, on a side note, the different colors & font sizes + font weights makes it a bit busy)

### Reproduction

Go to https://inlang.com/documentation/architecture

### Other information

Chrome Version 119.0.6045.199 (Offizieller Build) (arm64)
macOS 13.6 (22G120)

**Comment by NilsJacobsen** [comment]
I see. I also vote for changing that.
