### ISSUE TITLE
is https://inlang.com/documentation/sdk – still needed?

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1860]
## Problem 

<img width="644" alt="Bildschirmfoto 2023-12-11 um 09 53 37" src="https://github.com/inlang/monorepo/assets/34959078/023eb054-3b96-4b1f-9f9e-7c1e0c6fee9c">

This page confused me when I got to the new SDK docs. There was a "What is the SDK" in the Overview section which was helpful but after arriving at Reference -> SDK paraglide was brought into the discussion (confusing for new users).

## Proposal

Remove this page or display the actual SDK Typedoc Reference there what users would expect when clicking on "SDK reference".

**Comment by NilsJacobsen** [comment]
Nope the page is slowly transitioning to divided pages (SDK, plugins, lint rules, publish content)
Gonna remove it today. 
Related -> https://github.com/inlang/monorepo/issues/1815

**Comment by NilsJacobsen** [comment]
I removed it.
