### ISSUE TITLE
[improvement/bug] Side navigation on the subpages is not independently scrollable 

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1866]
### Problem

The side navigation on the subpages is stuck on the scrollbar for the entire page. That makes the side navigation less valuable than it could be. Another problem is that the user can't see all the content in the navigation.

### Expected behavior

The side navigation needs a scrollbar so the user can scroll independently through the navigation. 

### Reproduction

1. go to https://inlang.com/m/gerre34r/library-inlang-paraglideJs
2. scroll down 

### Other information

https://www.loom.com/share/ca50cdd9a2f949959b9d7194e3241716

**Comment by flornkm** [comment]
This bug should be fixed with https://github.com/inlang/monorepo/commit/112c8bfd1515232b886a808846c3d185bf372037 
Please re-open if that happens again, scroll height has to be adjusted based on the height of main-navigation.
