### ISSUE TITLE
Improve support for Monorepos in the Web-Editor

### ISSUE THREAD

**Issue by LorisSigrist** [inlang/monorepo#1867]
## Problem 
In #1858 i had to disappoint someone about using inlang's webeditor with a monorepo. It can (I believe) currently only be done if the inlang-project is at the _root_ of the workspace. You can't have individual projects per app. (please do correct me if I'm wrong here)

Monorepos are common among enterprise users, so  having better support for them would be nice.
Given that we ourselves also use a monorepo, we too would benefit from this. 

## Proposal
Enable selecting a subfolder to work within in the web editor.

**Comment by samuelstroschein** [comment]
@LorisSigrist please assign the person you deem to be in charge to ensure that issues get resolved as either closed or not going to be fixed

**Comment by NiklasBuchfink** [comment]
@LorisSigrist As you mentioned, it is common to have a mono repo, and the implementation of the directory proposal allows us to make that change now 👍

**Comment by NiklasBuchfink** [comment]
With #1935 we have now subfolder and multiproject support ✅
