### ISSUE TITLE
`Fink - Message editor` -> `fink.inlang.com` @NiklasBuchfink

### ISSUE THREAD

**Issue by flornkm** [inlang/monorepo#1873]
### Tasklist for moving Fink

- [x] Create `fink.inlang.com` domain
- [x] Redirect subdomain to the accurate render service domain via `CNAME entry`
- [x] Remove the proxy to the server from inlang's "main server"
- [x] Give it the name `fink-editor` on render.com for correct subdomain redirection
- [x] Make Fink run on default render port or on the port already declared
- [x] Create a new service in the render blueprint for starting the editor
- [x] (Maybe) we can lower the plan for the website as it doesn't need so much memory anymore?
- [x] Exclude fink from the start command in the root `package.json`
- [x] Implement redirection for all URLs leading to the editor
- [x] Change the badge generation URL to the new domain

**Comment by samuelstroschein** [comment]
I am gonna try to transfer the domain to godaddy now so you can do whatever you need without me

**Comment by samuelstroschein** [comment]
Still not working. I am in contact with namecheap. Let me know what DNS settings I should do for `fink.inlang.com`.
