### ISSUE TITLE
project ids

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1891]
## Problem 

We have difficulty improving inlang because projects have no project identifier for telemetry. We want answers to questions like "What plugins are used most often, and we should prioritize?", "What settings should we remove because they are not used?", etc. 

## Proposal

Introduce project identifiers. 

## Requirements

- [x] persistent in the project directory
- [x] no merge conflicts for users 
- [x] two (distributed) users should generate the same project id on first run
- [x] statistically unique

**Comment by samuelstroschein** [comment]
@janfjohannes do you want to implement this? 

- the requirements seem identical to repository ids that should come in the future
- you would get your hands dirty on the inlang SDK, given you more insights on requirements for lix

**Comment by janfjohannes** [comment]
@samuelstroschein  sure!
