### ISSUE TITLE
Sdk needs a repo  reference instead of only the fs

### ISSUE THREAD

**Issue by janfjohannes** [inlang/monorepo#1898]
## Problem 
We often run into issues not having lix/repo features in the sdk that lead to implementing features at the wrong abstraction level or hacky testing (cc @martin-lysk ) The current blocker is that predictable project ids should be generated based on the identity of the repository the are in but this info is only known to lix/git, not in the fs directly. 

## Proposal

As discussed with @samuelstroschein  we decided to add a required repo argument to loadProject next to the fs and then phase out the use of fs and deprecate that argument.

**Comment by samuelstroschein** [comment]
@janfjohannes is `createVirtualRepo()` for testing purposes (replaces `createMemoryFs()`) in the scope of the issue? 

```ts
import { createVirtualRepo } from "@lix-js/client"

const repo = await createVirtualRepo()
const project = await loadProject({ repository: repo, projectPath: "blalba.inlang" }) 

```

**Comment by martin-lysk** [comment]
Great we need a repo in the sdk for sure. Not for persistence i hope - but for a lot of other things like history queries, change detection, review logs and many other things. I guess there are cases where the project need to exist before the repo - like in parrot where project may start in figma but the connection to git comes at a later time.

**Comment by felixhaeberle** [comment]
Off-topic but I love how the SDK is getting more love since a few days 😍

**Comment by janfjohannes** [comment]
@samuelstroschein  createVirtulalRepo would require mocks for all github apis that are used which would be quite an undertaking and probably better done when we add support for other git providers and need to do this anyways.

 i recomend closing this ticket and i can of course provide mock features for any repo functions that a test you want reqires, if you want more tests now, please give a rough description for me to add them.

**Comment by samuelstroschein** [comment]
> createVirtulalRepo would require mocks for all github apis that are used which would be quite an undertaking 

Would throwing if external APIs are used be an option (via a proxy for example)? 

Seems logical that SDK devs want to pass a mock repo object to `loadProject` instead of: 

1. Create a virtual filesystem
2. open a repo with the virtual filesystem
3. load a project

**Comment by felixhaeberle** [comment]
> Seems logical that SDK devs want to pass a mock repo object to loadProject

Really important ❗️(even for ourselves to have a nice way to test functionality with loadProject)

**Comment by janfjohannes** [comment]
@here i added ar repo = mockRepo() function to lix/client
