### ISSUE TITLE
[bug] manage.inlang.com shows no installed lint rules

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1900]
### Problem

Lint rules are installed but not shown on manage.inlang.com

<img width="1068" alt="CleanShot 2023-12-16 at 12 16 49@2x" src="https://github.com/inlang/monorepo/assets/35429197/032c8e43-37a9-41df-8298-187740343052">

### Expected behavior

Show installed lint rules

### Reproduction

1. Open https://manage.inlang.com/?repo=github.com/inlang/monorepo&project=/project.inlang
2. Compare to https://github.com/inlang/monorepo/blob/main/project.inlang/settings.json

**Comment by flornkm** [comment]
Fixed with https://github.com/inlang/monorepo/commit/137020cd925271e82b98ba7155aba628ac6e9ff5
