### ISSUE TITLE
[bug] How to setup inlang guide is not found

### ISSUE THREAD

**Issue by buti1021** [inlang/monorepo#1901]
### Problem

It seems like there used to be a how to setup inlang guide (e.g., linked at the bottom of this page)
https://inlang.com/g/3go4f04m/guide-niklasbuchfink-whatIsInlang
This guide seems to not be available anymore

### Expected behavior

Expect working links

### Reproduction

Scroll down and click on the link https://inlang.com/g/3go4f04m/guide-niklasbuchfink-whatIsInlang

**Comment by LorisSigrist** [comment]
Thanks for pointing it out. The guide was removed for being outdated, I'll remove the link.

**Comment by LorisSigrist** [comment]
Should be fixed now. The site may not update for a couple hours because of jsDelivr caching. Thanks!
