### ISSUE TITLE
[bug] guides redirect is not working

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1925]
### Problem

The redirect of guide items is not working.

### Expected behavior

When entering the id it doesn't redirect to the post. It gives a 404.

### Reproduction

1. Follow that link https://inlang.com/g/2fg8ng94
2. See 404

### Other information

@inlang/martketplace-infrastructure

**Comment by NilsJacobsen** [comment]
@flornkm is that something we expect to work?

**Comment by flornkm** [comment]
@NilsJacobsen Yes. Will work on a fix.

**Comment by flornkm** [comment]
@NilsJacobsen have found out that you could also watch a module as a guide and vice versa. I have fixed this too:
<img width="1706" alt="Screenshot 2023-12-20 at 11 01 51 AM" src="https://github.com/inlang/monorepo/assets/92092993/fa13aa37-815a-4824-9ea3-e63f941bb9e4">

With https://github.com/inlang/monorepo/commit/9688b2c887ad733d946e79718e9b13742efe4bbd
