### ISSUE TITLE
[bug] Typos @ Build a Global Svelte App

### ISSUE THREAD

**Issue by rainerstudhalter** [inlang/monorepo#1930]
### Problem

There are some typos in the guide to "Build a Global Svelte App", that prevents SvelteKit from rendering without error.

### Reproduction

./src/params/lang.ts ... missing type declaration
`import { availableLanguageTags, AvailableLanguageTag } from "$paraglide/runtime"`
to
`{ availableLanguageTags, type AvailableLanguageTag } from "$paraglide/runtime"`

./src/routes/+layout.svelte ... missing comma before type
`import { setLanguageTag, sourceLanguageTag type AvailableLanguageTag } from "$paraglide/runtime";`
to
`import { setLanguageTag, sourceLanguageTag, type AvailableLanguageTag } from "$paraglide/runtime";`

./src/hooks.server.ts ... does not import sourceLanguageTag, which will be used in the handle function
`import { sourceLanguageTag } from "$paraglide/runtime";`

**Comment by LorisSigrist** [comment]
Thanks! I'll fix it

**Comment by LorisSigrist** [comment]
It may take an hour or so to update on the website because of jsDelivr's caching, but it should be good now
