### ISSUE TITLE
fink machine translation 404 error

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1958]
## Problem 
RPC can't be called from `fink.inlang.com`

## Proposal
Whitelist `fink.inlang.com` in RPC. 

Watch the screen recording here: https://jam.dev/c/7e2d908b-90d5-478e-9f5b-0eaed76a1f03

\-------------------------------------

**Website URL:**
[https://fink.inlang.com/github.com/inlang/example?lint=messageLintRule.inlang.missingTranslation&lang=en&lang=de](https://fink.inlang.com/github.com/inlang/example?lint=messageLintRule.inlang.missingTranslation&lang=en&lang=de)

**Device and browser info:**
Chrome 120.0.6099.109 (1600x838) | Mac OS (arm) 10.15.7

**Date and time:**
December 29th 2023 | 11:22pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/7e2d908b-90d5-478e-9f5b-0eaed76a1f03](https://jam.dev/c/7e2d908b-90d5-478e-9f5b-0eaed76a1f03)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by flornkm** [comment]
fixed with https://github.com/inlang/monorepo/commit/573f881f875900b5bbadbb5ca9afa04e361aa4e3
