### ISSUE TITLE
Resource plugin should not fail if no resources are present yet

### ISSUE THREAD

**Issue by ivanhofer** [inlang/monorepo#654]
I did want to use the plugin to create demo resources if no resources are present yet. But the plugin failed to load because the path where resources are located is not present on the filesystem. I can naively create the default path myself, but if the path is a custom one, I would create the wrong folder and the plugin will still crash.

So in order to implement this in a reliable way, the plugin needs to load even if the resource folder is not present.

Currently [`inlang-plugin-json`](https://github.com/samuelstroschein/inlang-plugin-json) fails to start if the resource folder `pathPattern` is not present.
I'm assuming this will be the case for other plugins too, so we need to make sure that we have a test for this use case.

**Comment by ivanhofer** [comment]
@samuelstroschein what do you think?

**Comment by samuelstroschein** [comment]
Yes, makes sense. We should have a `testPlugin` function that is exported from @inlang/core/plugin for plugins to test their stuff

**Comment by ivanhofer** [comment]
The plugin should also take care of writing resources to a path that does not exist yet (also recusrively)

**Comment by samuelstroschein** [comment]
Should be implemented by #948  https://github.com/inlang/inlang/blob/26e11c23f001f187fc25e7f38fc10aadcdc38f6b/source-code/plugins/i18next/src/plugin.test.ts#L39-L52

**Comment by ivanhofer** [comment]
The issue is still present.

1. create `inlang.config.js` file
```ts
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: jsonPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js"
	)
	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin/dist/index.js"
	)

	return {
		referenceLanguage: "en",
		plugins: [
			jsonPlugin({
				pathPattern: "./languages/{language}.json",
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
		],
	}
}
```
2. run `npx @inlang/cli@latest lint`

I get this error:
```bash
# The following errors occurred during the setup of plugins:

Failed to setup plugin 'samuelstroschein.inlangPluginJson':

ENOENT: no such file or directory, scandir 'languages'

# The following errors occurred during the validation of the config:

It seems you didn't set up a plugin to handle Resource files. See https://inlang.com/documentation/plugins/registry.
```

## Expected behavior:
The pluginshould not crash if the folder is not present on disk.

**Comment by NilsJacobsen** [comment]
Okey I will add a test.

**Comment by felixhaeberle** [comment]
@inlang/plugins can you verify that this works now after the refactor with i118next & json plugin?

**Comment by NiklasBuchfink** [comment]
@felixhaeberle The error is still present because an error is thrown if the directory does not exist.

**Comment by NiklasBuchfink** [comment]
@felixhaeberle @NilsJacobsen It doesn't crash and there is no error anymore.
- `npx @inlang/cli@latest lint`: command will lint no message and log "🎉 Linting successful."
- `npx @inlang/cli@latest machine translate`: 
"ℹ 📝 Translating to 2 languages.
ℹ Machine translate complete. "
- editor: No messages get loaded

What do you think, should we include a warning that no message was found and the `pathPattern` is probably wrong, the language files are missing or there are no messages yet?

**Comment by felixhaeberle** [comment]
@NiklasBuchfink Yes please, logging that no message was found and **not** display "Linting successful / Message translate completed" would probably be best.

**Comment by NiklasBuchfink** [comment]
@felixhaeberle Please go for it. The individual app should handle this if no message is found.

**Comment by felixhaeberle** [comment]
fixed by https://github.com/inlang/monorepo/pull/1398
